gx.evt.autoSkip=!1;
gx.define("gx0021",!1,function(){this.ServerClass="gx0021";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.hasEnterEvent=true;this.skipOnEnter=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){this.AV12pTanqueroEsclusasID=gx.fn.getIntegerValue("vPTANQUEROESCLUSASID",gx.thousandSeparator);this.AV13pTanqueroRango=gx.fn.getIntegerValue("vPTANQUERORANGO",gx.thousandSeparator)};this.e170x1_client=function(){this.clearMessages();
if(gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")=="AdvancedContainer"){gx.fn.setCtrlProperty("ADVANCEDCONTAINER","Class","AdvancedContainer AdvancedContainerVisible");gx.fn.setCtrlProperty("BTNTOGGLE","Class",gx.fn.getCtrlProperty("BTNTOGGLE","Class")+" BtnToggleActive")}else{gx.fn.setCtrlProperty("ADVANCEDCONTAINER","Class","AdvancedContainer");gx.fn.setCtrlProperty("BTNTOGGLE","Class","BtnToggle")}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")',ctrl:"ADVANCEDCONTAINER",
prop:"Class"},{ctrl:"BTNTOGGLE",prop:"Class"}])};this.e110x1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("TANQUERORANGOFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("TANQUERORANGOFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCTANQUERORANGO","Visible",true)}else{gx.fn.setCtrlProperty("TANQUERORANGOFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCTANQUERORANGO","Visible",
false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("TANQUERORANGOFILTERCONTAINER","Class")',ctrl:"TANQUERORANGOFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCTANQUERORANGO","Visible")',ctrl:"vCTANQUERORANGO",prop:"Visible"}])};this.e120x1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("TANQUEROTARIFACPSUABFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("TANQUEROTARIFACPSUABFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");
gx.fn.setCtrlProperty("vCTANQUEROTARIFACPSUAB","Visible",true)}else{gx.fn.setCtrlProperty("TANQUEROTARIFACPSUABFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCTANQUEROTARIFACPSUAB","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("TANQUEROTARIFACPSUABFILTERCONTAINER","Class")',ctrl:"TANQUEROTARIFACPSUABFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCTANQUEROTARIFACPSUAB","Visible")',ctrl:"vCTANQUEROTARIFACPSUAB",prop:"Visible"}])};this.e130x1_client=
function(){this.clearMessages();if(gx.fn.getCtrlProperty("TANQUEROBANDATMFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("TANQUEROBANDATMFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCTANQUEROBANDATM","Visible",true)}else{gx.fn.setCtrlProperty("TANQUEROBANDATMFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCTANQUEROBANDATM","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("TANQUEROBANDATMFILTERCONTAINER","Class")',
ctrl:"TANQUEROBANDATMFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCTANQUEROBANDATM","Visible")',ctrl:"vCTANQUEROBANDATM",prop:"Visible"}])};this.e140x1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("TANQUEROTARIFATMFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("TANQUEROTARIFATMFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCTANQUEROTARIFATM","Visible",true)}else{gx.fn.setCtrlProperty("TANQUEROTARIFATMFILTERCONTAINER",
"Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCTANQUEROTARIFATM","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("TANQUEROTARIFATMFILTERCONTAINER","Class")',ctrl:"TANQUEROTARIFATMFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCTANQUEROTARIFATM","Visible")',ctrl:"vCTANQUEROTARIFATM",prop:"Visible"}])};this.e150x1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("TANQUEROTARIFALASTREFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("TANQUEROTARIFALASTREFILTERCONTAINER",
"Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCTANQUEROTARIFALASTRE","Visible",true)}else{gx.fn.setCtrlProperty("TANQUEROTARIFALASTREFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCTANQUEROTARIFALASTRE","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("TANQUEROTARIFALASTREFILTERCONTAINER","Class")',ctrl:"TANQUEROTARIFALASTREFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCTANQUEROTARIFALASTRE","Visible")',
ctrl:"vCTANQUEROTARIFALASTRE",prop:"Visible"}])};this.e160x1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("TANQUEROBANDACPSUABFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("TANQUEROBANDACPSUABFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCTANQUEROBANDACPSUAB","Visible",true)}else{gx.fn.setCtrlProperty("TANQUEROBANDACPSUABFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCTANQUEROBANDACPSUAB",
"Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("TANQUEROBANDACPSUABFILTERCONTAINER","Class")',ctrl:"TANQUEROBANDACPSUABFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCTANQUEROBANDACPSUAB","Visible")',ctrl:"vCTANQUEROBANDACPSUAB",prop:"Visible"}])};this.e200x2_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e210x1_client=function(){this.executeServerEvent("CANCEL",true)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,
18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,72,73,75,76,77,78,79,80,81,82,83,84];this.GXLastCtrlId=84;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",74,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"gx0021",[],false,1,false,true,10,true,false,false,"",0,"px",gx.getMessage("GXM_newrow"),true,false,false,null,null,false,"",false,[1,1,1,1]);c.addBitmap("&Linkselection",
"vLINKSELECTION",75,0,"px",17,"px",null,"","","SelectionAttribute","WWActionColumn");c.addSingleLineEdit(3,76,"TANQUERORANGO",gx.getMessage("Identificador de rango"),"","TanqueroRango","int",0,"px",4,4,"right",null,[],3,"TanqueroRango",true,0,false,false,"Attribute",1,"WWColumn");c.addSingleLineEdit(4,77,"TANQUEROTARIFACPSUAB",gx.getMessage("Tarifa CP/SUAB"),"","TanqueroTarifaCPSUAB","decimal",0,"px",7,7,"right",null,[],4,"TanqueroTarifaCPSUAB",true,2,false,false,"Attribute",1,"WWColumn OptionalColumn");
c.addSingleLineEdit(5,78,"TANQUEROBANDATM",gx.getMessage("Banda TM"),"","TanqueroBandaTM","int",0,"px",12,12,"right",null,[],5,"TanqueroBandaTM",true,0,false,false,"Attribute",1,"WWColumn OptionalColumn");c.addSingleLineEdit(6,79,"TANQUEROTARIFATM",gx.getMessage("Tarifa TM"),"","TanqueroTarifaTM","decimal",0,"px",7,7,"right",null,[],6,"TanqueroTarifaTM",true,2,false,false,"Attribute",1,"WWColumn OptionalColumn");c.addSingleLineEdit(7,80,"TANQUEROTARIFALASTRE",gx.getMessage("Tarifa Lastre"),"","TanqueroTarifaLastre",
"decimal",0,"px",7,7,"right",null,[],7,"TanqueroTarifaLastre",true,2,false,false,"Attribute",1,"WWColumn OptionalColumn");c.addSingleLineEdit(8,81,"TANQUEROBANDACPSUAB",gx.getMessage("Banda en CP/SUAB"),"","TanqueroBandaCPSUAB","int",0,"px",10,10,"right",null,[],8,"TanqueroBandaCPSUAB",true,0,false,false,"DescriptionAttribute",1,"WWColumn");c.addComboBox(1,82,"TANQUEROESCLUSASID",gx.getMessage("Identificador de esclusa"),"TanqueroEsclusasID","int",null,0,false,false,0,"px","");this.setGrid(c);b[2]=
{fld:"",grid:0};b[3]={fld:"MAIN",grid:0};b[4]={fld:"",grid:0};b[5]={fld:"",grid:0};b[6]={fld:"ADVANCEDCONTAINER",grid:0};b[7]={fld:"",grid:0};b[8]={fld:"",grid:0};b[9]={fld:"TANQUERORANGOFILTERCONTAINER",grid:0};b[10]={fld:"",grid:0};b[11]={fld:"",grid:0};b[12]={fld:"LBLTANQUERORANGOFILTER",format:1,grid:0};b[13]={fld:"",grid:0};b[14]={fld:"",grid:0};b[15]={fld:"",grid:0};b[16]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],
fld:"vCTANQUERORANGO",gxz:"ZV6cTanqueroRango",gxold:"OV6cTanqueroRango",gxvar:"AV6cTanqueroRango",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV6cTanqueroRango=gx.num.intval(a)},v2z:function(a){gx.O.ZV6cTanqueroRango=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCTANQUERORANGO",gx.O.AV6cTanqueroRango,0)},c2v:function(){gx.O.AV6cTanqueroRango=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCTANQUERORANGO",gx.thousandSeparator)},nac:gx.falseFn};
b[17]={fld:"",grid:0};b[18]={fld:"",grid:0};b[19]={fld:"TANQUEROTARIFACPSUABFILTERCONTAINER",grid:0};b[20]={fld:"",grid:0};b[21]={fld:"",grid:0};b[22]={fld:"LBLTANQUEROTARIFACPSUABFILTER",format:1,grid:0};b[23]={fld:"",grid:0};b[24]={fld:"",grid:0};b[25]={fld:"",grid:0};b[26]={lvl:0,type:"decimal",len:7,dec:2,sign:false,pic:"ZZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCTANQUEROTARIFACPSUAB",gxz:"ZV7cTanqueroTarifaCPSUAB",gxold:"OV7cTanqueroTarifaCPSUAB",
gxvar:"AV7cTanqueroTarifaCPSUAB",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV7cTanqueroTarifaCPSUAB=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.ZV7cTanqueroTarifaCPSUAB=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("vCTANQUEROTARIFACPSUAB",gx.O.AV7cTanqueroTarifaCPSUAB,2,gx.decimalPoint)},c2v:function(){gx.O.AV7cTanqueroTarifaCPSUAB=this.val()},val:function(){return gx.fn.getDecimalValue("vCTANQUEROTARIFACPSUAB",
gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};b[27]={fld:"",grid:0};b[28]={fld:"",grid:0};b[29]={fld:"TANQUEROBANDATMFILTERCONTAINER",grid:0};b[30]={fld:"",grid:0};b[31]={fld:"",grid:0};b[32]={fld:"LBLTANQUEROBANDATMFILTER",format:1,grid:0};b[33]={fld:"",grid:0};b[34]={fld:"",grid:0};b[35]={fld:"",grid:0};b[36]={lvl:0,type:"int",len:12,dec:0,sign:false,pic:"ZZZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCTANQUEROBANDATM",gxz:"ZV8cTanqueroBandaTM",
gxold:"OV8cTanqueroBandaTM",gxvar:"AV8cTanqueroBandaTM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV8cTanqueroBandaTM=gx.num.intval(a)},v2z:function(a){gx.O.ZV8cTanqueroBandaTM=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCTANQUEROBANDATM",gx.O.AV8cTanqueroBandaTM,0)},c2v:function(){gx.O.AV8cTanqueroBandaTM=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCTANQUEROBANDATM",gx.thousandSeparator)},nac:gx.falseFn};b[37]={fld:"",grid:0};b[38]=
{fld:"",grid:0};b[39]={fld:"TANQUEROTARIFATMFILTERCONTAINER",grid:0};b[40]={fld:"",grid:0};b[41]={fld:"",grid:0};b[42]={fld:"LBLTANQUEROTARIFATMFILTER",format:1,grid:0};b[43]={fld:"",grid:0};b[44]={fld:"",grid:0};b[45]={fld:"",grid:0};b[46]={lvl:0,type:"decimal",len:7,dec:2,sign:false,pic:"ZZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCTANQUEROTARIFATM",gxz:"ZV9cTanqueroTarifaTM",gxold:"OV9cTanqueroTarifaTM",gxvar:"AV9cTanqueroTarifaTM",ucs:[],op:[],ip:[],
nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV9cTanqueroTarifaTM=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.ZV9cTanqueroTarifaTM=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("vCTANQUEROTARIFATM",gx.O.AV9cTanqueroTarifaTM,2,gx.decimalPoint)},c2v:function(){gx.O.AV9cTanqueroTarifaTM=this.val()},val:function(){return gx.fn.getDecimalValue("vCTANQUEROTARIFATM",gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};b[47]={fld:"",grid:0};
b[48]={fld:"",grid:0};b[49]={fld:"TANQUEROTARIFALASTREFILTERCONTAINER",grid:0};b[50]={fld:"",grid:0};b[51]={fld:"",grid:0};b[52]={fld:"LBLTANQUEROTARIFALASTREFILTER",format:1,grid:0};b[53]={fld:"",grid:0};b[54]={fld:"",grid:0};b[55]={fld:"",grid:0};b[56]={lvl:0,type:"decimal",len:7,dec:2,sign:false,pic:"ZZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCTANQUEROTARIFALASTRE",gxz:"ZV10cTanqueroTarifaLastre",gxold:"OV10cTanqueroTarifaLastre",gxvar:"AV10cTanqueroTarifaLastre",
ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10cTanqueroTarifaLastre=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.ZV10cTanqueroTarifaLastre=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("vCTANQUEROTARIFALASTRE",gx.O.AV10cTanqueroTarifaLastre,2,gx.decimalPoint)},c2v:function(){gx.O.AV10cTanqueroTarifaLastre=this.val()},val:function(){return gx.fn.getDecimalValue("vCTANQUEROTARIFALASTRE",gx.thousandSeparator,gx.decimalPoint)},
nac:gx.falseFn};b[57]={fld:"",grid:0};b[58]={fld:"",grid:0};b[59]={fld:"TANQUEROBANDACPSUABFILTERCONTAINER",grid:0};b[60]={fld:"",grid:0};b[61]={fld:"",grid:0};b[62]={fld:"LBLTANQUEROBANDACPSUABFILTER",format:1,grid:0};b[63]={fld:"",grid:0};b[64]={fld:"",grid:0};b[65]={fld:"",grid:0};b[66]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCTANQUEROBANDACPSUAB",gxz:"ZV11cTanqueroBandaCPSUAB",gxold:"OV11cTanqueroBandaCPSUAB",
gxvar:"AV11cTanqueroBandaCPSUAB",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11cTanqueroBandaCPSUAB=gx.num.intval(a)},v2z:function(a){gx.O.ZV11cTanqueroBandaCPSUAB=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCTANQUEROBANDACPSUAB",gx.O.AV11cTanqueroBandaCPSUAB,0)},c2v:function(){gx.O.AV11cTanqueroBandaCPSUAB=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCTANQUEROBANDACPSUAB",gx.thousandSeparator)},nac:gx.falseFn};b[67]={fld:"",grid:0};
b[68]={fld:"GRIDTABLE",grid:0};b[69]={fld:"",grid:0};b[70]={fld:"",grid:0};b[72]={fld:"",grid:0};b[73]={fld:"",grid:0};b[75]={lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:74,gxgrid:this.Grid1Container,fnc:null,isvalid:null,fld:"vLINKSELECTION",gxz:"ZV5LinkSelection",gxold:"OV5LinkSelection",gxvar:"AV5LinkSelection",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.AV5LinkSelection=a},v2z:function(a){gx.O.ZV5LinkSelection=a},v2c:function(a){gx.fn.setGridMultimediaValue("vLINKSELECTION",
a||gx.fn.currentGridRowImpl(74),gx.O.AV5LinkSelection,gx.O.AV17Linkselection_GXI)},c2v:function(){gx.O.AV17Linkselection_GXI=this.val_GXI();gx.O.AV5LinkSelection=this.val()},val:function(a){return gx.fn.getGridControlValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(74))},val_GXI:function(a){return gx.fn.getGridControlValue("vLINKSELECTION_GXI",a||gx.fn.currentGridRowImpl(74))},gxvar_GXI:"AV17Linkselection_GXI",nac:gx.falseFn};b[76]={lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:1,isacc:0,
grid:74,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TANQUERORANGO",gxz:"Z3TanqueroRango",gxold:"O3TanqueroRango",gxvar:"A3TanqueroRango",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A3TanqueroRango=gx.num.intval(a)},v2z:function(a){gx.O.Z3TanqueroRango=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("TANQUERORANGO",a||gx.fn.currentGridRowImpl(74),gx.O.A3TanqueroRango,0)},c2v:function(){gx.O.A3TanqueroRango=gx.num.intval(this.val())},
val:function(a){return gx.fn.getGridIntegerValue("TANQUERORANGO",a||gx.fn.currentGridRowImpl(74),gx.thousandSeparator)},nac:gx.falseFn};b[77]={lvl:2,type:"decimal",len:7,dec:2,sign:false,pic:"ZZZ9.99",ro:1,isacc:0,grid:74,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TANQUEROTARIFACPSUAB",gxz:"Z4TanqueroTarifaCPSUAB",gxold:"O4TanqueroTarifaCPSUAB",gxvar:"A4TanqueroTarifaCPSUAB",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A4TanqueroTarifaCPSUAB=
gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.Z4TanqueroTarifaCPSUAB=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(a){gx.fn.setGridDecimalValue("TANQUEROTARIFACPSUAB",a||gx.fn.currentGridRowImpl(74),gx.O.A4TanqueroTarifaCPSUAB,2,gx.decimalPoint);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A4TanqueroTarifaCPSUAB=gx.fn.toDecimalValue(this.val(),",",".")},val:function(a){return gx.fn.getGridDecimalValue("TANQUEROTARIFACPSUAB",a||
gx.fn.currentGridRowImpl(74),gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};b[78]={lvl:2,type:"int",len:12,dec:0,sign:false,pic:"ZZZZZZZZZZZ9",ro:1,isacc:0,grid:74,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TANQUEROBANDATM",gxz:"Z5TanqueroBandaTM",gxold:"O5TanqueroBandaTM",gxvar:"A5TanqueroBandaTM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A5TanqueroBandaTM=gx.num.intval(a)},v2z:function(a){gx.O.Z5TanqueroBandaTM=gx.num.intval(a)},
v2c:function(a){gx.fn.setGridControlValue("TANQUEROBANDATM",a||gx.fn.currentGridRowImpl(74),gx.O.A5TanqueroBandaTM,0)},c2v:function(){gx.O.A5TanqueroBandaTM=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("TANQUEROBANDATM",a||gx.fn.currentGridRowImpl(74),gx.thousandSeparator)},nac:gx.falseFn};b[79]={lvl:2,type:"decimal",len:7,dec:2,sign:false,pic:"ZZZ9.99",ro:1,isacc:0,grid:74,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TANQUEROTARIFATM",gxz:"Z6TanqueroTarifaTM",
gxold:"O6TanqueroTarifaTM",gxvar:"A6TanqueroTarifaTM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A6TanqueroTarifaTM=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.Z6TanqueroTarifaTM=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(a){gx.fn.setGridDecimalValue("TANQUEROTARIFATM",a||gx.fn.currentGridRowImpl(74),gx.O.A6TanqueroTarifaTM,2,gx.decimalPoint);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A6TanqueroTarifaTM=
gx.fn.toDecimalValue(this.val(),",",".")},val:function(a){return gx.fn.getGridDecimalValue("TANQUEROTARIFATM",a||gx.fn.currentGridRowImpl(74),gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};b[80]={lvl:2,type:"decimal",len:7,dec:2,sign:false,pic:"ZZZ9.99",ro:1,isacc:0,grid:74,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TANQUEROTARIFALASTRE",gxz:"Z7TanqueroTarifaLastre",gxold:"O7TanqueroTarifaLastre",gxvar:"A7TanqueroTarifaLastre",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",
inputType:"text",v2v:function(a){gx.O.A7TanqueroTarifaLastre=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.Z7TanqueroTarifaLastre=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(a){gx.fn.setGridDecimalValue("TANQUEROTARIFALASTRE",a||gx.fn.currentGridRowImpl(74),gx.O.A7TanqueroTarifaLastre,2,gx.decimalPoint);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A7TanqueroTarifaLastre=gx.fn.toDecimalValue(this.val(),",",".")},val:function(a){return gx.fn.getGridDecimalValue("TANQUEROTARIFALASTRE",
a||gx.fn.currentGridRowImpl(74),gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};b[81]={lvl:2,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:1,isacc:0,grid:74,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TANQUEROBANDACPSUAB",gxz:"Z8TanqueroBandaCPSUAB",gxold:"O8TanqueroBandaCPSUAB",gxvar:"A8TanqueroBandaCPSUAB",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A8TanqueroBandaCPSUAB=gx.num.intval(a)},v2z:function(a){gx.O.Z8TanqueroBandaCPSUAB=
gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("TANQUEROBANDACPSUAB",a||gx.fn.currentGridRowImpl(74),gx.O.A8TanqueroBandaCPSUAB,0)},c2v:function(){gx.O.A8TanqueroBandaCPSUAB=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("TANQUEROBANDACPSUAB",a||gx.fn.currentGridRowImpl(74),gx.thousandSeparator)},nac:gx.falseFn};b[82]={lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:1,isacc:0,grid:74,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"TANQUEROESCLUSASID",
gxz:"Z1TanqueroEsclusasID",gxold:"O1TanqueroEsclusasID",gxvar:"A1TanqueroEsclusasID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",inputType:"text",v2v:function(a){gx.O.A1TanqueroEsclusasID=gx.num.intval(a)},v2z:function(a){gx.O.Z1TanqueroEsclusasID=gx.num.intval(a)},v2c:function(a){gx.fn.setGridComboBoxValue("TANQUEROESCLUSASID",a||gx.fn.currentGridRowImpl(74),gx.O.A1TanqueroEsclusasID);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A1TanqueroEsclusasID=gx.num.intval(this.val())},
val:function(a){return gx.fn.getGridIntegerValue("TANQUEROESCLUSASID",a||gx.fn.currentGridRowImpl(74),gx.thousandSeparator)},nac:gx.falseFn};b[83]={fld:"",grid:0};b[84]={fld:"",grid:0};this.OV11cTanqueroBandaCPSUAB=this.ZV11cTanqueroBandaCPSUAB=this.AV11cTanqueroBandaCPSUAB=this.OV10cTanqueroTarifaLastre=this.ZV10cTanqueroTarifaLastre=this.AV10cTanqueroTarifaLastre=this.OV9cTanqueroTarifaTM=this.ZV9cTanqueroTarifaTM=this.AV9cTanqueroTarifaTM=this.OV8cTanqueroBandaTM=this.ZV8cTanqueroBandaTM=this.AV8cTanqueroBandaTM=
this.OV7cTanqueroTarifaCPSUAB=this.ZV7cTanqueroTarifaCPSUAB=this.AV7cTanqueroTarifaCPSUAB=this.OV6cTanqueroRango=this.ZV6cTanqueroRango=this.AV6cTanqueroRango=0;this.OV5LinkSelection=this.ZV5LinkSelection="";this.AV13pTanqueroRango=this.AV12pTanqueroEsclusasID=this.AV11cTanqueroBandaCPSUAB=this.AV10cTanqueroTarifaLastre=this.AV9cTanqueroTarifaTM=this.AV8cTanqueroBandaTM=this.AV7cTanqueroTarifaCPSUAB=this.AV6cTanqueroRango=this.O1TanqueroEsclusasID=this.Z1TanqueroEsclusasID=this.O8TanqueroBandaCPSUAB=
this.Z8TanqueroBandaCPSUAB=this.O7TanqueroTarifaLastre=this.Z7TanqueroTarifaLastre=this.O6TanqueroTarifaTM=this.Z6TanqueroTarifaTM=this.O5TanqueroBandaTM=this.Z5TanqueroBandaTM=this.O4TanqueroTarifaCPSUAB=this.Z4TanqueroTarifaCPSUAB=this.O3TanqueroRango=this.Z3TanqueroRango=0;this.AV5LinkSelection="";this.A1TanqueroEsclusasID=this.A8TanqueroBandaCPSUAB=this.A7TanqueroTarifaLastre=this.A6TanqueroTarifaTM=this.A5TanqueroBandaTM=this.A4TanqueroTarifaCPSUAB=this.A3TanqueroRango=0;this.Events={e200x2_client:["ENTER",
true],e210x1_client:["CANCEL",true],e170x1_client:["'TOGGLE'",false],e110x1_client:["LBLTANQUERORANGOFILTER.CLICK",false],e120x1_client:["LBLTANQUEROTARIFACPSUABFILTER.CLICK",false],e130x1_client:["LBLTANQUEROBANDATMFILTER.CLICK",false],e140x1_client:["LBLTANQUEROTARIFATMFILTER.CLICK",false],e150x1_client:["LBLTANQUEROTARIFALASTREFILTER.CLICK",false],e160x1_client:["LBLTANQUEROBANDACPSUABFILTER.CLICK",false]};this.EvtParms.REFRESH=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},
{av:"AV6cTanqueroRango",fld:"vCTANQUERORANGO"},{av:"AV7cTanqueroTarifaCPSUAB",fld:"vCTANQUEROTARIFACPSUAB"},{av:"AV8cTanqueroBandaTM",fld:"vCTANQUEROBANDATM"},{av:"AV9cTanqueroTarifaTM",fld:"vCTANQUEROTARIFATM"},{av:"AV10cTanqueroTarifaLastre",fld:"vCTANQUEROTARIFALASTRE"},{av:"AV11cTanqueroBandaCPSUAB",fld:"vCTANQUEROBANDACPSUAB"},{av:"AV12pTanqueroEsclusasID",fld:"vPTANQUEROESCLUSASID"}],[]];this.EvtParms["'TOGGLE'"]=[[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")',ctrl:"ADVANCEDCONTAINER",
prop:"Class"},{ctrl:"BTNTOGGLE",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")',ctrl:"ADVANCEDCONTAINER",prop:"Class"},{ctrl:"BTNTOGGLE",prop:"Class"}]];this.EvtParms["LBLTANQUERORANGOFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("TANQUERORANGOFILTERCONTAINER","Class")',ctrl:"TANQUERORANGOFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("TANQUERORANGOFILTERCONTAINER","Class")',ctrl:"TANQUERORANGOFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCTANQUERORANGO","Visible")',
ctrl:"vCTANQUERORANGO",prop:"Visible"}]];this.EvtParms["LBLTANQUEROTARIFACPSUABFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("TANQUEROTARIFACPSUABFILTERCONTAINER","Class")',ctrl:"TANQUEROTARIFACPSUABFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("TANQUEROTARIFACPSUABFILTERCONTAINER","Class")',ctrl:"TANQUEROTARIFACPSUABFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCTANQUEROTARIFACPSUAB","Visible")',ctrl:"vCTANQUEROTARIFACPSUAB",prop:"Visible"}]];this.EvtParms["LBLTANQUEROBANDATMFILTER.CLICK"]=
[[{av:'gx.fn.getCtrlProperty("TANQUEROBANDATMFILTERCONTAINER","Class")',ctrl:"TANQUEROBANDATMFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("TANQUEROBANDATMFILTERCONTAINER","Class")',ctrl:"TANQUEROBANDATMFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCTANQUEROBANDATM","Visible")',ctrl:"vCTANQUEROBANDATM",prop:"Visible"}]];this.EvtParms["LBLTANQUEROTARIFATMFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("TANQUEROTARIFATMFILTERCONTAINER","Class")',ctrl:"TANQUEROTARIFATMFILTERCONTAINER",
prop:"Class"}],[{av:'gx.fn.getCtrlProperty("TANQUEROTARIFATMFILTERCONTAINER","Class")',ctrl:"TANQUEROTARIFATMFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCTANQUEROTARIFATM","Visible")',ctrl:"vCTANQUEROTARIFATM",prop:"Visible"}]];this.EvtParms["LBLTANQUEROTARIFALASTREFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("TANQUEROTARIFALASTREFILTERCONTAINER","Class")',ctrl:"TANQUEROTARIFALASTREFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("TANQUEROTARIFALASTREFILTERCONTAINER","Class")',
ctrl:"TANQUEROTARIFALASTREFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCTANQUEROTARIFALASTRE","Visible")',ctrl:"vCTANQUEROTARIFALASTRE",prop:"Visible"}]];this.EvtParms["LBLTANQUEROBANDACPSUABFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("TANQUEROBANDACPSUABFILTERCONTAINER","Class")',ctrl:"TANQUEROBANDACPSUABFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("TANQUEROBANDACPSUABFILTERCONTAINER","Class")',ctrl:"TANQUEROBANDACPSUABFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCTANQUEROBANDACPSUAB","Visible")',
ctrl:"vCTANQUEROBANDACPSUAB",prop:"Visible"}]];this.EvtParms.ENTER=[[{av:"A3TanqueroRango",fld:"TANQUERORANGO"}],[{av:"AV13pTanqueroRango",fld:"vPTANQUERORANGO"}]];this.EvtParms.GRID1_FIRSTPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cTanqueroRango",fld:"vCTANQUERORANGO"},{av:"AV7cTanqueroTarifaCPSUAB",fld:"vCTANQUEROTARIFACPSUAB"},{av:"AV8cTanqueroBandaTM",fld:"vCTANQUEROBANDATM"},{av:"AV9cTanqueroTarifaTM",fld:"vCTANQUEROTARIFATM"},{av:"AV10cTanqueroTarifaLastre",
fld:"vCTANQUEROTARIFALASTRE"},{av:"AV11cTanqueroBandaCPSUAB",fld:"vCTANQUEROBANDACPSUAB"},{av:"AV12pTanqueroEsclusasID",fld:"vPTANQUEROESCLUSASID"}],[]];this.EvtParms.GRID1_PREVPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cTanqueroRango",fld:"vCTANQUERORANGO"},{av:"AV7cTanqueroTarifaCPSUAB",fld:"vCTANQUEROTARIFACPSUAB"},{av:"AV8cTanqueroBandaTM",fld:"vCTANQUEROBANDATM"},{av:"AV9cTanqueroTarifaTM",fld:"vCTANQUEROTARIFATM"},{av:"AV10cTanqueroTarifaLastre",fld:"vCTANQUEROTARIFALASTRE"},
{av:"AV11cTanqueroBandaCPSUAB",fld:"vCTANQUEROBANDACPSUAB"},{av:"AV12pTanqueroEsclusasID",fld:"vPTANQUEROESCLUSASID"}],[]];this.EvtParms.GRID1_NEXTPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cTanqueroRango",fld:"vCTANQUERORANGO"},{av:"AV7cTanqueroTarifaCPSUAB",fld:"vCTANQUEROTARIFACPSUAB"},{av:"AV8cTanqueroBandaTM",fld:"vCTANQUEROBANDATM"},{av:"AV9cTanqueroTarifaTM",fld:"vCTANQUEROTARIFATM"},{av:"AV10cTanqueroTarifaLastre",fld:"vCTANQUEROTARIFALASTRE"},{av:"AV11cTanqueroBandaCPSUAB",
fld:"vCTANQUEROBANDACPSUAB"},{av:"AV12pTanqueroEsclusasID",fld:"vPTANQUEROESCLUSASID"}],[]];this.EvtParms.GRID1_LASTPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cTanqueroRango",fld:"vCTANQUERORANGO"},{av:"AV7cTanqueroTarifaCPSUAB",fld:"vCTANQUEROTARIFACPSUAB"},{av:"AV8cTanqueroBandaTM",fld:"vCTANQUEROBANDATM"},{av:"AV9cTanqueroTarifaTM",fld:"vCTANQUEROTARIFATM"},{av:"AV10cTanqueroTarifaLastre",fld:"vCTANQUEROTARIFALASTRE"},{av:"AV11cTanqueroBandaCPSUAB",fld:"vCTANQUEROBANDACPSUAB"},
{av:"AV12pTanqueroEsclusasID",fld:"vPTANQUEROESCLUSASID"}],[]];this.setVCMap("AV12pTanqueroEsclusasID","vPTANQUEROESCLUSASID",0,"int");this.setVCMap("AV13pTanqueroRango","vPTANQUERORANGO",0,"int");this.setVCMap("AV12pTanqueroEsclusasID","vPTANQUEROESCLUSASID",0,"int");c.addRefreshingVar(this.GXValidFnc[16]);c.addRefreshingVar(this.GXValidFnc[26]);c.addRefreshingVar(this.GXValidFnc[36]);c.addRefreshingVar(this.GXValidFnc[46]);c.addRefreshingVar(this.GXValidFnc[56]);c.addRefreshingVar(this.GXValidFnc[66]);
c.addRefreshingVar({rfrVar:"AV12pTanqueroEsclusasID"});this.InitStandaloneVars()});gx.createParentObj(gx0021);
