gx.evt.autoSkip=!1;
gx.define("gx0060",!1,function(){this.ServerClass="gx0060";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.hasEnterEvent=true;this.skipOnEnter=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){this.AV8pPortaContenedoresEsclusa=gx.fn.getIntegerValue("vPPORTACONTENEDORESESCLUSA",gx.thousandSeparator)};this.Validv_Cportacontenedoresesclusa=function(){try{var a=gx.util.balloon.getNew("vCPORTACONTENEDORESESCLUSA");this.AnyError=
0;if(!(this.AV6cPortaContenedoresEsclusa==1||this.AV6cPortaContenedoresEsclusa==2||0==this.AV6cPortaContenedoresEsclusa))try{a.setError(gx.text.format(gx.getMessage("GXSPC_OutOfRange"),gx.getMessage("cPortaContenedoresEsclusa"),"","","","","","","",""));this.AnyError=1}catch(b){}}catch(c){}try{return a==null?true:a.show()}catch(d){}return true};this.e13101_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")=="AdvancedContainer"){gx.fn.setCtrlProperty("ADVANCEDCONTAINER",
"Class","AdvancedContainer AdvancedContainerVisible");gx.fn.setCtrlProperty("BTNTOGGLE","Class",gx.fn.getCtrlProperty("BTNTOGGLE","Class")+" BtnToggleActive")}else{gx.fn.setCtrlProperty("ADVANCEDCONTAINER","Class","AdvancedContainer");gx.fn.setCtrlProperty("BTNTOGGLE","Class","BtnToggle")}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")',ctrl:"ADVANCEDCONTAINER",prop:"Class"},{ctrl:"BTNTOGGLE",prop:"Class"}])};this.e11101_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("PORTACONTENEDORESESCLUSAFILTERCONTAINER",
"Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("PORTACONTENEDORESESCLUSAFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCPORTACONTENEDORESESCLUSA","Visible",true)}else{gx.fn.setCtrlProperty("PORTACONTENEDORESESCLUSAFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCPORTACONTENEDORESESCLUSA","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("PORTACONTENEDORESESCLUSAFILTERCONTAINER","Class")',ctrl:"PORTACONTENEDORESESCLUSAFILTERCONTAINER",
prop:"Class"},{ctrl:"vCPORTACONTENEDORESESCLUSA"}])};this.e12101_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("PORTACONTENEDORESESCLUSADESCFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("PORTACONTENEDORESESCLUSADESCFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCPORTACONTENEDORESESCLUSADESC","Visible",true)}else{gx.fn.setCtrlProperty("PORTACONTENEDORESESCLUSADESCFILTERCONTAINER","Class","AdvancedContainerItem");
gx.fn.setCtrlProperty("vCPORTACONTENEDORESESCLUSADESC","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("PORTACONTENEDORESESCLUSADESCFILTERCONTAINER","Class")',ctrl:"PORTACONTENEDORESESCLUSADESCFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCPORTACONTENEDORESESCLUSADESC","Visible")',ctrl:"vCPORTACONTENEDORESESCLUSADESC",prop:"Visible"}])};this.e16102_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e17101_client=function(){this.executeServerEvent("CANCEL",
true)};var b=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,32,33,35,36,37,38,39];this.GXLastCtrlId=39;var c=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",34,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"gx0060",[],false,1,false,true,10,true,false,false,"",0,"px",gx.getMessage("GXM_newrow"),true,false,false,null,null,false,"",false,[1,1,1,1]);c.addBitmap("&Linkselection","vLINKSELECTION",35,0,"px",17,
"px",null,"","","SelectionAttribute","WWActionColumn");c.addComboBox(22,36,"PORTACONTENEDORESESCLUSA",gx.getMessage("Esclusa"),"PortaContenedoresEsclusa","int",null,0,true,false,0,"px","WWColumn");c.addSingleLineEdit(23,37,"PORTACONTENEDORESESCLUSADESC",gx.getMessage("Descripci\u00f3n de la esclusa"),"","PortaContenedoresEsclusaDesc","svchar",0,"px",40,40,"left",null,[],23,"PortaContenedoresEsclusaDesc",true,0,false,false,"DescriptionAttribute",1,"WWColumn");this.setGrid(c);b[2]={fld:"",grid:0};b[3]=
{fld:"MAIN",grid:0};b[4]={fld:"",grid:0};b[5]={fld:"",grid:0};b[6]={fld:"ADVANCEDCONTAINER",grid:0};b[7]={fld:"",grid:0};b[8]={fld:"",grid:0};b[9]={fld:"PORTACONTENEDORESESCLUSAFILTERCONTAINER",grid:0};b[10]={fld:"",grid:0};b[11]={fld:"",grid:0};b[12]={fld:"LBLPORTACONTENEDORESESCLUSAFILTER",format:1,grid:0};b[13]={fld:"",grid:0};b[14]={fld:"",grid:0};b[15]={fld:"",grid:0};b[16]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Validv_Cportacontenedoresesclusa,isvalid:null,
rgrid:[this.Grid1Container],fld:"vCPORTACONTENEDORESESCLUSA",gxz:"ZV6cPortaContenedoresEsclusa",gxold:"OV6cPortaContenedoresEsclusa",gxvar:"AV6cPortaContenedoresEsclusa",ucs:[],op:[16],ip:[16],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.AV6cPortaContenedoresEsclusa=gx.num.intval(a)},v2z:function(a){gx.O.ZV6cPortaContenedoresEsclusa=gx.num.intval(a)},v2c:function(){gx.fn.setComboBoxValue("vCPORTACONTENEDORESESCLUSA",gx.O.AV6cPortaContenedoresEsclusa)},c2v:function(){gx.O.AV6cPortaContenedoresEsclusa=
gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCPORTACONTENEDORESESCLUSA",gx.thousandSeparator)},nac:gx.falseFn};b[17]={fld:"",grid:0};b[18]={fld:"",grid:0};b[19]={fld:"PORTACONTENEDORESESCLUSADESCFILTERCONTAINER",grid:0};b[20]={fld:"",grid:0};b[21]={fld:"",grid:0};b[22]={fld:"LBLPORTACONTENEDORESESCLUSADESCFILTER",format:1,grid:0};b[23]={fld:"",grid:0};b[24]={fld:"",grid:0};b[25]={fld:"",grid:0};b[26]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,
fnc:null,isvalid:null,fld:"vCPORTACONTENEDORESESCLUSADESC",gxz:"ZV7cPortaContenedoresEsclusaDesc",gxold:"OV7cPortaContenedoresEsclusaDesc",gxvar:"AV7cPortaContenedoresEsclusaDesc",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV7cPortaContenedoresEsclusaDesc=a},v2z:function(a){gx.O.ZV7cPortaContenedoresEsclusaDesc=a},v2c:function(){gx.fn.setControlValue("vCPORTACONTENEDORESESCLUSADESC",gx.O.AV7cPortaContenedoresEsclusaDesc,0)},c2v:function(){gx.O.AV7cPortaContenedoresEsclusaDesc=
this.val()},val:function(){return gx.fn.getControlValue("vCPORTACONTENEDORESESCLUSADESC")},nac:gx.falseFn};b[27]={fld:"",grid:0};b[28]={fld:"GRIDTABLE",grid:0};b[29]={fld:"",grid:0};b[30]={fld:"",grid:0};b[32]={fld:"",grid:0};b[33]={fld:"",grid:0};b[35]={lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:34,gxgrid:this.Grid1Container,fnc:null,isvalid:null,fld:"vLINKSELECTION",gxz:"ZV5LinkSelection",gxold:"OV5LinkSelection",gxvar:"AV5LinkSelection",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",
inputType:"text",v2v:function(a){gx.O.AV5LinkSelection=a},v2z:function(a){gx.O.ZV5LinkSelection=a},v2c:function(a){gx.fn.setGridMultimediaValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(34),gx.O.AV5LinkSelection,gx.O.AV12Linkselection_GXI)},c2v:function(){gx.O.AV12Linkselection_GXI=this.val_GXI();gx.O.AV5LinkSelection=this.val()},val:function(a){return gx.fn.getGridControlValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(34))},val_GXI:function(a){return gx.fn.getGridControlValue("vLINKSELECTION_GXI",
a||gx.fn.currentGridRowImpl(34))},gxvar_GXI:"AV12Linkselection_GXI",nac:gx.falseFn};b[36]={lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:1,isacc:0,grid:34,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"PORTACONTENEDORESESCLUSA",gxz:"Z22PortaContenedoresEsclusa",gxold:"O22PortaContenedoresEsclusa",gxvar:"A22PortaContenedoresEsclusa",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",inputType:"text",v2v:function(a){gx.O.A22PortaContenedoresEsclusa=gx.num.intval(a)},v2z:function(a){gx.O.Z22PortaContenedoresEsclusa=
gx.num.intval(a)},v2c:function(a){gx.fn.setGridComboBoxValue("PORTACONTENEDORESESCLUSA",a||gx.fn.currentGridRowImpl(34),gx.O.A22PortaContenedoresEsclusa);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A22PortaContenedoresEsclusa=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("PORTACONTENEDORESESCLUSA",a||gx.fn.currentGridRowImpl(34),gx.thousandSeparator)},nac:gx.falseFn};b[37]={lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:34,
gxgrid:this.Grid1Container,fnc:null,isvalid:null,fld:"PORTACONTENEDORESESCLUSADESC",gxz:"Z23PortaContenedoresEsclusaDesc",gxold:"O23PortaContenedoresEsclusaDesc",gxvar:"A23PortaContenedoresEsclusaDesc",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",autoCorrect:"1",v2v:function(a){gx.O.A23PortaContenedoresEsclusaDesc=a},v2z:function(a){gx.O.Z23PortaContenedoresEsclusaDesc=a},v2c:function(a){gx.fn.setGridControlValue("PORTACONTENEDORESESCLUSADESC",a||gx.fn.currentGridRowImpl(34),gx.O.A23PortaContenedoresEsclusaDesc,
0)},c2v:function(){gx.O.A23PortaContenedoresEsclusaDesc=this.val()},val:function(a){return gx.fn.getGridControlValue("PORTACONTENEDORESESCLUSADESC",a||gx.fn.currentGridRowImpl(34))},nac:gx.falseFn};b[38]={fld:"",grid:0};b[39]={fld:"",grid:0};this.OV6cPortaContenedoresEsclusa=this.ZV6cPortaContenedoresEsclusa=this.AV6cPortaContenedoresEsclusa=0;this.OV5LinkSelection=this.ZV5LinkSelection=this.OV7cPortaContenedoresEsclusaDesc=this.ZV7cPortaContenedoresEsclusaDesc=this.AV7cPortaContenedoresEsclusaDesc=
"";this.O22PortaContenedoresEsclusa=this.Z22PortaContenedoresEsclusa=0;this.O23PortaContenedoresEsclusaDesc=this.Z23PortaContenedoresEsclusaDesc="";this.AV6cPortaContenedoresEsclusa=0;this.AV7cPortaContenedoresEsclusaDesc="";this.AV8pPortaContenedoresEsclusa=0;this.AV5LinkSelection="";this.A22PortaContenedoresEsclusa=0;this.A23PortaContenedoresEsclusaDesc="";this.Events={e16102_client:["ENTER",true],e17101_client:["CANCEL",true],e13101_client:["'TOGGLE'",false],e11101_client:["LBLPORTACONTENEDORESESCLUSAFILTER.CLICK",
false],e12101_client:["LBLPORTACONTENEDORESESCLUSADESCFILTER.CLICK",false]};this.EvtParms.REFRESH=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cPortaContenedoresEsclusa",fld:"vCPORTACONTENEDORESESCLUSA"},{av:"AV7cPortaContenedoresEsclusaDesc",fld:"vCPORTACONTENEDORESESCLUSADESC"}],[]];this.EvtParms["'TOGGLE'"]=[[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")',ctrl:"ADVANCEDCONTAINER",prop:"Class"},{ctrl:"BTNTOGGLE",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")',
ctrl:"ADVANCEDCONTAINER",prop:"Class"},{ctrl:"BTNTOGGLE",prop:"Class"}]];this.EvtParms["LBLPORTACONTENEDORESESCLUSAFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("PORTACONTENEDORESESCLUSAFILTERCONTAINER","Class")',ctrl:"PORTACONTENEDORESESCLUSAFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("PORTACONTENEDORESESCLUSAFILTERCONTAINER","Class")',ctrl:"PORTACONTENEDORESESCLUSAFILTERCONTAINER",prop:"Class"},{ctrl:"vCPORTACONTENEDORESESCLUSA"}]];this.EvtParms["LBLPORTACONTENEDORESESCLUSADESCFILTER.CLICK"]=
[[{av:'gx.fn.getCtrlProperty("PORTACONTENEDORESESCLUSADESCFILTERCONTAINER","Class")',ctrl:"PORTACONTENEDORESESCLUSADESCFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("PORTACONTENEDORESESCLUSADESCFILTERCONTAINER","Class")',ctrl:"PORTACONTENEDORESESCLUSADESCFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCPORTACONTENEDORESESCLUSADESC","Visible")',ctrl:"vCPORTACONTENEDORESESCLUSADESC",prop:"Visible"}]];this.EvtParms.ENTER=[[{av:"A22PortaContenedoresEsclusa",fld:"PORTACONTENEDORESESCLUSA"}],
[{av:"AV8pPortaContenedoresEsclusa",fld:"vPPORTACONTENEDORESESCLUSA"}]];this.EvtParms.GRID1_FIRSTPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cPortaContenedoresEsclusa",fld:"vCPORTACONTENEDORESESCLUSA"},{av:"AV7cPortaContenedoresEsclusaDesc",fld:"vCPORTACONTENEDORESESCLUSADESC"}],[]];this.EvtParms.GRID1_PREVPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cPortaContenedoresEsclusa",fld:"vCPORTACONTENEDORESESCLUSA"},{av:"AV7cPortaContenedoresEsclusaDesc",
fld:"vCPORTACONTENEDORESESCLUSADESC"}],[]];this.EvtParms.GRID1_NEXTPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cPortaContenedoresEsclusa",fld:"vCPORTACONTENEDORESESCLUSA"},{av:"AV7cPortaContenedoresEsclusaDesc",fld:"vCPORTACONTENEDORESESCLUSADESC"}],[]];this.EvtParms.GRID1_LASTPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cPortaContenedoresEsclusa",fld:"vCPORTACONTENEDORESESCLUSA"},{av:"AV7cPortaContenedoresEsclusaDesc",
fld:"vCPORTACONTENEDORESESCLUSADESC"}],[]];this.setVCMap("AV8pPortaContenedoresEsclusa","vPPORTACONTENEDORESESCLUSA",0,"int");c.addRefreshingVar(this.GXValidFnc[16]);c.addRefreshingVar(this.GXValidFnc[26]);this.InitStandaloneVars()});gx.createParentObj(gx0060);
