gx.evt.autoSkip=!1;
gx.define("gx0090",!1,function(){this.ServerClass="gx0090";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.hasEnterEvent=true;this.skipOnEnter=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){this.AV11pREF_CGRAL_DESP_ID=gx.fn.getIntegerValue("vPREF_CGRAL_DESP_ID",gx.thousandSeparator)};this.e161o1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")=="AdvancedContainer"){gx.fn.setCtrlProperty("ADVANCEDCONTAINER",
"Class","AdvancedContainer AdvancedContainerVisible");gx.fn.setCtrlProperty("BTNTOGGLE","Class",gx.fn.getCtrlProperty("BTNTOGGLE","Class")+" BtnToggleActive")}else{gx.fn.setCtrlProperty("ADVANCEDCONTAINER","Class","AdvancedContainer");gx.fn.setCtrlProperty("BTNTOGGLE","Class","BtnToggle")}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")',ctrl:"ADVANCEDCONTAINER",prop:"Class"},{ctrl:"BTNTOGGLE",prop:"Class"}])};this.e111o1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("REF_CGRAL_DESP_IDFILTERCONTAINER",
"Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("REF_CGRAL_DESP_IDFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCREF_CGRAL_DESP_ID","Visible",true)}else{gx.fn.setCtrlProperty("REF_CGRAL_DESP_IDFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCREF_CGRAL_DESP_ID","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_IDFILTERCONTAINER","Class")',ctrl:"REF_CGRAL_DESP_IDFILTERCONTAINER",
prop:"Class"},{av:'gx.fn.getCtrlProperty("vCREF_CGRAL_DESP_ID","Visible")',ctrl:"vCREF_CGRAL_DESP_ID",prop:"Visible"}])};this.e121o1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("REF_CGRAL_DESP_TIPOFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("REF_CGRAL_DESP_TIPOFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCREF_CGRAL_DESP_TIPO","Visible",true)}else{gx.fn.setCtrlProperty("REF_CGRAL_DESP_TIPOFILTERCONTAINER",
"Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCREF_CGRAL_DESP_TIPO","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_TIPOFILTERCONTAINER","Class")',ctrl:"REF_CGRAL_DESP_TIPOFILTERCONTAINER",prop:"Class"},{ctrl:"vCREF_CGRAL_DESP_TIPO"}])};this.e131o1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("REF_CGRAL_DESP_ID_TON_TARIFFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("REF_CGRAL_DESP_ID_TON_TARIFFILTERCONTAINER",
"Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCREF_CGRAL_DESP_ID_TON_TARIF","Visible",true)}else{gx.fn.setCtrlProperty("REF_CGRAL_DESP_ID_TON_TARIFFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCREF_CGRAL_DESP_ID_TON_TARIF","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_ID_TON_TARIFFILTERCONTAINER","Class")',ctrl:"REF_CGRAL_DESP_ID_TON_TARIFFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCREF_CGRAL_DESP_ID_TON_TARIF","Visible")',
ctrl:"vCREF_CGRAL_DESP_ID_TON_TARIF",prop:"Visible"}])};this.e141o1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("REF_CGRAL_DESP_TON_TARIFFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("REF_CGRAL_DESP_TON_TARIFFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCREF_CGRAL_DESP_TON_TARIF","Visible",true)}else{gx.fn.setCtrlProperty("REF_CGRAL_DESP_TON_TARIFFILTERCONTAINER","Class","AdvancedContainerItem");
gx.fn.setCtrlProperty("vCREF_CGRAL_DESP_TON_TARIF","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_TON_TARIFFILTERCONTAINER","Class")',ctrl:"REF_CGRAL_DESP_TON_TARIFFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCREF_CGRAL_DESP_TON_TARIF","Visible")',ctrl:"vCREF_CGRAL_DESP_TON_TARIF",prop:"Visible"}])};this.e151o1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("REF_CGRAL_DESP_TARIFAFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("REF_CGRAL_DESP_TARIFAFILTERCONTAINER",
"Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCREF_CGRAL_DESP_TARIFA","Visible",true)}else{gx.fn.setCtrlProperty("REF_CGRAL_DESP_TARIFAFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCREF_CGRAL_DESP_TARIFA","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_TARIFAFILTERCONTAINER","Class")',ctrl:"REF_CGRAL_DESP_TARIFAFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCREF_CGRAL_DESP_TARIFA","Visible")',
ctrl:"vCREF_CGRAL_DESP_TARIFA",prop:"Visible"}])};this.e191o2_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e201o1_client=function(){this.executeServerEvent("CANCEL",true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,62,63,65,66,67,68,69,70];this.GXLastCtrlId=70;var b=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",
64,"Grid1","Grid1","Grid1Container",this.CmpContext,this.IsMasterPage,"gx0090",[],false,1,false,true,10,true,false,false,"",0,"px",gx.getMessage("GXM_newrow"),true,false,false,null,null,false,"",false,[1,1,1,1]);b.addBitmap("&Linkselection","vLINKSELECTION",65,0,"px",17,"px",null,"","","SelectionAttribute","WWActionColumn");b.addSingleLineEdit(49,66,"REF_CGRAL_DESP_ID",gx.getMessage("ID"),"","REF_CGRAL_DESP_ID","int",0,"px",4,4,"right",null,[],49,"REF_CGRAL_DESP_ID",true,0,false,false,"Attribute",
1,"WWColumn");b.addComboBox(45,67,"REF_CGRAL_DESP_TIPO",gx.getMessage("Tipo"),"REF_CGRAL_DESP_TIPO","svchar",null,0,true,false,0,"px","WWColumn OptionalColumn");b.addSingleLineEdit(48,68,"REF_CGRAL_DESP_ID_TON_TARIF",gx.getMessage("TON ID"),"","REF_CGRAL_DESP_ID_TON_TARIF","int",0,"px",4,4,"right",null,[],48,"REF_CGRAL_DESP_ID_TON_TARIF",true,0,false,false,"Attribute",1,"WWColumn OptionalColumn");this.setGrid(b);a[2]={fld:"",grid:0};a[3]={fld:"MAIN",grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};
a[6]={fld:"ADVANCEDCONTAINER",grid:0};a[7]={fld:"",grid:0};a[8]={fld:"",grid:0};a[9]={fld:"REF_CGRAL_DESP_IDFILTERCONTAINER",grid:0};a[10]={fld:"",grid:0};a[11]={fld:"",grid:0};a[12]={fld:"LBLREF_CGRAL_DESP_IDFILTER",format:1,grid:0};a[13]={fld:"",grid:0};a[14]={fld:"",grid:0};a[15]={fld:"",grid:0};a[16]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCREF_CGRAL_DESP_ID",gxz:"ZV6cREF_CGRAL_DESP_ID",gxold:"OV6cREF_CGRAL_DESP_ID",
gxvar:"AV6cREF_CGRAL_DESP_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV6cREF_CGRAL_DESP_ID=gx.num.intval(a)},v2z:function(a){gx.O.ZV6cREF_CGRAL_DESP_ID=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCREF_CGRAL_DESP_ID",gx.O.AV6cREF_CGRAL_DESP_ID,0)},c2v:function(){gx.O.AV6cREF_CGRAL_DESP_ID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCREF_CGRAL_DESP_ID",gx.thousandSeparator)},nac:gx.falseFn};a[17]={fld:"",grid:0};a[18]={fld:"",grid:0};
a[19]={fld:"REF_CGRAL_DESP_TIPOFILTERCONTAINER",grid:0};a[20]={fld:"",grid:0};a[21]={fld:"",grid:0};a[22]={fld:"LBLREF_CGRAL_DESP_TIPOFILTER",format:1,grid:0};a[23]={fld:"",grid:0};a[24]={fld:"",grid:0};a[25]={fld:"",grid:0};a[26]={lvl:0,type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vCREF_CGRAL_DESP_TIPO",gxz:"ZV7cREF_CGRAL_DESP_TIPO",gxold:"OV7cREF_CGRAL_DESP_TIPO",gxvar:"AV7cREF_CGRAL_DESP_TIPO",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.AV7cREF_CGRAL_DESP_TIPO=
a},v2z:function(a){gx.O.ZV7cREF_CGRAL_DESP_TIPO=a},v2c:function(){gx.fn.setComboBoxValue("vCREF_CGRAL_DESP_TIPO",gx.O.AV7cREF_CGRAL_DESP_TIPO)},c2v:function(){gx.O.AV7cREF_CGRAL_DESP_TIPO=this.val()},val:function(){return gx.fn.getControlValue("vCREF_CGRAL_DESP_TIPO")},nac:gx.falseFn};a[27]={fld:"",grid:0};a[28]={fld:"",grid:0};a[29]={fld:"REF_CGRAL_DESP_ID_TON_TARIFFILTERCONTAINER",grid:0};a[30]={fld:"",grid:0};a[31]={fld:"",grid:0};a[32]={fld:"LBLREF_CGRAL_DESP_ID_TON_TARIFFILTER",format:1,grid:0};
a[33]={fld:"",grid:0};a[34]={fld:"",grid:0};a[35]={fld:"",grid:0};a[36]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCREF_CGRAL_DESP_ID_TON_TARIF",gxz:"ZV8cREF_CGRAL_DESP_ID_TON_TARIF",gxold:"OV8cREF_CGRAL_DESP_ID_TON_TARIF",gxvar:"AV8cREF_CGRAL_DESP_ID_TON_TARIF",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV8cREF_CGRAL_DESP_ID_TON_TARIF=gx.num.intval(a)},v2z:function(a){gx.O.ZV8cREF_CGRAL_DESP_ID_TON_TARIF=
gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCREF_CGRAL_DESP_ID_TON_TARIF",gx.O.AV8cREF_CGRAL_DESP_ID_TON_TARIF,0)},c2v:function(){gx.O.AV8cREF_CGRAL_DESP_ID_TON_TARIF=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCREF_CGRAL_DESP_ID_TON_TARIF",gx.thousandSeparator)},nac:gx.falseFn};a[37]={fld:"",grid:0};a[38]={fld:"",grid:0};a[39]={fld:"REF_CGRAL_DESP_TON_TARIFFILTERCONTAINER",grid:0};a[40]={fld:"",grid:0};a[41]={fld:"",grid:0};a[42]={fld:"LBLREF_CGRAL_DESP_TON_TARIFFILTER",
format:1,grid:0};a[43]={fld:"",grid:0};a[44]={fld:"",grid:0};a[45]={fld:"",grid:0};a[46]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCREF_CGRAL_DESP_TON_TARIF",gxz:"ZV9cREF_CGRAL_DESP_TON_TARIF",gxold:"OV9cREF_CGRAL_DESP_TON_TARIF",gxvar:"AV9cREF_CGRAL_DESP_TON_TARIF",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV9cREF_CGRAL_DESP_TON_TARIF=gx.num.intval(a)},v2z:function(a){gx.O.ZV9cREF_CGRAL_DESP_TON_TARIF=
gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCREF_CGRAL_DESP_TON_TARIF",gx.O.AV9cREF_CGRAL_DESP_TON_TARIF,0)},c2v:function(){gx.O.AV9cREF_CGRAL_DESP_TON_TARIF=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCREF_CGRAL_DESP_TON_TARIF",gx.thousandSeparator)},nac:gx.falseFn};a[47]={fld:"",grid:0};a[48]={fld:"",grid:0};a[49]={fld:"REF_CGRAL_DESP_TARIFAFILTERCONTAINER",grid:0};a[50]={fld:"",grid:0};a[51]={fld:"",grid:0};a[52]={fld:"LBLREF_CGRAL_DESP_TARIFAFILTER",format:1,
grid:0};a[53]={fld:"",grid:0};a[54]={fld:"",grid:0};a[55]={fld:"",grid:0};a[56]={lvl:0,type:"decimal",len:10,dec:2,sign:false,pic:"ZZZZZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCREF_CGRAL_DESP_TARIFA",gxz:"ZV10cREF_CGRAL_DESP_TARIFA",gxold:"OV10cREF_CGRAL_DESP_TARIFA",gxvar:"AV10cREF_CGRAL_DESP_TARIFA",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10cREF_CGRAL_DESP_TARIFA=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.ZV10cREF_CGRAL_DESP_TARIFA=
gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("vCREF_CGRAL_DESP_TARIFA",gx.O.AV10cREF_CGRAL_DESP_TARIFA,2,gx.decimalPoint)},c2v:function(){gx.O.AV10cREF_CGRAL_DESP_TARIFA=this.val()},val:function(){return gx.fn.getDecimalValue("vCREF_CGRAL_DESP_TARIFA",gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};a[57]={fld:"",grid:0};a[58]={fld:"GRIDTABLE",grid:0};a[59]={fld:"",grid:0};a[60]={fld:"",grid:0};a[62]={fld:"",grid:0};a[63]={fld:"",grid:0};
a[65]={lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:64,gxgrid:this.Grid1Container,fnc:null,isvalid:null,fld:"vLINKSELECTION",gxz:"ZV5LinkSelection",gxold:"OV5LinkSelection",gxvar:"AV5LinkSelection",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.AV5LinkSelection=a},v2z:function(a){gx.O.ZV5LinkSelection=a},v2c:function(a){gx.fn.setGridMultimediaValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(64),gx.O.AV5LinkSelection,gx.O.AV15Linkselection_GXI)},
c2v:function(){gx.O.AV15Linkselection_GXI=this.val_GXI();gx.O.AV5LinkSelection=this.val()},val:function(a){return gx.fn.getGridControlValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(64))},val_GXI:function(a){return gx.fn.getGridControlValue("vLINKSELECTION_GXI",a||gx.fn.currentGridRowImpl(64))},gxvar_GXI:"AV15Linkselection_GXI",nac:gx.falseFn};a[66]={lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:1,isacc:0,grid:64,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"REF_CGRAL_DESP_ID",
gxz:"Z49REF_CGRAL_DESP_ID",gxold:"O49REF_CGRAL_DESP_ID",gxvar:"A49REF_CGRAL_DESP_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A49REF_CGRAL_DESP_ID=gx.num.intval(a)},v2z:function(a){gx.O.Z49REF_CGRAL_DESP_ID=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("REF_CGRAL_DESP_ID",a||gx.fn.currentGridRowImpl(64),gx.O.A49REF_CGRAL_DESP_ID,0)},c2v:function(){gx.O.A49REF_CGRAL_DESP_ID=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("REF_CGRAL_DESP_ID",
a||gx.fn.currentGridRowImpl(64),gx.thousandSeparator)},nac:gx.falseFn};a[67]={lvl:2,type:"svchar",len:50,dec:0,sign:false,ro:1,isacc:0,grid:64,gxgrid:this.Grid1Container,fnc:null,isvalid:null,fld:"REF_CGRAL_DESP_TIPO",gxz:"Z45REF_CGRAL_DESP_TIPO",gxold:"O45REF_CGRAL_DESP_TIPO",gxvar:"A45REF_CGRAL_DESP_TIPO",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",inputType:"text",v2v:function(a){gx.O.A45REF_CGRAL_DESP_TIPO=a},v2z:function(a){gx.O.Z45REF_CGRAL_DESP_TIPO=a},v2c:function(a){gx.fn.setGridComboBoxValue("REF_CGRAL_DESP_TIPO",
a||gx.fn.currentGridRowImpl(64),gx.O.A45REF_CGRAL_DESP_TIPO)},c2v:function(){gx.O.A45REF_CGRAL_DESP_TIPO=this.val()},val:function(a){return gx.fn.getGridControlValue("REF_CGRAL_DESP_TIPO",a||gx.fn.currentGridRowImpl(64))},nac:gx.falseFn};a[68]={lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:1,isacc:0,grid:64,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"REF_CGRAL_DESP_ID_TON_TARIF",gxz:"Z48REF_CGRAL_DESP_ID_TON_TARIF",gxold:"O48REF_CGRAL_DESP_ID_TON_TARIF",gxvar:"A48REF_CGRAL_DESP_ID_TON_TARIF",
ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A48REF_CGRAL_DESP_ID_TON_TARIF=gx.num.intval(a)},v2z:function(a){gx.O.Z48REF_CGRAL_DESP_ID_TON_TARIF=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("REF_CGRAL_DESP_ID_TON_TARIF",a||gx.fn.currentGridRowImpl(64),gx.O.A48REF_CGRAL_DESP_ID_TON_TARIF,0)},c2v:function(){gx.O.A48REF_CGRAL_DESP_ID_TON_TARIF=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("REF_CGRAL_DESP_ID_TON_TARIF",
a||gx.fn.currentGridRowImpl(64),gx.thousandSeparator)},nac:gx.falseFn};a[69]={fld:"",grid:0};a[70]={fld:"",grid:0};this.OV6cREF_CGRAL_DESP_ID=this.ZV6cREF_CGRAL_DESP_ID=this.AV6cREF_CGRAL_DESP_ID=0;this.OV7cREF_CGRAL_DESP_TIPO=this.ZV7cREF_CGRAL_DESP_TIPO=this.AV7cREF_CGRAL_DESP_TIPO="";this.OV10cREF_CGRAL_DESP_TARIFA=this.ZV10cREF_CGRAL_DESP_TARIFA=this.AV10cREF_CGRAL_DESP_TARIFA=this.OV9cREF_CGRAL_DESP_TON_TARIF=this.ZV9cREF_CGRAL_DESP_TON_TARIF=this.AV9cREF_CGRAL_DESP_TON_TARIF=this.OV8cREF_CGRAL_DESP_ID_TON_TARIF=
this.ZV8cREF_CGRAL_DESP_ID_TON_TARIF=this.AV8cREF_CGRAL_DESP_ID_TON_TARIF=0;this.OV5LinkSelection=this.ZV5LinkSelection="";this.O49REF_CGRAL_DESP_ID=this.Z49REF_CGRAL_DESP_ID=0;this.O45REF_CGRAL_DESP_TIPO=this.Z45REF_CGRAL_DESP_TIPO="";this.AV6cREF_CGRAL_DESP_ID=this.O48REF_CGRAL_DESP_ID_TON_TARIF=this.Z48REF_CGRAL_DESP_ID_TON_TARIF=0;this.AV7cREF_CGRAL_DESP_TIPO="";this.A46REF_CGRAL_DESP_TON_TARIF=this.A47REF_CGRAL_DESP_TARIFA=this.AV11pREF_CGRAL_DESP_ID=this.AV10cREF_CGRAL_DESP_TARIFA=this.AV9cREF_CGRAL_DESP_TON_TARIF=
this.AV8cREF_CGRAL_DESP_ID_TON_TARIF=0;this.AV5LinkSelection="";this.A49REF_CGRAL_DESP_ID=0;this.A45REF_CGRAL_DESP_TIPO="";this.A48REF_CGRAL_DESP_ID_TON_TARIF=0;this.Events={e191o2_client:["ENTER",true],e201o1_client:["CANCEL",true],e161o1_client:["'TOGGLE'",false],e111o1_client:["LBLREF_CGRAL_DESP_IDFILTER.CLICK",false],e121o1_client:["LBLREF_CGRAL_DESP_TIPOFILTER.CLICK",false],e131o1_client:["LBLREF_CGRAL_DESP_ID_TON_TARIFFILTER.CLICK",false],e141o1_client:["LBLREF_CGRAL_DESP_TON_TARIFFILTER.CLICK",
false],e151o1_client:["LBLREF_CGRAL_DESP_TARIFAFILTER.CLICK",false]};this.EvtParms.REFRESH=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cREF_CGRAL_DESP_ID",fld:"vCREF_CGRAL_DESP_ID"},{av:"AV7cREF_CGRAL_DESP_TIPO",fld:"vCREF_CGRAL_DESP_TIPO"},{av:"AV8cREF_CGRAL_DESP_ID_TON_TARIF",fld:"vCREF_CGRAL_DESP_ID_TON_TARIF"},{av:"AV9cREF_CGRAL_DESP_TON_TARIF",fld:"vCREF_CGRAL_DESP_TON_TARIF"},{av:"AV10cREF_CGRAL_DESP_TARIFA",fld:"vCREF_CGRAL_DESP_TARIFA"}],[]];this.EvtParms["'TOGGLE'"]=
[[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")',ctrl:"ADVANCEDCONTAINER",prop:"Class"},{ctrl:"BTNTOGGLE",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")',ctrl:"ADVANCEDCONTAINER",prop:"Class"},{ctrl:"BTNTOGGLE",prop:"Class"}]];this.EvtParms["LBLREF_CGRAL_DESP_IDFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_IDFILTERCONTAINER","Class")',ctrl:"REF_CGRAL_DESP_IDFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_IDFILTERCONTAINER","Class")',
ctrl:"REF_CGRAL_DESP_IDFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCREF_CGRAL_DESP_ID","Visible")',ctrl:"vCREF_CGRAL_DESP_ID",prop:"Visible"}]];this.EvtParms["LBLREF_CGRAL_DESP_TIPOFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_TIPOFILTERCONTAINER","Class")',ctrl:"REF_CGRAL_DESP_TIPOFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_TIPOFILTERCONTAINER","Class")',ctrl:"REF_CGRAL_DESP_TIPOFILTERCONTAINER",prop:"Class"},{ctrl:"vCREF_CGRAL_DESP_TIPO"}]];
this.EvtParms["LBLREF_CGRAL_DESP_ID_TON_TARIFFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_ID_TON_TARIFFILTERCONTAINER","Class")',ctrl:"REF_CGRAL_DESP_ID_TON_TARIFFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_ID_TON_TARIFFILTERCONTAINER","Class")',ctrl:"REF_CGRAL_DESP_ID_TON_TARIFFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCREF_CGRAL_DESP_ID_TON_TARIF","Visible")',ctrl:"vCREF_CGRAL_DESP_ID_TON_TARIF",prop:"Visible"}]];this.EvtParms["LBLREF_CGRAL_DESP_TON_TARIFFILTER.CLICK"]=
[[{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_TON_TARIFFILTERCONTAINER","Class")',ctrl:"REF_CGRAL_DESP_TON_TARIFFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_TON_TARIFFILTERCONTAINER","Class")',ctrl:"REF_CGRAL_DESP_TON_TARIFFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCREF_CGRAL_DESP_TON_TARIF","Visible")',ctrl:"vCREF_CGRAL_DESP_TON_TARIF",prop:"Visible"}]];this.EvtParms["LBLREF_CGRAL_DESP_TARIFAFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_TARIFAFILTERCONTAINER","Class")',
ctrl:"REF_CGRAL_DESP_TARIFAFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("REF_CGRAL_DESP_TARIFAFILTERCONTAINER","Class")',ctrl:"REF_CGRAL_DESP_TARIFAFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCREF_CGRAL_DESP_TARIFA","Visible")',ctrl:"vCREF_CGRAL_DESP_TARIFA",prop:"Visible"}]];this.EvtParms.ENTER=[[{av:"A49REF_CGRAL_DESP_ID",fld:"REF_CGRAL_DESP_ID"}],[{av:"AV11pREF_CGRAL_DESP_ID",fld:"vPREF_CGRAL_DESP_ID"}]];this.EvtParms.GRID1_FIRSTPAGE=[[{av:"GRID1_nFirstRecordOnPage"},
{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cREF_CGRAL_DESP_ID",fld:"vCREF_CGRAL_DESP_ID"},{av:"AV7cREF_CGRAL_DESP_TIPO",fld:"vCREF_CGRAL_DESP_TIPO"},{av:"AV8cREF_CGRAL_DESP_ID_TON_TARIF",fld:"vCREF_CGRAL_DESP_ID_TON_TARIF"},{av:"AV9cREF_CGRAL_DESP_TON_TARIF",fld:"vCREF_CGRAL_DESP_TON_TARIF"},{av:"AV10cREF_CGRAL_DESP_TARIFA",fld:"vCREF_CGRAL_DESP_TARIFA"}],[]];this.EvtParms.GRID1_PREVPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cREF_CGRAL_DESP_ID",fld:"vCREF_CGRAL_DESP_ID"},
{av:"AV7cREF_CGRAL_DESP_TIPO",fld:"vCREF_CGRAL_DESP_TIPO"},{av:"AV8cREF_CGRAL_DESP_ID_TON_TARIF",fld:"vCREF_CGRAL_DESP_ID_TON_TARIF"},{av:"AV9cREF_CGRAL_DESP_TON_TARIF",fld:"vCREF_CGRAL_DESP_TON_TARIF"},{av:"AV10cREF_CGRAL_DESP_TARIFA",fld:"vCREF_CGRAL_DESP_TARIFA"}],[]];this.EvtParms.GRID1_NEXTPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cREF_CGRAL_DESP_ID",fld:"vCREF_CGRAL_DESP_ID"},{av:"AV7cREF_CGRAL_DESP_TIPO",fld:"vCREF_CGRAL_DESP_TIPO"},{av:"AV8cREF_CGRAL_DESP_ID_TON_TARIF",
fld:"vCREF_CGRAL_DESP_ID_TON_TARIF"},{av:"AV9cREF_CGRAL_DESP_TON_TARIF",fld:"vCREF_CGRAL_DESP_TON_TARIF"},{av:"AV10cREF_CGRAL_DESP_TARIFA",fld:"vCREF_CGRAL_DESP_TARIFA"}],[]];this.EvtParms.GRID1_LASTPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cREF_CGRAL_DESP_ID",fld:"vCREF_CGRAL_DESP_ID"},{av:"AV7cREF_CGRAL_DESP_TIPO",fld:"vCREF_CGRAL_DESP_TIPO"},{av:"AV8cREF_CGRAL_DESP_ID_TON_TARIF",fld:"vCREF_CGRAL_DESP_ID_TON_TARIF"},{av:"AV9cREF_CGRAL_DESP_TON_TARIF",
fld:"vCREF_CGRAL_DESP_TON_TARIF"},{av:"AV10cREF_CGRAL_DESP_TARIFA",fld:"vCREF_CGRAL_DESP_TARIFA"}],[]];this.setVCMap("AV11pREF_CGRAL_DESP_ID","vPREF_CGRAL_DESP_ID",0,"int");b.addRefreshingVar(this.GXValidFnc[16]);b.addRefreshingVar(this.GXValidFnc[26]);b.addRefreshingVar(this.GXValidFnc[36]);b.addRefreshingVar(this.GXValidFnc[46]);b.addRefreshingVar(this.GXValidFnc[56]);this.InitStandaloneVars()});gx.createParentObj(gx0090);
