gx.evt.autoSkip=!1;
gx.define("gx00b0",!1,function(){this.ServerClass="gx00b0";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.hasEnterEvent=true;this.skipOnEnter=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){this.AV13pPASAJEROS_ID=gx.fn.getIntegerValue("vPPASAJEROS_ID",gx.thousandSeparator)};this.Validv_Cpasajeros_esclusa=function(){try{var a=gx.util.balloon.getNew("vCPASAJEROS_ESCLUSA");this.AnyError=0;if(!(this.AV7cPASAJEROS_ESCLUSA==
"Panamax"||this.AV7cPASAJEROS_ESCLUSA=="NeoPanamax"||""==this.AV7cPASAJEROS_ESCLUSA))try{a.setError(gx.text.format(gx.getMessage("GXSPC_OutOfRange"),gx.getMessage("cPASAJEROS_ESCLUSA"),"","","","","","","",""));this.AnyError=1}catch(b){}}catch(c){}try{return a==null?true:a.show()}catch(d){}return true};this.Validv_Cpasajeros_tipo_tarifa=function(){try{var a=gx.util.balloon.getNew("vCPASAJEROS_TIPO_TARIFA");this.AnyError=0;if(!(this.AV8cPASAJEROS_TIPO_TARIFA=="LITERA"||this.AV8cPASAJEROS_TIPO_TARIFA==
"CPSUAB"||""==this.AV8cPASAJEROS_TIPO_TARIFA))try{a.setError(gx.text.format(gx.getMessage("GXSPC_OutOfRange"),gx.getMessage("cPASAJEROS_TIPO_TARIFA"),"","","","","","","",""));this.AnyError=1}catch(b){}}catch(c){}try{return a==null?true:a.show()}catch(d){}return true};this.Validv_Cpasajeros_carga=function(){try{var a=gx.util.balloon.getNew("vCPASAJEROS_CARGA");this.AnyError=0;if(!(this.AV9cPASAJEROS_CARGA=="Laden"||this.AV9cPASAJEROS_CARGA=="Ballast"||""==this.AV9cPASAJEROS_CARGA))try{a.setError(gx.text.format(gx.getMessage("GXSPC_OutOfRange"),
gx.getMessage("cPASAJEROS_CARGA"),"","","","","","","",""));this.AnyError=1}catch(b){}}catch(c){}try{return a==null?true:a.show()}catch(d){}return true};this.e181p1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")=="AdvancedContainer"){gx.fn.setCtrlProperty("ADVANCEDCONTAINER","Class","AdvancedContainer AdvancedContainerVisible");gx.fn.setCtrlProperty("BTNTOGGLE","Class",gx.fn.getCtrlProperty("BTNTOGGLE","Class")+" BtnToggleActive")}else{gx.fn.setCtrlProperty("ADVANCEDCONTAINER",
"Class","AdvancedContainer");gx.fn.setCtrlProperty("BTNTOGGLE","Class","BtnToggle")}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")',ctrl:"ADVANCEDCONTAINER",prop:"Class"},{ctrl:"BTNTOGGLE",prop:"Class"}])};this.e111p1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("PASAJEROS_IDFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("PASAJEROS_IDFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCPASAJEROS_ID",
"Visible",true)}else{gx.fn.setCtrlProperty("PASAJEROS_IDFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCPASAJEROS_ID","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("PASAJEROS_IDFILTERCONTAINER","Class")',ctrl:"PASAJEROS_IDFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCPASAJEROS_ID","Visible")',ctrl:"vCPASAJEROS_ID",prop:"Visible"}])};this.e121p1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("PASAJEROS_ESCLUSAFILTERCONTAINER",
"Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("PASAJEROS_ESCLUSAFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCPASAJEROS_ESCLUSA","Visible",true)}else{gx.fn.setCtrlProperty("PASAJEROS_ESCLUSAFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCPASAJEROS_ESCLUSA","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("PASAJEROS_ESCLUSAFILTERCONTAINER","Class")',ctrl:"PASAJEROS_ESCLUSAFILTERCONTAINER",
prop:"Class"},{ctrl:"vCPASAJEROS_ESCLUSA"}])};this.e131p1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("PASAJEROS_TIPO_TARIFAFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("PASAJEROS_TIPO_TARIFAFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCPASAJEROS_TIPO_TARIFA","Visible",true)}else{gx.fn.setCtrlProperty("PASAJEROS_TIPO_TARIFAFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCPASAJEROS_TIPO_TARIFA",
"Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("PASAJEROS_TIPO_TARIFAFILTERCONTAINER","Class")',ctrl:"PASAJEROS_TIPO_TARIFAFILTERCONTAINER",prop:"Class"},{ctrl:"vCPASAJEROS_TIPO_TARIFA"}])};this.e141p1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("PASAJEROS_CARGAFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("PASAJEROS_CARGAFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCPASAJEROS_CARGA",
"Visible",true)}else{gx.fn.setCtrlProperty("PASAJEROS_CARGAFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCPASAJEROS_CARGA","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("PASAJEROS_CARGAFILTERCONTAINER","Class")',ctrl:"PASAJEROS_CARGAFILTERCONTAINER",prop:"Class"},{ctrl:"vCPASAJEROS_CARGA"}])};this.e151p1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("PASAJEROS_ID_TON_TARIFFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("PASAJEROS_ID_TON_TARIFFILTERCONTAINER",
"Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCPASAJEROS_ID_TON_TARIF","Visible",true)}else{gx.fn.setCtrlProperty("PASAJEROS_ID_TON_TARIFFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCPASAJEROS_ID_TON_TARIF","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("PASAJEROS_ID_TON_TARIFFILTERCONTAINER","Class")',ctrl:"PASAJEROS_ID_TON_TARIFFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCPASAJEROS_ID_TON_TARIF","Visible")',
ctrl:"vCPASAJEROS_ID_TON_TARIF",prop:"Visible"}])};this.e161p1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("PASAJEROS_TON_TARIFAFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("PASAJEROS_TON_TARIFAFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");gx.fn.setCtrlProperty("vCPASAJEROS_TON_TARIFA","Visible",true)}else{gx.fn.setCtrlProperty("PASAJEROS_TON_TARIFAFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCPASAJEROS_TON_TARIFA",
"Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("PASAJEROS_TON_TARIFAFILTERCONTAINER","Class")',ctrl:"PASAJEROS_TON_TARIFAFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCPASAJEROS_TON_TARIFA","Visible")',ctrl:"vCPASAJEROS_TON_TARIFA",prop:"Visible"}])};this.e171p1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("PASAJEROS_TARIFAFILTERCONTAINER","Class")=="AdvancedContainerItem"){gx.fn.setCtrlProperty("PASAJEROS_TARIFAFILTERCONTAINER","Class","AdvancedContainerItem AdvancedContainerItemExpanded");
gx.fn.setCtrlProperty("vCPASAJEROS_TARIFA","Visible",true)}else{gx.fn.setCtrlProperty("PASAJEROS_TARIFAFILTERCONTAINER","Class","AdvancedContainerItem");gx.fn.setCtrlProperty("vCPASAJEROS_TARIFA","Visible",false)}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("PASAJEROS_TARIFAFILTERCONTAINER","Class")',ctrl:"PASAJEROS_TARIFAFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCPASAJEROS_TARIFA","Visible")',ctrl:"vCPASAJEROS_TARIFA",prop:"Visible"}])};this.e211p2_client=function(a){this.executeServerEvent("ENTER",
true,a)};this.e221p1_client=function(){this.executeServerEvent("CANCEL",true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,82,83,85,86,87,88,89,90];this.GXLastCtrlId=90;var b=this.Grid1Container=new gx.grid.grid(this,2,"WbpLvl2",84,"Grid1","Grid1","Grid1Container",this.CmpContext,
this.IsMasterPage,"gx00b0",[],false,1,false,true,10,true,false,false,"",0,"px",gx.getMessage("GXM_newrow"),true,false,false,null,null,false,"",false,[1,1,1,1]);b.addBitmap("&Linkselection","vLINKSELECTION",85,0,"px",17,"px",null,"","","SelectionAttribute","WWActionColumn");b.addSingleLineEdit(63,86,"PASAJEROS_ID",gx.getMessage("ID"),"","PASAJEROS_ID","int",0,"px",4,4,"right",null,[],63,"PASAJEROS_ID",true,0,false,false,"Attribute",1,"WWColumn");b.addComboBox(58,87,"PASAJEROS_ESCLUSA",gx.getMessage("Esclusa"),
"PASAJEROS_ESCLUSA","svchar",null,0,true,false,0,"px","WWColumn");b.addComboBox(60,88,"PASAJEROS_TIPO_TARIFA",gx.getMessage("Tipo Tarifa"),"PASAJEROS_TIPO_TARIFA","svchar",null,0,true,false,0,"px","WWColumn OptionalColumn");this.setGrid(b);a[2]={fld:"",grid:0};a[3]={fld:"MAIN",grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};a[6]={fld:"ADVANCEDCONTAINER",grid:0};a[7]={fld:"",grid:0};a[8]={fld:"",grid:0};a[9]={fld:"PASAJEROS_IDFILTERCONTAINER",grid:0};a[10]={fld:"",grid:0};a[11]={fld:"",grid:0};a[12]=
{fld:"LBLPASAJEROS_IDFILTER",format:1,grid:0};a[13]={fld:"",grid:0};a[14]={fld:"",grid:0};a[15]={fld:"",grid:0};a[16]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCPASAJEROS_ID",gxz:"ZV6cPASAJEROS_ID",gxold:"OV6cPASAJEROS_ID",gxvar:"AV6cPASAJEROS_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV6cPASAJEROS_ID=gx.num.intval(a)},v2z:function(a){gx.O.ZV6cPASAJEROS_ID=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCPASAJEROS_ID",
gx.O.AV6cPASAJEROS_ID,0)},c2v:function(){gx.O.AV6cPASAJEROS_ID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCPASAJEROS_ID",gx.thousandSeparator)},nac:gx.falseFn};a[17]={fld:"",grid:0};a[18]={fld:"",grid:0};a[19]={fld:"PASAJEROS_ESCLUSAFILTERCONTAINER",grid:0};a[20]={fld:"",grid:0};a[21]={fld:"",grid:0};a[22]={fld:"LBLPASAJEROS_ESCLUSAFILTER",format:1,grid:0};a[23]={fld:"",grid:0};a[24]={fld:"",grid:0};a[25]={fld:"",grid:0};a[26]={lvl:0,type:"svchar",len:40,dec:0,sign:false,
ro:0,grid:0,gxgrid:null,fnc:this.Validv_Cpasajeros_esclusa,isvalid:null,fld:"vCPASAJEROS_ESCLUSA",gxz:"ZV7cPASAJEROS_ESCLUSA",gxold:"OV7cPASAJEROS_ESCLUSA",gxvar:"AV7cPASAJEROS_ESCLUSA",ucs:[],op:[26],ip:[26],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.AV7cPASAJEROS_ESCLUSA=a},v2z:function(a){gx.O.ZV7cPASAJEROS_ESCLUSA=a},v2c:function(){gx.fn.setComboBoxValue("vCPASAJEROS_ESCLUSA",gx.O.AV7cPASAJEROS_ESCLUSA)},c2v:function(){gx.O.AV7cPASAJEROS_ESCLUSA=this.val()},val:function(){return gx.fn.getControlValue("vCPASAJEROS_ESCLUSA")},
nac:gx.falseFn};a[27]={fld:"",grid:0};a[28]={fld:"",grid:0};a[29]={fld:"PASAJEROS_TIPO_TARIFAFILTERCONTAINER",grid:0};a[30]={fld:"",grid:0};a[31]={fld:"",grid:0};a[32]={fld:"LBLPASAJEROS_TIPO_TARIFAFILTER",format:1,grid:0};a[33]={fld:"",grid:0};a[34]={fld:"",grid:0};a[35]={fld:"",grid:0};a[36]={lvl:0,type:"svchar",len:10,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Validv_Cpasajeros_tipo_tarifa,isvalid:null,fld:"vCPASAJEROS_TIPO_TARIFA",gxz:"ZV8cPASAJEROS_TIPO_TARIFA",gxold:"OV8cPASAJEROS_TIPO_TARIFA",
gxvar:"AV8cPASAJEROS_TIPO_TARIFA",ucs:[],op:[36],ip:[36],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.AV8cPASAJEROS_TIPO_TARIFA=a},v2z:function(a){gx.O.ZV8cPASAJEROS_TIPO_TARIFA=a},v2c:function(){gx.fn.setComboBoxValue("vCPASAJEROS_TIPO_TARIFA",gx.O.AV8cPASAJEROS_TIPO_TARIFA)},c2v:function(){gx.O.AV8cPASAJEROS_TIPO_TARIFA=this.val()},val:function(){return gx.fn.getControlValue("vCPASAJEROS_TIPO_TARIFA")},nac:gx.falseFn};a[37]={fld:"",grid:0};a[38]={fld:"",grid:0};a[39]={fld:"PASAJEROS_CARGAFILTERCONTAINER",
grid:0};a[40]={fld:"",grid:0};a[41]={fld:"",grid:0};a[42]={fld:"LBLPASAJEROS_CARGAFILTER",format:1,grid:0};a[43]={fld:"",grid:0};a[44]={fld:"",grid:0};a[45]={fld:"",grid:0};a[46]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Validv_Cpasajeros_carga,isvalid:null,fld:"vCPASAJEROS_CARGA",gxz:"ZV9cPASAJEROS_CARGA",gxold:"OV9cPASAJEROS_CARGA",gxvar:"AV9cPASAJEROS_CARGA",ucs:[],op:[46],ip:[46],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.AV9cPASAJEROS_CARGA=a},v2z:function(a){gx.O.ZV9cPASAJEROS_CARGA=
a},v2c:function(){gx.fn.setComboBoxValue("vCPASAJEROS_CARGA",gx.O.AV9cPASAJEROS_CARGA)},c2v:function(){gx.O.AV9cPASAJEROS_CARGA=this.val()},val:function(){return gx.fn.getControlValue("vCPASAJEROS_CARGA")},nac:gx.falseFn};a[47]={fld:"",grid:0};a[48]={fld:"",grid:0};a[49]={fld:"PASAJEROS_ID_TON_TARIFFILTERCONTAINER",grid:0};a[50]={fld:"",grid:0};a[51]={fld:"",grid:0};a[52]={fld:"LBLPASAJEROS_ID_TON_TARIFFILTER",format:1,grid:0};a[53]={fld:"",grid:0};a[54]={fld:"",grid:0};a[55]={fld:"",grid:0};a[56]=
{lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCPASAJEROS_ID_TON_TARIF",gxz:"ZV10cPASAJEROS_ID_TON_TARIF",gxold:"OV10cPASAJEROS_ID_TON_TARIF",gxvar:"AV10cPASAJEROS_ID_TON_TARIF",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10cPASAJEROS_ID_TON_TARIF=gx.num.intval(a)},v2z:function(a){gx.O.ZV10cPASAJEROS_ID_TON_TARIF=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCPASAJEROS_ID_TON_TARIF",
gx.O.AV10cPASAJEROS_ID_TON_TARIF,0)},c2v:function(){gx.O.AV10cPASAJEROS_ID_TON_TARIF=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCPASAJEROS_ID_TON_TARIF",gx.thousandSeparator)},nac:gx.falseFn};a[57]={fld:"",grid:0};a[58]={fld:"",grid:0};a[59]={fld:"PASAJEROS_TON_TARIFAFILTERCONTAINER",grid:0};a[60]={fld:"",grid:0};a[61]={fld:"",grid:0};a[62]={fld:"LBLPASAJEROS_TON_TARIFAFILTER",format:1,grid:0};a[63]={fld:"",grid:0};a[64]={fld:"",grid:0};a[65]={fld:"",grid:0};a[66]={lvl:0,
type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCPASAJEROS_TON_TARIFA",gxz:"ZV11cPASAJEROS_TON_TARIFA",gxold:"OV11cPASAJEROS_TON_TARIFA",gxvar:"AV11cPASAJEROS_TON_TARIFA",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11cPASAJEROS_TON_TARIFA=gx.num.intval(a)},v2z:function(a){gx.O.ZV11cPASAJEROS_TON_TARIFA=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCPASAJEROS_TON_TARIFA",gx.O.AV11cPASAJEROS_TON_TARIFA,
0)},c2v:function(){gx.O.AV11cPASAJEROS_TON_TARIFA=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCPASAJEROS_TON_TARIFA",gx.thousandSeparator)},nac:gx.falseFn};a[67]={fld:"",grid:0};a[68]={fld:"",grid:0};a[69]={fld:"PASAJEROS_TARIFAFILTERCONTAINER",grid:0};a[70]={fld:"",grid:0};a[71]={fld:"",grid:0};a[72]={fld:"LBLPASAJEROS_TARIFAFILTER",format:1,grid:0};a[73]={fld:"",grid:0};a[74]={fld:"",grid:0};a[75]={fld:"",grid:0};a[76]={lvl:0,type:"decimal",len:10,dec:2,sign:false,pic:"ZZZZZZ9.99",
ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[this.Grid1Container],fld:"vCPASAJEROS_TARIFA",gxz:"ZV12cPASAJEROS_TARIFA",gxold:"OV12cPASAJEROS_TARIFA",gxvar:"AV12cPASAJEROS_TARIFA",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12cPASAJEROS_TARIFA=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.ZV12cPASAJEROS_TARIFA=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("vCPASAJEROS_TARIFA",gx.O.AV12cPASAJEROS_TARIFA,2,gx.decimalPoint)},
c2v:function(){gx.O.AV12cPASAJEROS_TARIFA=this.val()},val:function(){return gx.fn.getDecimalValue("vCPASAJEROS_TARIFA",gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};a[77]={fld:"",grid:0};a[78]={fld:"GRIDTABLE",grid:0};a[79]={fld:"",grid:0};a[80]={fld:"",grid:0};a[82]={fld:"",grid:0};a[83]={fld:"",grid:0};a[85]={lvl:2,type:"bits",len:1024,dec:0,sign:false,ro:1,isacc:0,grid:84,gxgrid:this.Grid1Container,fnc:null,isvalid:null,fld:"vLINKSELECTION",gxz:"ZV5LinkSelection",gxold:"OV5LinkSelection",
gxvar:"AV5LinkSelection",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.AV5LinkSelection=a},v2z:function(a){gx.O.ZV5LinkSelection=a},v2c:function(a){gx.fn.setGridMultimediaValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(84),gx.O.AV5LinkSelection,gx.O.AV17Linkselection_GXI)},c2v:function(){gx.O.AV17Linkselection_GXI=this.val_GXI();gx.O.AV5LinkSelection=this.val()},val:function(a){return gx.fn.getGridControlValue("vLINKSELECTION",a||gx.fn.currentGridRowImpl(84))},
val_GXI:function(a){return gx.fn.getGridControlValue("vLINKSELECTION_GXI",a||gx.fn.currentGridRowImpl(84))},gxvar_GXI:"AV17Linkselection_GXI",nac:gx.falseFn};a[86]={lvl:2,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:1,isacc:0,grid:84,gxgrid:this.Grid1Container,fnc:null,isvalid:null,rgrid:[],fld:"PASAJEROS_ID",gxz:"Z63PASAJEROS_ID",gxold:"O63PASAJEROS_ID",gxvar:"A63PASAJEROS_ID",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:"text",v2v:function(a){gx.O.A63PASAJEROS_ID=gx.num.intval(a)},
v2z:function(a){gx.O.Z63PASAJEROS_ID=gx.num.intval(a)},v2c:function(a){gx.fn.setGridControlValue("PASAJEROS_ID",a||gx.fn.currentGridRowImpl(84),gx.O.A63PASAJEROS_ID,0)},c2v:function(){gx.O.A63PASAJEROS_ID=gx.num.intval(this.val())},val:function(a){return gx.fn.getGridIntegerValue("PASAJEROS_ID",a||gx.fn.currentGridRowImpl(84),gx.thousandSeparator)},nac:gx.falseFn};a[87]={lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:84,gxgrid:this.Grid1Container,fnc:null,isvalid:null,fld:"PASAJEROS_ESCLUSA",
gxz:"Z58PASAJEROS_ESCLUSA",gxold:"O58PASAJEROS_ESCLUSA",gxvar:"A58PASAJEROS_ESCLUSA",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",inputType:"text",v2v:function(a){gx.O.A58PASAJEROS_ESCLUSA=a},v2z:function(a){gx.O.Z58PASAJEROS_ESCLUSA=a},v2c:function(a){gx.fn.setGridComboBoxValue("PASAJEROS_ESCLUSA",a||gx.fn.currentGridRowImpl(84),gx.O.A58PASAJEROS_ESCLUSA);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A58PASAJEROS_ESCLUSA=this.val()},val:function(a){return gx.fn.getGridControlValue("PASAJEROS_ESCLUSA",
a||gx.fn.currentGridRowImpl(84))},nac:gx.falseFn};a[88]={lvl:2,type:"svchar",len:10,dec:0,sign:false,ro:1,isacc:0,grid:84,gxgrid:this.Grid1Container,fnc:null,isvalid:null,fld:"PASAJEROS_TIPO_TARIFA",gxz:"Z60PASAJEROS_TIPO_TARIFA",gxold:"O60PASAJEROS_TIPO_TARIFA",gxvar:"A60PASAJEROS_TIPO_TARIFA",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",inputType:"text",v2v:function(a){gx.O.A60PASAJEROS_TIPO_TARIFA=a},v2z:function(a){gx.O.Z60PASAJEROS_TIPO_TARIFA=a},v2c:function(a){gx.fn.setGridComboBoxValue("PASAJEROS_TIPO_TARIFA",
a||gx.fn.currentGridRowImpl(84),gx.O.A60PASAJEROS_TIPO_TARIFA);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A60PASAJEROS_TIPO_TARIFA=this.val()},val:function(a){return gx.fn.getGridControlValue("PASAJEROS_TIPO_TARIFA",a||gx.fn.currentGridRowImpl(84))},nac:gx.falseFn};a[89]={fld:"",grid:0};a[90]={fld:"",grid:0};this.OV6cPASAJEROS_ID=this.ZV6cPASAJEROS_ID=this.AV6cPASAJEROS_ID=0;this.OV9cPASAJEROS_CARGA=this.ZV9cPASAJEROS_CARGA=this.AV9cPASAJEROS_CARGA=this.OV8cPASAJEROS_TIPO_TARIFA=
this.ZV8cPASAJEROS_TIPO_TARIFA=this.AV8cPASAJEROS_TIPO_TARIFA=this.OV7cPASAJEROS_ESCLUSA=this.ZV7cPASAJEROS_ESCLUSA=this.AV7cPASAJEROS_ESCLUSA="";this.OV12cPASAJEROS_TARIFA=this.ZV12cPASAJEROS_TARIFA=this.AV12cPASAJEROS_TARIFA=this.OV11cPASAJEROS_TON_TARIFA=this.ZV11cPASAJEROS_TON_TARIFA=this.AV11cPASAJEROS_TON_TARIFA=this.OV10cPASAJEROS_ID_TON_TARIF=this.ZV10cPASAJEROS_ID_TON_TARIF=this.AV10cPASAJEROS_ID_TON_TARIF=0;this.OV5LinkSelection=this.ZV5LinkSelection="";this.O63PASAJEROS_ID=this.Z63PASAJEROS_ID=
0;this.O60PASAJEROS_TIPO_TARIFA=this.Z60PASAJEROS_TIPO_TARIFA=this.O58PASAJEROS_ESCLUSA=this.Z58PASAJEROS_ESCLUSA="";this.AV6cPASAJEROS_ID=0;this.AV9cPASAJEROS_CARGA=this.AV8cPASAJEROS_TIPO_TARIFA=this.AV7cPASAJEROS_ESCLUSA="";this.A65PASAJEROS_ID_TON_TARIF=this.A61PASAJEROS_TON_TARIFA=this.A62PASAJEROS_TARIFA=this.AV13pPASAJEROS_ID=this.AV12cPASAJEROS_TARIFA=this.AV11cPASAJEROS_TON_TARIFA=this.AV10cPASAJEROS_ID_TON_TARIF=0;this.AV5LinkSelection=this.A59PASAJEROS_CARGA="";this.A63PASAJEROS_ID=0;this.A60PASAJEROS_TIPO_TARIFA=
this.A58PASAJEROS_ESCLUSA="";this.Events={e211p2_client:["ENTER",true],e221p1_client:["CANCEL",true],e181p1_client:["'TOGGLE'",false],e111p1_client:["LBLPASAJEROS_IDFILTER.CLICK",false],e121p1_client:["LBLPASAJEROS_ESCLUSAFILTER.CLICK",false],e131p1_client:["LBLPASAJEROS_TIPO_TARIFAFILTER.CLICK",false],e141p1_client:["LBLPASAJEROS_CARGAFILTER.CLICK",false],e151p1_client:["LBLPASAJEROS_ID_TON_TARIFFILTER.CLICK",false],e161p1_client:["LBLPASAJEROS_TON_TARIFAFILTER.CLICK",false],e171p1_client:["LBLPASAJEROS_TARIFAFILTER.CLICK",
false]};this.EvtParms.REFRESH=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cPASAJEROS_ID",fld:"vCPASAJEROS_ID"},{av:"AV7cPASAJEROS_ESCLUSA",fld:"vCPASAJEROS_ESCLUSA"},{av:"AV8cPASAJEROS_TIPO_TARIFA",fld:"vCPASAJEROS_TIPO_TARIFA"},{av:"AV9cPASAJEROS_CARGA",fld:"vCPASAJEROS_CARGA"},{av:"AV10cPASAJEROS_ID_TON_TARIF",fld:"vCPASAJEROS_ID_TON_TARIF"},{av:"AV11cPASAJEROS_TON_TARIFA",fld:"vCPASAJEROS_TON_TARIFA"},{av:"AV12cPASAJEROS_TARIFA",fld:"vCPASAJEROS_TARIFA"}],[]];
this.EvtParms["'TOGGLE'"]=[[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")',ctrl:"ADVANCEDCONTAINER",prop:"Class"},{ctrl:"BTNTOGGLE",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER","Class")',ctrl:"ADVANCEDCONTAINER",prop:"Class"},{ctrl:"BTNTOGGLE",prop:"Class"}]];this.EvtParms["LBLPASAJEROS_IDFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("PASAJEROS_IDFILTERCONTAINER","Class")',ctrl:"PASAJEROS_IDFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("PASAJEROS_IDFILTERCONTAINER","Class")',
ctrl:"PASAJEROS_IDFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCPASAJEROS_ID","Visible")',ctrl:"vCPASAJEROS_ID",prop:"Visible"}]];this.EvtParms["LBLPASAJEROS_ESCLUSAFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("PASAJEROS_ESCLUSAFILTERCONTAINER","Class")',ctrl:"PASAJEROS_ESCLUSAFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("PASAJEROS_ESCLUSAFILTERCONTAINER","Class")',ctrl:"PASAJEROS_ESCLUSAFILTERCONTAINER",prop:"Class"},{ctrl:"vCPASAJEROS_ESCLUSA"}]];this.EvtParms["LBLPASAJEROS_TIPO_TARIFAFILTER.CLICK"]=
[[{av:'gx.fn.getCtrlProperty("PASAJEROS_TIPO_TARIFAFILTERCONTAINER","Class")',ctrl:"PASAJEROS_TIPO_TARIFAFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("PASAJEROS_TIPO_TARIFAFILTERCONTAINER","Class")',ctrl:"PASAJEROS_TIPO_TARIFAFILTERCONTAINER",prop:"Class"},{ctrl:"vCPASAJEROS_TIPO_TARIFA"}]];this.EvtParms["LBLPASAJEROS_CARGAFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("PASAJEROS_CARGAFILTERCONTAINER","Class")',ctrl:"PASAJEROS_CARGAFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("PASAJEROS_CARGAFILTERCONTAINER","Class")',
ctrl:"PASAJEROS_CARGAFILTERCONTAINER",prop:"Class"},{ctrl:"vCPASAJEROS_CARGA"}]];this.EvtParms["LBLPASAJEROS_ID_TON_TARIFFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("PASAJEROS_ID_TON_TARIFFILTERCONTAINER","Class")',ctrl:"PASAJEROS_ID_TON_TARIFFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("PASAJEROS_ID_TON_TARIFFILTERCONTAINER","Class")',ctrl:"PASAJEROS_ID_TON_TARIFFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCPASAJEROS_ID_TON_TARIF","Visible")',ctrl:"vCPASAJEROS_ID_TON_TARIF",
prop:"Visible"}]];this.EvtParms["LBLPASAJEROS_TON_TARIFAFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("PASAJEROS_TON_TARIFAFILTERCONTAINER","Class")',ctrl:"PASAJEROS_TON_TARIFAFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("PASAJEROS_TON_TARIFAFILTERCONTAINER","Class")',ctrl:"PASAJEROS_TON_TARIFAFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCPASAJEROS_TON_TARIFA","Visible")',ctrl:"vCPASAJEROS_TON_TARIFA",prop:"Visible"}]];this.EvtParms["LBLPASAJEROS_TARIFAFILTER.CLICK"]=[[{av:'gx.fn.getCtrlProperty("PASAJEROS_TARIFAFILTERCONTAINER","Class")',
ctrl:"PASAJEROS_TARIFAFILTERCONTAINER",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("PASAJEROS_TARIFAFILTERCONTAINER","Class")',ctrl:"PASAJEROS_TARIFAFILTERCONTAINER",prop:"Class"},{av:'gx.fn.getCtrlProperty("vCPASAJEROS_TARIFA","Visible")',ctrl:"vCPASAJEROS_TARIFA",prop:"Visible"}]];this.EvtParms.ENTER=[[{av:"A63PASAJEROS_ID",fld:"PASAJEROS_ID"}],[{av:"AV13pPASAJEROS_ID",fld:"vPPASAJEROS_ID"}]];this.EvtParms.GRID1_FIRSTPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cPASAJEROS_ID",
fld:"vCPASAJEROS_ID"},{av:"AV7cPASAJEROS_ESCLUSA",fld:"vCPASAJEROS_ESCLUSA"},{av:"AV8cPASAJEROS_TIPO_TARIFA",fld:"vCPASAJEROS_TIPO_TARIFA"},{av:"AV9cPASAJEROS_CARGA",fld:"vCPASAJEROS_CARGA"},{av:"AV10cPASAJEROS_ID_TON_TARIF",fld:"vCPASAJEROS_ID_TON_TARIF"},{av:"AV11cPASAJEROS_TON_TARIFA",fld:"vCPASAJEROS_TON_TARIFA"},{av:"AV12cPASAJEROS_TARIFA",fld:"vCPASAJEROS_TARIFA"}],[]];this.EvtParms.GRID1_PREVPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cPASAJEROS_ID",
fld:"vCPASAJEROS_ID"},{av:"AV7cPASAJEROS_ESCLUSA",fld:"vCPASAJEROS_ESCLUSA"},{av:"AV8cPASAJEROS_TIPO_TARIFA",fld:"vCPASAJEROS_TIPO_TARIFA"},{av:"AV9cPASAJEROS_CARGA",fld:"vCPASAJEROS_CARGA"},{av:"AV10cPASAJEROS_ID_TON_TARIF",fld:"vCPASAJEROS_ID_TON_TARIF"},{av:"AV11cPASAJEROS_TON_TARIFA",fld:"vCPASAJEROS_TON_TARIFA"},{av:"AV12cPASAJEROS_TARIFA",fld:"vCPASAJEROS_TARIFA"}],[]];this.EvtParms.GRID1_NEXTPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cPASAJEROS_ID",
fld:"vCPASAJEROS_ID"},{av:"AV7cPASAJEROS_ESCLUSA",fld:"vCPASAJEROS_ESCLUSA"},{av:"AV8cPASAJEROS_TIPO_TARIFA",fld:"vCPASAJEROS_TIPO_TARIFA"},{av:"AV9cPASAJEROS_CARGA",fld:"vCPASAJEROS_CARGA"},{av:"AV10cPASAJEROS_ID_TON_TARIF",fld:"vCPASAJEROS_ID_TON_TARIF"},{av:"AV11cPASAJEROS_TON_TARIFA",fld:"vCPASAJEROS_TON_TARIFA"},{av:"AV12cPASAJEROS_TARIFA",fld:"vCPASAJEROS_TARIFA"}],[]];this.EvtParms.GRID1_LASTPAGE=[[{av:"GRID1_nFirstRecordOnPage"},{av:"GRID1_nEOF"},{av:"subGrid1_Rows"},{av:"AV6cPASAJEROS_ID",
fld:"vCPASAJEROS_ID"},{av:"AV7cPASAJEROS_ESCLUSA",fld:"vCPASAJEROS_ESCLUSA"},{av:"AV8cPASAJEROS_TIPO_TARIFA",fld:"vCPASAJEROS_TIPO_TARIFA"},{av:"AV9cPASAJEROS_CARGA",fld:"vCPASAJEROS_CARGA"},{av:"AV10cPASAJEROS_ID_TON_TARIF",fld:"vCPASAJEROS_ID_TON_TARIF"},{av:"AV11cPASAJEROS_TON_TARIFA",fld:"vCPASAJEROS_TON_TARIFA"},{av:"AV12cPASAJEROS_TARIFA",fld:"vCPASAJEROS_TARIFA"}],[]];this.setVCMap("AV13pPASAJEROS_ID","vPPASAJEROS_ID",0,"int");b.addRefreshingVar(this.GXValidFnc[16]);b.addRefreshingVar(this.GXValidFnc[26]);
b.addRefreshingVar(this.GXValidFnc[36]);b.addRefreshingVar(this.GXValidFnc[46]);b.addRefreshingVar(this.GXValidFnc[56]);b.addRefreshingVar(this.GXValidFnc[66]);b.addRefreshingVar(this.GXValidFnc[76]);this.InitStandaloneVars()});gx.createParentObj(gx00b0);
