gx.evt.autoSkip=!1;
gx.define("mp",!1,function(){this.ServerClass="mp";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.IsMasterPage=true;this.skipOnEnter=this.hasEnterEvent=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){this.AV14Pgmname=gx.fn.getControlValue("vPGMNAME_MPAGE")};this.Validv_Segmento=function(){try{var a=gx.util.balloon.getNew("vSEGMENTO_MPAGE");this.AnyError=0;if(!(this.AV5Segmento=="Portacontenedores"||this.AV5Segmento==
"Graneles Secos"||this.AV5Segmento=="Tanqueros"||this.AV5Segmento=="Quimiqueros"||this.AV5Segmento=="Gaseros LPG"||this.AV5Segmento=="Gaseros LNG"||this.AV5Segmento=="Porta Veh\u00edculos y Ro-Ro"||this.AV5Segmento=="Pasajeros"||this.AV5Segmento=="Refrigerados"||this.AV5Segmento=="Carga General"||this.AV5Segmento=="Otros"||""==this.AV5Segmento))try{a.setError(gx.text.format(gx.getMessage("GXSPC_OutOfRange"),gx.getMessage("Segmento"),"","","","","","","",""));this.AnyError=1}catch(b){}}catch(c){}try{return a==
null?true:a.show()}catch(d){}return true};this.e121x1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")=="AdvancedContainer"){gx.fn.setCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class","AdvancedContainer AdvancedContainerVisible");gx.fn.setCtrlProperty("BTNTOGGLE_MPAGE","Class",gx.fn.getCtrlProperty("BTNTOGGLE_MPAGE","Class")+" BtnToggleActive")}else{gx.fn.setCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class","AdvancedContainer");gx.fn.setCtrlProperty("BTNTOGGLE_MPAGE",
"Class","BtnToggle")}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}])};this.e191x2_client=function(){this.clearMessages();gx.fn.setCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class","AdvancedContainer");gx.fn.setCtrlProperty("BTNTOGGLE_MPAGE","Class","BtnToggle");this.refreshOutputs([{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},
{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}])};this.e201x1_client=function(){this.clearMessages();gx.fn.setCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class","AdvancedContainer");gx.fn.setCtrlProperty("BTNTOGGLE_MPAGE","Class","BtnToggle");this.refreshOutputs([{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}])};this.e111x1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE",
"Class")=="AdvancedContainer"){gx.fn.setCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class","AdvancedContainer AdvancedContainerVisible");gx.fn.setCtrlProperty("BTNTOGGLE_MPAGE","Class",gx.fn.getCtrlProperty("BTNTOGGLE_MPAGE","Class")+" BtnToggleActive")}else{gx.fn.setCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class","AdvancedContainer");gx.fn.setCtrlProperty("BTNTOGGLE_MPAGE","Class","BtnToggle")}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",
prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}])};this.e151x2_client=function(){this.executeServerEvent("VSEGMENTO_MPAGE.CLICK_MPAGE",true)};this.e161x2_client=function(){this.executeServerEvent("ENG._MPAGE",false)};this.e171x2_client=function(){this.executeServerEvent("SET ESPA\u00f1OL_MPAGE",false)};this.e211x2_client=function(){this.executeServerEvent("ENTER_MPAGE",true)};this.e221x2_client=function(){this.executeServerEvent("CANCEL_MPAGE",true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,
3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,45,46,47,48,49,51,52,54,55,56,57,58,59,60,61,62,63];this.GXLastCtrlId=63;a[2]={fld:"",grid:0};a[3]={fld:"MAINTABLE",grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};a[6]={fld:"HEADER",grid:0};a[7]={fld:"",grid:0};a[8]={fld:"",grid:0};a[9]={fld:"",grid:0};a[10]={fld:"IMAGE1",grid:0};a[11]={fld:"",grid:0};a[12]={fld:"",grid:0};a[13]={fld:"RECENT",grid:0};a[14]={fld:"",grid:0};a[15]={fld:"",
grid:0};a[16]={fld:"TEXTBLOCK1",format:0,grid:0};a[17]={fld:"",grid:0};a[18]={fld:"",grid:0};a[21]={fld:"",grid:0};a[22]={fld:"",grid:0};a[23]={fld:"MAINTABLEX",grid:0};a[24]={fld:"",grid:0};a[25]={fld:"",grid:0};a[26]={fld:"ADVANCEDCONTAINER",grid:0};a[27]={fld:"",grid:0};a[28]={fld:"",grid:0};a[29]={fld:"",grid:0};a[30]={fld:"SOLICITUDFECHAFILTERCONTAINER",grid:0};a[31]={fld:"",grid:0};a[32]={fld:"",grid:0};a[33]={fld:"TEXTBLOCK3",format:0,grid:0};a[34]={fld:"",grid:0};a[35]={fld:"",grid:0};a[36]=
{fld:"GROUP1",grid:0};a[37]={fld:"GROUP1TABLE",grid:0};a[38]={fld:"",grid:0};a[39]={fld:"",grid:0};a[40]={fld:"",grid:0};a[41]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Validv_Segmento,isvalid:"e201x1_client",fld:"vSEGMENTO_MPAGE",gxz:"ZV5Segmento",gxold:"OV5Segmento",gxvar:"AV5Segmento",ucs:[],op:[41],ip:[41],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.AV5Segmento=a},v2z:function(a){gx.O.ZV5Segmento=a},v2c:function(){gx.fn.setComboBoxValue("vSEGMENTO_MPAGE",
gx.O.AV5Segmento);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV5Segmento=this.val()},val:function(){return gx.fn.getControlValue("vSEGMENTO_MPAGE")},nac:gx.falseFn};this.declareDomainHdlr(41,function(){});a[42]={fld:"",grid:0};a[43]={fld:"",grid:0};a[45]={fld:"",grid:0};a[46]={fld:"GRIDTABLE",grid:0};a[47]={fld:"",grid:0};a[48]={fld:"",grid:0};a[49]={fld:"",grid:0};a[51]={fld:"",grid:0};a[52]={fld:"",grid:0};a[54]={fld:"",grid:0};a[55]={fld:"",grid:0};a[56]={fld:"FOOTER",
grid:0};a[57]={fld:"",grid:0};a[58]={fld:"",grid:0};a[59]={fld:"TEXTBLOCK2",format:0,grid:0};a[60]={fld:"",grid:0};a[61]={fld:"",grid:0};a[62]={fld:"",grid:0};a[63]={fld:"",grid:0};this.AV14Pgmname=this.AV5Segmento=this.OV5Segmento=this.ZV5Segmento=this.AV5Segmento="";this.Events={e151x2_client:["VSEGMENTO_MPAGE.CLICK_MPAGE",true],e161x2_client:["ENG._MPAGE",true],e171x2_client:["SET ESPA\u00f1OL_MPAGE",true],e211x2_client:["ENTER_MPAGE",true],e221x2_client:["CANCEL_MPAGE",true],e121x1_client:["TOGGLE_MPAGE",
false],e191x2_client:["BUSCAR_MPAGE",false],e201x1_client:["VSEGMENTO_MPAGE.ISVALID_MPAGE",false],e111x1_client:["CANCELAR_MPAGE",false]};this.EvtParms.REFRESH_MPAGE=[[{av:"AV14Pgmname",fld:"vPGMNAME_MPAGE"},{av:"AV5Segmento",fld:"vSEGMENTO_MPAGE"}],[{ctrl:"COMPONENT1_MPAGE"},{av:"AV8GridState",fld:"vGRIDSTATE_MPAGE"},{av:"AV11GridStateFilterValue",fld:"vGRIDSTATEFILTERVALUE_MPAGE"}]];this.EvtParms.TOGGLE_MPAGE=[[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",
prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}]];this.EvtParms.BUSCAR_MPAGE=[[],[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}]];this.EvtParms["VSEGMENTO_MPAGE.ISVALID_MPAGE"]=[[],[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",
prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}]];this.EvtParms["VSEGMENTO_MPAGE.CLICK_MPAGE"]=[[{av:"AV5Segmento",fld:"vSEGMENTO_MPAGE"},{av:"AV14Pgmname",fld:"vPGMNAME_MPAGE"}],[{av:"AV8GridState",fld:"vGRIDSTATE_MPAGE"},{av:"AV11GridStateFilterValue",fld:"vGRIDSTATEFILTERVALUE_MPAGE"}]];this.EvtParms["ENG._MPAGE"]=[[],[{av:"Gx_err",fld:"vERR_MPAGE"}]];this.EvtParms["SET ESPA\u00f1OL_MPAGE"]=[[],[{av:"Gx_err",fld:"vERR_MPAGE"}]];this.EvtParms.CANCELAR_MPAGE=[[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',
ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}]];this.setVCMap("AV14Pgmname","vPGMNAME_MPAGE",0,"char");this.InitStandaloneVars();this.setComponent({id:"COMPONENT1",GXClass:null,Prefix:"MPW0064",lvl:1})});gx.setMasterPage(new mp);
