gx.evt.autoSkip=!1;
gx.define("pasajeros",!1,function(){this.ServerClass="pasajeros";this.PackageName="GeneXus.Programs";this.setObjectType("trn");this.hasEnterEvent=true;this.skipOnEnter=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=true;this.SetStandaloneVars=function(){this.Gx_mode=gx.fn.getControlValue("vMODE")};this.Valid_Pasajeros_id=function(){gx.ajax.validSrvEvt("dyncall","Valid_Pasajeros_id",["gx.O.A63PASAJEROS_ID","gx.O.A58PASAJEROS_ESCLUSA","gx.O.A60PASAJEROS_TIPO_TARIFA","gx.O.A59PASAJEROS_CARGA",
"gx.O.A65PASAJEROS_ID_TON_TARIF","gx.O.A61PASAJEROS_TON_TARIFA","gx.num.urlDecimal(gx.O.A62PASAJEROS_TARIFA,gx.thousandSeparator,gx.decimalPoint)","gx.O.A64PASAJEROS_COMENTARIO"],["A58PASAJEROS_ESCLUSA","A60PASAJEROS_TIPO_TARIFA","A59PASAJEROS_CARGA","A65PASAJEROS_ID_TON_TARIF","A61PASAJEROS_TON_TARIFA","A62PASAJEROS_TARIFA","A64PASAJEROS_COMENTARIO","Gx_mode","Z63PASAJEROS_ID","Z58PASAJEROS_ESCLUSA","Z60PASAJEROS_TIPO_TARIFA","Z59PASAJEROS_CARGA","Z65PASAJEROS_ID_TON_TARIF","Z61PASAJEROS_TON_TARIFA",
"Z62PASAJEROS_TARIFA","Z64PASAJEROS_COMENTARIO",["BTN_DELETE","Enabled"],["BTN_ENTER","Enabled"]]);return true};this.Valid_Pasajeros_esclusa=function(){try{var a=gx.util.balloon.getNew("PASAJEROS_ESCLUSA");this.AnyError=0;if(!(this.A58PASAJEROS_ESCLUSA=="Panamax"||this.A58PASAJEROS_ESCLUSA=="Neo Panamax"))try{a.setError(gx.text.format(gx.getMessage("GXSPC_OutOfRange"),gx.getMessage("Identificador unico de la transaccion"),"","","","","","","",""));this.AnyError=1}catch(b){}}catch(c){}try{return a==
null?true:a.show()}catch(d){}return true};this.Valid_Pasajeros_tipo_tarifa=function(){try{var a=gx.util.balloon.getNew("PASAJEROS_TIPO_TARIFA");this.AnyError=0;if(!(this.A60PASAJEROS_TIPO_TARIFA=="LITERA"||this.A60PASAJEROS_TIPO_TARIFA=="CPSUAB"))try{a.setError(gx.text.format(gx.getMessage("GXSPC_OutOfRange"),gx.getMessage("Tipo de tarifa del peaje: Litera, CP/SUAB"),"","","","","","","",""));this.AnyError=1}catch(b){}}catch(c){}try{return a==null?true:a.show()}catch(d){}return true};this.Valid_Pasajeros_carga=
function(){try{var a=gx.util.balloon.getNew("PASAJEROS_CARGA");this.AnyError=0;if(!(this.A59PASAJEROS_CARGA=="Laden"||this.A59PASAJEROS_CARGA=="Ballast"))try{a.setError(gx.text.format(gx.getMessage("GXSPC_OutOfRange"),gx.getMessage("Estado en el que viaja el buque: Cargado, En Lastre"),"","","","","","","",""));this.AnyError=1}catch(b){}}catch(c){}try{return a==null?true:a.show()}catch(d){}return true};this.e110911_client=function(){this.executeServerEvent("ENTER",true)};this.e120911_client=function(){this.executeServerEvent("CANCEL",
true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,16,17,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69];this.GXLastCtrlId=69;a[2]={fld:"",grid:0};a[3]={fld:"TABLEMAIN",grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};a[6]={fld:"TITLE",format:0,grid:0};a[7]={fld:"",grid:0};a[8]={fld:"",grid:0};a[9]={fld:"",grid:0};a[10]={fld:"",grid:0};a[16]={fld:"",grid:0};a[17]={fld:"",grid:0};
a[19]={fld:"",grid:0};a[20]={fld:"",grid:0};a[21]={fld:"PASAJEROS_ID_CONTAINER",grid:0};a[22]={fld:"",format:0,grid:0};a[23]={fld:"",grid:0};a[24]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Valid_Pasajeros_id,isvalid:null,rgrid:[],fld:"PASAJEROS_ID",gxz:"Z63PASAJEROS_ID",gxold:"O63PASAJEROS_ID",gxvar:"A63PASAJEROS_ID",ucs:[],op:[66,60,54,48,42,36,30],ip:[66,60,54,48,42,36,30,24],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A63PASAJEROS_ID=gx.num.intval(a)},
v2z:function(a){gx.O.Z63PASAJEROS_ID=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("PASAJEROS_ID",gx.O.A63PASAJEROS_ID,0)},c2v:function(){gx.O.A63PASAJEROS_ID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("PASAJEROS_ID",gx.thousandSeparator)},nac:gx.falseFn};a[25]={fld:"",grid:0};a[26]={fld:"",grid:0};a[27]={fld:"PASAJEROS_ESCLUSA_CONTAINER",grid:0};a[28]={fld:"",format:0,grid:0};a[29]={fld:"",grid:0};a[30]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,
gxgrid:null,fnc:this.Valid_Pasajeros_esclusa,isvalid:null,fld:"PASAJEROS_ESCLUSA",gxz:"Z58PASAJEROS_ESCLUSA",gxold:"O58PASAJEROS_ESCLUSA",gxvar:"A58PASAJEROS_ESCLUSA",ucs:[],op:[30],ip:[30],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.A58PASAJEROS_ESCLUSA=a},v2z:function(a){gx.O.Z58PASAJEROS_ESCLUSA=a},v2c:function(){gx.fn.setComboBoxValue("PASAJEROS_ESCLUSA",gx.O.A58PASAJEROS_ESCLUSA);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A58PASAJEROS_ESCLUSA=this.val()},
val:function(){return gx.fn.getControlValue("PASAJEROS_ESCLUSA")},nac:gx.falseFn};this.declareDomainHdlr(30,function(){});a[31]={fld:"",grid:0};a[32]={fld:"",grid:0};a[33]={fld:"PASAJEROS_TIPO_TARIFA_CONTAINER",grid:0};a[34]={fld:"",format:0,grid:0};a[35]={fld:"",grid:0};a[36]={lvl:0,type:"svchar",len:10,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Valid_Pasajeros_tipo_tarifa,isvalid:null,fld:"PASAJEROS_TIPO_TARIFA",gxz:"Z60PASAJEROS_TIPO_TARIFA",gxold:"O60PASAJEROS_TIPO_TARIFA",gxvar:"A60PASAJEROS_TIPO_TARIFA",
ucs:[],op:[36],ip:[36],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.A60PASAJEROS_TIPO_TARIFA=a},v2z:function(a){gx.O.Z60PASAJEROS_TIPO_TARIFA=a},v2c:function(){gx.fn.setComboBoxValue("PASAJEROS_TIPO_TARIFA",gx.O.A60PASAJEROS_TIPO_TARIFA);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A60PASAJEROS_TIPO_TARIFA=this.val()},val:function(){return gx.fn.getControlValue("PASAJEROS_TIPO_TARIFA")},nac:gx.falseFn};this.declareDomainHdlr(36,function(){});a[37]={fld:"",grid:0};
a[38]={fld:"",grid:0};a[39]={fld:"PASAJEROS_CARGA_CONTAINER",grid:0};a[40]={fld:"",format:0,grid:0};a[41]={fld:"",grid:0};a[42]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Valid_Pasajeros_carga,isvalid:null,fld:"PASAJEROS_CARGA",gxz:"Z59PASAJEROS_CARGA",gxold:"O59PASAJEROS_CARGA",gxvar:"A59PASAJEROS_CARGA",ucs:[],op:[42],ip:[42],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.A59PASAJEROS_CARGA=a},v2z:function(a){gx.O.Z59PASAJEROS_CARGA=a},v2c:function(){gx.fn.setComboBoxValue("PASAJEROS_CARGA",
gx.O.A59PASAJEROS_CARGA);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.A59PASAJEROS_CARGA=this.val()},val:function(){return gx.fn.getControlValue("PASAJEROS_CARGA")},nac:gx.falseFn};this.declareDomainHdlr(42,function(){});a[43]={fld:"",grid:0};a[44]={fld:"",grid:0};a[45]={fld:"PASAJEROS_ID_TON_TARIF_CONTAINER",grid:0};a[46]={fld:"",format:0,grid:0};a[47]={fld:"",grid:0};a[48]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,
rgrid:[],fld:"PASAJEROS_ID_TON_TARIF",gxz:"Z65PASAJEROS_ID_TON_TARIF",gxold:"O65PASAJEROS_ID_TON_TARIF",gxvar:"A65PASAJEROS_ID_TON_TARIF",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A65PASAJEROS_ID_TON_TARIF=gx.num.intval(a)},v2z:function(a){gx.O.Z65PASAJEROS_ID_TON_TARIF=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("PASAJEROS_ID_TON_TARIF",gx.O.A65PASAJEROS_ID_TON_TARIF,0)},c2v:function(){gx.O.A65PASAJEROS_ID_TON_TARIF=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("PASAJEROS_ID_TON_TARIF",
gx.thousandSeparator)},nac:gx.falseFn};a[49]={fld:"",grid:0};a[50]={fld:"",grid:0};a[51]={fld:"PASAJEROS_TON_TARIFA_CONTAINER",grid:0};a[52]={fld:"",format:0,grid:0};a[53]={fld:"",grid:0};a[54]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"PASAJEROS_TON_TARIFA",gxz:"Z61PASAJEROS_TON_TARIFA",gxold:"O61PASAJEROS_TON_TARIFA",gxvar:"A61PASAJEROS_TON_TARIFA",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A61PASAJEROS_TON_TARIFA=
gx.num.intval(a)},v2z:function(a){gx.O.Z61PASAJEROS_TON_TARIFA=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("PASAJEROS_TON_TARIFA",gx.O.A61PASAJEROS_TON_TARIFA,0)},c2v:function(){gx.O.A61PASAJEROS_TON_TARIFA=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("PASAJEROS_TON_TARIFA",gx.thousandSeparator)},nac:gx.falseFn};a[55]={fld:"",grid:0};a[56]={fld:"",grid:0};a[57]={fld:"PASAJEROS_TARIFA_CONTAINER",grid:0};a[58]={fld:"",format:0,grid:0};a[59]={fld:"",grid:0};a[60]=
{lvl:0,type:"decimal",len:10,dec:2,sign:false,pic:"ZZZZZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"PASAJEROS_TARIFA",gxz:"Z62PASAJEROS_TARIFA",gxold:"O62PASAJEROS_TARIFA",gxvar:"A62PASAJEROS_TARIFA",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A62PASAJEROS_TARIFA=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.Z62PASAJEROS_TARIFA=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("PASAJEROS_TARIFA",
gx.O.A62PASAJEROS_TARIFA,2,gx.decimalPoint)},c2v:function(){gx.O.A62PASAJEROS_TARIFA=this.val()},val:function(){return gx.fn.getDecimalValue("PASAJEROS_TARIFA",gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};a[61]={fld:"",grid:0};a[62]={fld:"",grid:0};a[63]={fld:"PASAJEROS_COMENTARIO_CONTAINER",grid:0};a[64]={fld:"",format:0,grid:0};a[65]={fld:"",grid:0};a[66]={lvl:0,type:"svchar",len:150,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"PASAJEROS_COMENTARIO",gxz:"Z64PASAJEROS_COMENTARIO",
gxold:"O64PASAJEROS_COMENTARIO",gxvar:"A64PASAJEROS_COMENTARIO",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A64PASAJEROS_COMENTARIO=a},v2z:function(a){gx.O.Z64PASAJEROS_COMENTARIO=a},v2c:function(){gx.fn.setControlValue("PASAJEROS_COMENTARIO",gx.O.A64PASAJEROS_COMENTARIO,0)},c2v:function(){gx.O.A64PASAJEROS_COMENTARIO=this.val()},val:function(){return gx.fn.getControlValue("PASAJEROS_COMENTARIO")},nac:gx.falseFn};a[67]={fld:"",grid:0};a[68]={fld:"",grid:0};a[69]={fld:"",grid:0};
this.O63PASAJEROS_ID=this.Z63PASAJEROS_ID=this.A63PASAJEROS_ID=0;this.O59PASAJEROS_CARGA=this.Z59PASAJEROS_CARGA=this.A59PASAJEROS_CARGA=this.O60PASAJEROS_TIPO_TARIFA=this.Z60PASAJEROS_TIPO_TARIFA=this.A60PASAJEROS_TIPO_TARIFA=this.O58PASAJEROS_ESCLUSA=this.Z58PASAJEROS_ESCLUSA=this.A58PASAJEROS_ESCLUSA="";this.O62PASAJEROS_TARIFA=this.Z62PASAJEROS_TARIFA=this.A62PASAJEROS_TARIFA=this.O61PASAJEROS_TON_TARIFA=this.Z61PASAJEROS_TON_TARIFA=this.A61PASAJEROS_TON_TARIFA=this.O65PASAJEROS_ID_TON_TARIF=
this.Z65PASAJEROS_ID_TON_TARIF=this.A65PASAJEROS_ID_TON_TARIF=0;this.O64PASAJEROS_COMENTARIO=this.Z64PASAJEROS_COMENTARIO=this.A64PASAJEROS_COMENTARIO="";this.A63PASAJEROS_ID=0;this.A59PASAJEROS_CARGA=this.A60PASAJEROS_TIPO_TARIFA=this.A58PASAJEROS_ESCLUSA="";this.A62PASAJEROS_TARIFA=this.A61PASAJEROS_TON_TARIFA=this.A65PASAJEROS_ID_TON_TARIF=0;this.A64PASAJEROS_COMENTARIO="";this.Events={e110911_client:["ENTER",true],e120911_client:["CANCEL",true]};this.EvtParms.ENTER=[[{postForm:true}],[]];this.EvtParms.REFRESH=
[[],[]];this.EnterCtrl=["BTN_ENTER"];this.setVCMap("Gx_mode","vMODE",0,"char");this.InitStandaloneVars()});gx.createParentObj(pasajeros);
