gx.evt.autoSkip=!1;
gx.define("ppalmasterpage",!1,function(){this.ServerClass="ppalmasterpage";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.IsMasterPage=true;this.skipOnEnter=this.hasEnterEvent=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){};this.Validv_Segmento=function(){try{var a=gx.util.balloon.getNew("vSEGMENTO_MPAGE");this.AnyError=0;if(!(this.AV5Segmento=="Portacontenedores"||this.AV5Segmento=="Graneles Secos"||this.AV5Segmento==
"Tanqueros"||this.AV5Segmento=="Quimiqueros"||this.AV5Segmento=="Gaseros LPG"||this.AV5Segmento=="Gaseros LNG"||this.AV5Segmento=="Porta Veh\u00edculos y Ro-Ro"||this.AV5Segmento=="Pasajeros"||this.AV5Segmento=="Refrigerados"||this.AV5Segmento=="Carga General"||this.AV5Segmento=="Otros"||""==this.AV5Segmento))try{a.setError(gx.text.format(gx.getMessage("GXSPC_OutOfRange"),gx.getMessage("Segmento"),"","","","","","","",""));this.AnyError=1}catch(b){}}catch(c){}try{return a==null?true:a.show()}catch(d){}return true};
this.e121u1_client=function(){this.clearMessages();if(gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")=="AdvancedContainer"){gx.fn.setCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class","AdvancedContainer AdvancedContainerVisible");gx.fn.setCtrlProperty("BTNTOGGLE_MPAGE","Class",gx.fn.getCtrlProperty("BTNTOGGLE_MPAGE","Class")+" BtnToggleActive")}else{gx.fn.setCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class","AdvancedContainer");gx.fn.setCtrlProperty("BTNTOGGLE_MPAGE","Class","BtnToggle")}this.refreshOutputs([{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',
ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}])};this.e161u2_client=function(){this.clearMessages();gx.fn.setCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class","AdvancedContainer");gx.fn.setCtrlProperty("BTNTOGGLE_MPAGE","Class","BtnToggle");this.refreshOutputs([{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}])};this.e111u1_client=function(){this.clearMessages();gx.fn.setCtrlProperty("ADVANCEDCONTAINER_MPAGE",
"Class","AdvancedContainer");gx.fn.setCtrlProperty("BTNTOGGLE_MPAGE","Class","BtnToggle");this.refreshOutputs([{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}])};this.e171u2_client=function(){this.executeServerEvent("ENTER_MPAGE",true)};this.e181u2_client=function(){this.executeServerEvent("CANCEL_MPAGE",true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,
21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,42,44,45];this.GXLastCtrlId=45;a[2]={fld:"",grid:0};a[3]={fld:"MAINTABLE",grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};a[6]={fld:"HEADER",grid:0};a[7]={fld:"",grid:0};a[8]={fld:"",grid:0};a[9]={fld:"IMAGE1",grid:0};a[10]={fld:"",grid:0};a[11]={fld:"",grid:0};a[12]={fld:"RECENT",grid:0};a[13]={fld:"",grid:0};a[14]={fld:"",grid:0};a[15]={fld:"TEXTBLOCK1",format:0,grid:0};a[16]={fld:"",grid:0};a[17]={fld:"",grid:0};a[18]={fld:"",grid:0};
a[19]={fld:"CONTENT",grid:0};a[20]={fld:"",grid:0};a[21]={fld:"",grid:0};a[22]={fld:"CONTENT1",grid:0};a[23]={fld:"",grid:0};a[24]={fld:"",grid:0};a[25]={fld:"ADVANCEDCONTAINER",grid:0};a[26]={fld:"",grid:0};a[27]={fld:"",grid:0};a[28]={fld:"",grid:0};a[29]={fld:"SOLICITUDFECHAFILTERCONTAINER",grid:0};a[30]={fld:"",grid:0};a[31]={fld:"",grid:0};a[32]={fld:"TEXTBLOCKSELECCIONE",format:0,grid:0};a[33]={fld:"",grid:0};a[34]={fld:"",grid:0};a[35]={fld:"",grid:0};a[36]={lvl:0,type:"svchar",len:40,dec:0,
sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Validv_Segmento,isvalid:null,fld:"vSEGMENTO_MPAGE",gxz:"ZV5Segmento",gxold:"OV5Segmento",gxvar:"AV5Segmento",ucs:[],op:[36],ip:[36],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.AV5Segmento=a},v2z:function(a){gx.O.ZV5Segmento=a},v2c:function(){gx.fn.setComboBoxValue("vSEGMENTO_MPAGE",gx.O.AV5Segmento);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV5Segmento=this.val()},val:function(){return gx.fn.getControlValue("vSEGMENTO_MPAGE")},
nac:gx.falseFn};this.declareDomainHdlr(36,function(){});a[37]={fld:"",grid:0};a[38]={fld:"GRIDTABLE",grid:0};a[39]={fld:"",grid:0};a[40]={fld:"",grid:0};a[42]={fld:"",grid:0};a[44]={fld:"",grid:0};a[45]={fld:"",grid:0};this.AV5Segmento=this.OV5Segmento=this.ZV5Segmento=this.AV5Segmento="";this.Events={e171u2_client:["ENTER_MPAGE",true],e181u2_client:["CANCEL_MPAGE",true],e121u1_client:["TOGGLE_MPAGE",false],e161u2_client:["BUSCAR_MPAGE",false],e111u1_client:["VSEGMENTO_MPAGE.CLICK_MPAGE",false]};
this.EvtParms.REFRESH_MPAGE=[[],[]];this.EvtParms.TOGGLE_MPAGE=[[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}]];this.EvtParms.BUSCAR_MPAGE=[[],[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},
{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}]];this.EvtParms["VSEGMENTO_MPAGE.CLICK_MPAGE"]=[[],[{av:'gx.fn.getCtrlProperty("ADVANCEDCONTAINER_MPAGE","Class")',ctrl:"ADVANCEDCONTAINER_MPAGE",prop:"Class"},{ctrl:"BTNTOGGLE_MPAGE",prop:"Class"}]];this.InitStandaloneVars()});gx.setMasterPage(new ppalmasterpage);
