gx.evt.autoSkip=!1;
gx.define("ref_cgral_desp",!1,function(){this.ServerClass="ref_cgral_desp";this.PackageName="GeneXus.Programs";this.setObjectType("trn");this.hasEnterEvent=true;this.skipOnEnter=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=true;this.SetStandaloneVars=function(){this.Gx_mode=gx.fn.getControlValue("vMODE")};this.Valid_Ref_cgral_desp_id=function(){gx.ajax.validSrvEvt("dyncall","Valid_Ref_cgral_desp_id",["gx.O.A49REF_CGRAL_DESP_ID","gx.O.A44REF_CGRAL_DESP_CARGA","gx.O.A45REF_CGRAL_DESP_TIPO",
"gx.O.A48REF_CGRAL_DESP_ID_TON_TARIF","gx.O.A46REF_CGRAL_DESP_TON_TARIF","gx.num.urlDecimal(gx.O.A47REF_CGRAL_DESP_TARIFA,gx.thousandSeparator,gx.decimalPoint)","gx.O.A50REF_CGRAL_DESP_COMENTARIO"],["A44REF_CGRAL_DESP_CARGA","A45REF_CGRAL_DESP_TIPO","A48REF_CGRAL_DESP_ID_TON_TARIF","A46REF_CGRAL_DESP_TON_TARIF","A47REF_CGRAL_DESP_TARIFA","A50REF_CGRAL_DESP_COMENTARIO","Gx_mode","Z49REF_CGRAL_DESP_ID","Z44REF_CGRAL_DESP_CARGA","Z45REF_CGRAL_DESP_TIPO","Z48REF_CGRAL_DESP_ID_TON_TARIF","Z46REF_CGRAL_DESP_TON_TARIF",
"Z47REF_CGRAL_DESP_TARIFA","Z50REF_CGRAL_DESP_COMENTARIO",["BTN_DELETE","Enabled"],["BTN_ENTER","Enabled"]]);return true};this.e11079_client=function(){this.executeServerEvent("ENTER",true)};this.e12079_client=function(){this.executeServerEvent("CANCEL",true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,16,17,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63];this.GXLastCtrlId=63;a[2]={fld:"",grid:0};
a[3]={fld:"TABLEMAIN",grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};a[6]={fld:"TITLE",format:0,grid:0};a[7]={fld:"",grid:0};a[8]={fld:"",grid:0};a[9]={fld:"",grid:0};a[10]={fld:"",grid:0};a[16]={fld:"",grid:0};a[17]={fld:"",grid:0};a[19]={fld:"",grid:0};a[20]={fld:"",grid:0};a[21]={fld:"REF_CGRAL_DESP_ID_CONTAINER",grid:0};a[22]={fld:"",format:0,grid:0};a[23]={fld:"",grid:0};a[24]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Valid_Ref_cgral_desp_id,isvalid:null,
rgrid:[],fld:"REF_CGRAL_DESP_ID",gxz:"Z49REF_CGRAL_DESP_ID",gxold:"O49REF_CGRAL_DESP_ID",gxvar:"A49REF_CGRAL_DESP_ID",ucs:[],op:[60,54,48,42,36,30],ip:[60,54,48,42,36,30,24],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A49REF_CGRAL_DESP_ID=gx.num.intval(a)},v2z:function(a){gx.O.Z49REF_CGRAL_DESP_ID=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("REF_CGRAL_DESP_ID",gx.O.A49REF_CGRAL_DESP_ID,0)},c2v:function(){gx.O.A49REF_CGRAL_DESP_ID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("REF_CGRAL_DESP_ID",
gx.thousandSeparator)},nac:gx.falseFn};a[25]={fld:"",grid:0};a[26]={fld:"",grid:0};a[27]={fld:"REF_CGRAL_DESP_CARGA_CONTAINER",grid:0};a[28]={fld:"",format:0,grid:0};a[29]={fld:"",grid:0};a[30]={lvl:0,type:"svchar",len:150,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"REF_CGRAL_DESP_CARGA",gxz:"Z44REF_CGRAL_DESP_CARGA",gxold:"O44REF_CGRAL_DESP_CARGA",gxvar:"A44REF_CGRAL_DESP_CARGA",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.A44REF_CGRAL_DESP_CARGA=a},
v2z:function(a){gx.O.Z44REF_CGRAL_DESP_CARGA=a},v2c:function(){gx.fn.setComboBoxValue("REF_CGRAL_DESP_CARGA",gx.O.A44REF_CGRAL_DESP_CARGA)},c2v:function(){gx.O.A44REF_CGRAL_DESP_CARGA=this.val()},val:function(){return gx.fn.getControlValue("REF_CGRAL_DESP_CARGA")},nac:gx.falseFn};a[31]={fld:"",grid:0};a[32]={fld:"",grid:0};a[33]={fld:"REF_CGRAL_DESP_TIPO_CONTAINER",grid:0};a[34]={fld:"",format:0,grid:0};a[35]={fld:"",grid:0};a[36]={lvl:0,type:"svchar",len:50,dec:0,sign:false,ro:0,grid:0,gxgrid:null,
fnc:null,isvalid:null,fld:"REF_CGRAL_DESP_TIPO",gxz:"Z45REF_CGRAL_DESP_TIPO",gxold:"O45REF_CGRAL_DESP_TIPO",gxvar:"A45REF_CGRAL_DESP_TIPO",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.A45REF_CGRAL_DESP_TIPO=a},v2z:function(a){gx.O.Z45REF_CGRAL_DESP_TIPO=a},v2c:function(){gx.fn.setComboBoxValue("REF_CGRAL_DESP_TIPO",gx.O.A45REF_CGRAL_DESP_TIPO)},c2v:function(){gx.O.A45REF_CGRAL_DESP_TIPO=this.val()},val:function(){return gx.fn.getControlValue("REF_CGRAL_DESP_TIPO")},nac:gx.falseFn};
a[37]={fld:"",grid:0};a[38]={fld:"",grid:0};a[39]={fld:"REF_CGRAL_DESP_ID_TON_TARIF_CONTAINER",grid:0};a[40]={fld:"",format:0,grid:0};a[41]={fld:"",grid:0};a[42]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"REF_CGRAL_DESP_ID_TON_TARIF",gxz:"Z48REF_CGRAL_DESP_ID_TON_TARIF",gxold:"O48REF_CGRAL_DESP_ID_TON_TARIF",gxvar:"A48REF_CGRAL_DESP_ID_TON_TARIF",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A48REF_CGRAL_DESP_ID_TON_TARIF=
gx.num.intval(a)},v2z:function(a){gx.O.Z48REF_CGRAL_DESP_ID_TON_TARIF=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("REF_CGRAL_DESP_ID_TON_TARIF",gx.O.A48REF_CGRAL_DESP_ID_TON_TARIF,0)},c2v:function(){gx.O.A48REF_CGRAL_DESP_ID_TON_TARIF=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("REF_CGRAL_DESP_ID_TON_TARIF",gx.thousandSeparator)},nac:gx.falseFn};a[43]={fld:"",grid:0};a[44]={fld:"",grid:0};a[45]={fld:"REF_CGRAL_DESP_TON_TARIF_CONTAINER",grid:0};a[46]={fld:"",format:0,
grid:0};a[47]={fld:"",grid:0};a[48]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"ZZZZZZZZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"REF_CGRAL_DESP_TON_TARIF",gxz:"Z46REF_CGRAL_DESP_TON_TARIF",gxold:"O46REF_CGRAL_DESP_TON_TARIF",gxvar:"A46REF_CGRAL_DESP_TON_TARIF",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A46REF_CGRAL_DESP_TON_TARIF=gx.num.intval(a)},v2z:function(a){gx.O.Z46REF_CGRAL_DESP_TON_TARIF=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("REF_CGRAL_DESP_TON_TARIF",
gx.O.A46REF_CGRAL_DESP_TON_TARIF,0)},c2v:function(){gx.O.A46REF_CGRAL_DESP_TON_TARIF=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("REF_CGRAL_DESP_TON_TARIF",gx.thousandSeparator)},nac:gx.falseFn};a[49]={fld:"",grid:0};a[50]={fld:"",grid:0};a[51]={fld:"REF_CGRAL_DESP_TARIFA_CONTAINER",grid:0};a[52]={fld:"",format:0,grid:0};a[53]={fld:"",grid:0};a[54]={lvl:0,type:"decimal",len:10,dec:2,sign:false,pic:"ZZZZZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"REF_CGRAL_DESP_TARIFA",
gxz:"Z47REF_CGRAL_DESP_TARIFA",gxold:"O47REF_CGRAL_DESP_TARIFA",gxvar:"A47REF_CGRAL_DESP_TARIFA",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A47REF_CGRAL_DESP_TARIFA=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.Z47REF_CGRAL_DESP_TARIFA=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("REF_CGRAL_DESP_TARIFA",gx.O.A47REF_CGRAL_DESP_TARIFA,2,gx.decimalPoint)},c2v:function(){gx.O.A47REF_CGRAL_DESP_TARIFA=this.val()},val:function(){return gx.fn.getDecimalValue("REF_CGRAL_DESP_TARIFA",
gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};a[55]={fld:"",grid:0};a[56]={fld:"",grid:0};a[57]={fld:"REF_CGRAL_DESP_COMENTARIO_CONTAINER",grid:0};a[58]={fld:"",format:0,grid:0};a[59]={fld:"",grid:0};a[60]={lvl:0,type:"svchar",len:250,dec:0,sign:false,ro:0,multiline:true,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"REF_CGRAL_DESP_COMENTARIO",gxz:"Z50REF_CGRAL_DESP_COMENTARIO",gxold:"O50REF_CGRAL_DESP_COMENTARIO",gxvar:"A50REF_CGRAL_DESP_COMENTARIO",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",
v2v:function(a){gx.O.A50REF_CGRAL_DESP_COMENTARIO=a},v2z:function(a){gx.O.Z50REF_CGRAL_DESP_COMENTARIO=a},v2c:function(){gx.fn.setControlValue("REF_CGRAL_DESP_COMENTARIO",gx.O.A50REF_CGRAL_DESP_COMENTARIO,0)},c2v:function(){gx.O.A50REF_CGRAL_DESP_COMENTARIO=this.val()},val:function(){return gx.fn.getControlValue("REF_CGRAL_DESP_COMENTARIO")},nac:gx.falseFn};a[61]={fld:"",grid:0};a[62]={fld:"",grid:0};a[63]={fld:"",grid:0};this.O49REF_CGRAL_DESP_ID=this.Z49REF_CGRAL_DESP_ID=this.A49REF_CGRAL_DESP_ID=
0;this.O45REF_CGRAL_DESP_TIPO=this.Z45REF_CGRAL_DESP_TIPO=this.A45REF_CGRAL_DESP_TIPO=this.O44REF_CGRAL_DESP_CARGA=this.Z44REF_CGRAL_DESP_CARGA=this.A44REF_CGRAL_DESP_CARGA="";this.O47REF_CGRAL_DESP_TARIFA=this.Z47REF_CGRAL_DESP_TARIFA=this.A47REF_CGRAL_DESP_TARIFA=this.O46REF_CGRAL_DESP_TON_TARIF=this.Z46REF_CGRAL_DESP_TON_TARIF=this.A46REF_CGRAL_DESP_TON_TARIF=this.O48REF_CGRAL_DESP_ID_TON_TARIF=this.Z48REF_CGRAL_DESP_ID_TON_TARIF=this.A48REF_CGRAL_DESP_ID_TON_TARIF=0;this.O50REF_CGRAL_DESP_COMENTARIO=
this.Z50REF_CGRAL_DESP_COMENTARIO=this.A50REF_CGRAL_DESP_COMENTARIO="";this.A49REF_CGRAL_DESP_ID=0;this.A45REF_CGRAL_DESP_TIPO=this.A44REF_CGRAL_DESP_CARGA="";this.A47REF_CGRAL_DESP_TARIFA=this.A46REF_CGRAL_DESP_TON_TARIF=this.A48REF_CGRAL_DESP_ID_TON_TARIF=0;this.A50REF_CGRAL_DESP_COMENTARIO="";this.Events={e11079_client:["ENTER",true],e12079_client:["CANCEL",true]};this.EvtParms.ENTER=[[{postForm:true}],[]];this.EvtParms.REFRESH=[[],[]];this.EnterCtrl=["BTN_ENTER"];this.setVCMap("Gx_mode","vMODE",
0,"char");this.InitStandaloneVars()});gx.createParentObj(ref_cgral_desp);
