gx.evt.autoSkip=!1;
gx.define("rwdrecentlinks",!0,function(a){this.ServerClass="rwdrecentlinks";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.setCmpContext(a);this.ReadonlyForm=true;this.skipOnEnter=this.hasEnterEvent=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){this.AV6FormCaption=gx.fn.getControlValue("vFORMCAPTION");this.AV7FormPgmName=gx.fn.getControlValue("vFORMPGMNAME")};this.e11051_client=function(){this.clearMessages();gx.fn.getCtrlProperty("MAINTABLE",
"Class")=="RecentLinksMainTable"?gx.fn.setCtrlProperty("MAINTABLE","Class","RecentLinksMainTable RecentLinksMainTableExpanded"):gx.fn.setCtrlProperty("MAINTABLE","Class","RecentLinksMainTable");this.refreshOutputs([{av:'gx.fn.getCtrlProperty("MAINTABLE","Class")',ctrl:"MAINTABLE",prop:"Class"}])};this.e13052_client=function(a){this.executeServerEvent("ENTER",true,a)};this.e14052_client=function(a){this.executeServerEvent("CANCEL",true,a)};a=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,9,10,11,12];
this.GXLastCtrlId=12;var b=this.LinksContainer=new gx.grid.grid(this,2,"WbpLvl2",8,"Links","Links","LinksContainer",this.CmpContext,this.IsMasterPage,"rwdrecentlinks",[],true,9999,true,true,49995,true,false,false,"",0,"px",gx.getMessage("GXM_newrow"),true,false,false,null,null,false,"",true,[1,0,0,0]);b.startDiv("Linkstable","0px","0px");b.startDiv("","0px","0px");b.startDiv("","0px","0px");b.addTextBlock("PLACE",null);b.endDiv();b.endDiv();b.endDiv();this.setGrid(b);a[2]={fld:"",grid:0};a[3]={fld:"MAINTABLE",
grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};a[6]={fld:"RECENTTEXT",format:0,grid:0};a[7]={fld:"",grid:0};a[9]={fld:"LINKSTABLE",grid:8};a[10]={fld:"",grid:8};a[11]={fld:"",grid:8};a[12]={fld:"PLACE",format:0,grid:8};this.AV7FormPgmName=this.AV6FormCaption="";this.AV12RecentLinksItem={};this.Events={e13052_client:["ENTER",true],e14052_client:["CANCEL",true],e11051_client:["RECENTTEXT.CLICK",false]};this.EvtParms.REFRESH=[[{av:"LINKS_nFirstRecordOnPage"},{av:"LINKS_nEOF"},{av:"subLinks_Rows"},
{av:"AV6FormCaption",fld:"vFORMCAPTION"},{av:"sPrefix"}],[]];this.EvtParms["RECENTTEXT.CLICK"]=[[{av:'gx.fn.getCtrlProperty("MAINTABLE","Class")',ctrl:"MAINTABLE",prop:"Class"}],[{av:'gx.fn.getCtrlProperty("MAINTABLE","Class")',ctrl:"MAINTABLE",prop:"Class"}]];this.EvtParms["LINKS.LOAD"]=[[{av:"AV11RecentLinksItems",fld:"vRECENTLINKSITEMS"},{av:"AV12RecentLinksItem",fld:"vRECENTLINKSITEM"},{av:"AV6FormCaption",fld:"vFORMCAPTION"}],[{av:"AV11RecentLinksItems",fld:"vRECENTLINKSITEMS"},{av:"AV9i",fld:"vI"},
{av:"AV12RecentLinksItem",fld:"vRECENTLINKSITEM"},{av:"AV13PlaceCaption",fld:"vPLACECAPTION"},{av:'gx.fn.getCtrlProperty("PLACE","Caption")',ctrl:"PLACE",prop:"Caption"},{av:'gx.fn.getCtrlProperty("PLACE","Link")',ctrl:"PLACE",prop:"Link"}]];this.EvtParms.LINKS_FIRSTPAGE=[[{av:"LINKS_nFirstRecordOnPage"},{av:"LINKS_nEOF"},{av:"subLinks_Rows"},{av:"AV6FormCaption",fld:"vFORMCAPTION"},{av:"sPrefix"}],[]];this.EvtParms.LINKS_PREVPAGE=[[{av:"LINKS_nFirstRecordOnPage"},{av:"LINKS_nEOF"},{av:"subLinks_Rows"},
{av:"AV6FormCaption",fld:"vFORMCAPTION"},{av:"sPrefix"}],[]];this.EvtParms.LINKS_NEXTPAGE=[[{av:"LINKS_nFirstRecordOnPage"},{av:"LINKS_nEOF"},{av:"subLinks_Rows"},{av:"AV6FormCaption",fld:"vFORMCAPTION"},{av:"sPrefix"}],[]];this.EvtParms.LINKS_LASTPAGE=[[{av:"LINKS_nFirstRecordOnPage"},{av:"LINKS_nEOF"},{av:"subLinks_Rows"},{av:"AV6FormCaption",fld:"vFORMCAPTION"},{av:"sPrefix"}],[]];this.setVCMap("AV6FormCaption","vFORMCAPTION",0,"char");this.setVCMap("AV7FormPgmName","vFORMPGMNAME",0,"svchar");
this.setVCMap("AV6FormCaption","vFORMCAPTION",0,"char");b.addRefreshingVar({rfrVar:"AV6FormCaption"});this.InitStandaloneVars()});
