/*
               File: Segmento1
        Description: Segmento1
             Author: GeneXus C# Generator version 10_3_2-86442
       Generated on: 1/20/2015 7:38:20.51
       Program type: Main program
          Main DBMS: sqlserver
*/
gx.evt.autoSkip = false;
gx.define('segmento1', false, function () {
   this.ServerClass =  "segmento1" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV45P1=gx.fn.getControlValue("vP1") ;
      this.AV46P2=gx.fn.getControlValue("vP2") ;
   };
   this.Validv_Solicitudfecha=function()
   {
      try {
         var gxballoon = gx.util.balloon.getNew("vSOLICITUDFECHA");
         this.AnyError  = 0;
         if ( ! ( (new gx.date.gxdate("").compare(this.AV58SolicitudFecha)==0) || new gx.date.gxdate( this.AV58SolicitudFecha ).compare( gx.date.ymdtod( 1753, 01, 01) ) >= 0 ) )
         {
            try {
               gxballoon.setError(gx.text.format( gx.getMessage( "GXSPC_OutOfRange"), gx.getMessage( "SolicitudFecha"), "", "", "", "", "", "", "", ""));
               this.AnyError = 1 ;
            }
            catch(e){}
         }

      }
      catch(e){}
      try {
         if (gxballoon == null) return true; return gxballoon.show();
      }
      catch(e){}
      return true ;
   }
   this.e12072_client=function()
   {
      this.executeServerEvent("ENTER", true);
   };
   this.e13072_client=function()
   {
      this.executeServerEvent("CANCEL", true);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,52,53,55,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,83,85,87,89,91,93,95,98,99,101,102,104,105,107,108,110,111,113,114,116,117,120,121,123,124,126,127,129,130,132,133,135,136,138,139,142,143,145,146,148,149,151,152,154,155,157,158,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210];
   this.GXLastCtrlId =210;
   GXValidFnc[2]={fld:"",grid:0};
   GXValidFnc[3]={fld:"MAINTABLE",grid:0};
   GXValidFnc[4]={fld:"",grid:0};
   GXValidFnc[5]={fld:"",grid:0};
   GXValidFnc[6]={fld:"ADVANCEDCONTAINER",grid:0};
   GXValidFnc[7]={fld:"",grid:0};
   GXValidFnc[8]={fld:"",grid:0};
   GXValidFnc[9]={fld:"",grid:0};
   GXValidFnc[10]={fld:"SOLICITUDFECHAFILTERCONTAINER",grid:0};
   GXValidFnc[11]={fld:"",grid:0};
   GXValidFnc[12]={fld:"",grid:0};
   GXValidFnc[13]={fld:"LBLSOLICITUDFECHAFILTER", format:1,grid:0};
   GXValidFnc[14]={fld:"",grid:0};
   GXValidFnc[15]={fld:"",grid:0};
   GXValidFnc[16]={fld:"",grid:0};
   GXValidFnc[17]={lvl:0,type:"date",len:10,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Validv_Solicitudfecha,isvalid:null,fld:"vSOLICITUDFECHA",gxz:"ZV58SolicitudFecha",gxold:"OV58SolicitudFecha",gxvar:"AV58SolicitudFecha",dp:{f:0,st:false,wn:false,mf:false,pic:"99/99/9999",dec:0},ucs:[],op:[17],ip:[17],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV58SolicitudFecha=gx.fn.toDatetimeValue(Value)},v2z:function(Value){gx.O.ZV58SolicitudFecha=gx.fn.toDatetimeValue(Value)},v2c:function(){gx.fn.setControlValue("vSOLICITUDFECHA",gx.O.AV58SolicitudFecha,0)},c2v:function(){gx.O.AV58SolicitudFecha=gx.fn.toDatetimeValue(this.val())},val:function(){return gx.fn.getControlValue("vSOLICITUDFECHA")},nac:gx.falseFn};
   GXValidFnc[18]={fld:"",grid:0};
   GXValidFnc[19]={fld:"",grid:0};
   GXValidFnc[20]={fld:"FILTROIPFILTERCONTAINER",grid:0};
   GXValidFnc[21]={fld:"",grid:0};
   GXValidFnc[22]={fld:"",grid:0};
   GXValidFnc[23]={fld:"LBLFILTROIPFILTER", format:1,grid:0};
   GXValidFnc[24]={fld:"",grid:0};
   GXValidFnc[25]={fld:"",grid:0};
   GXValidFnc[26]={fld:"",grid:0};
   GXValidFnc[27]={lvl:0,type:"int",len:9,dec:0,sign:false,pic:"ZZZZZZZZZ",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vFILTROIP",gxz:"ZV24filtroIP",gxold:"OV24filtroIP",gxvar:"AV24filtroIP",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV24filtroIP=gx.num.intval(Value)},v2z:function(Value){gx.O.ZV24filtroIP=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vFILTROIP",gx.O.AV24filtroIP,0)},c2v:function(){gx.O.AV24filtroIP=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vFILTROIP",gx.thousandSeparator)},nac:gx.falseFn};
   GXValidFnc[28]={fld:"",grid:0};
   GXValidFnc[29]={fld:"",grid:0};
   GXValidFnc[30]={fld:"NOMBRECORTOFILTERCONTAINER",grid:0};
   GXValidFnc[31]={fld:"",grid:0};
   GXValidFnc[32]={fld:"",grid:0};
   GXValidFnc[33]={fld:"LBLNOMBRECORTO", format:1,grid:0};
   GXValidFnc[34]={fld:"",grid:0};
   GXValidFnc[35]={fld:"",grid:0};
   GXValidFnc[36]={fld:"",grid:0};
   GXValidFnc[37]={lvl:0,type:"svchar",len:40,dec:0,sign:false,pic:"@!",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vNOMBRECORTO",gxz:"ZV34NombreCorto",gxold:"OV34NombreCorto",gxvar:"AV34NombreCorto",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV34NombreCorto=Value},v2z:function(Value){gx.O.ZV34NombreCorto=Value},v2c:function(){gx.fn.setControlValue("vNOMBRECORTO",gx.O.AV34NombreCorto,0)},c2v:function(){gx.O.AV34NombreCorto=this.val()},val:function(){return gx.fn.getControlValue("vNOMBRECORTO")},nac:gx.falseFn};
   GXValidFnc[38]={fld:"",grid:0};
   GXValidFnc[39]={fld:"",grid:0};
   GXValidFnc[40]={fld:"TABLE2",grid:0};
   GXValidFnc[41]={fld:"",grid:0};
   GXValidFnc[42]={fld:"",grid:0};
   GXValidFnc[44]={fld:"",grid:0};
   GXValidFnc[45]={fld:"",grid:0};
   GXValidFnc[46]={fld:"",grid:0};
   GXValidFnc[47]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vTIPOUSUARIO",gxz:"ZV59TIPOUSUARIO",gxold:"OV59TIPOUSUARIO",gxvar:"AV59TIPOUSUARIO",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV59TIPOUSUARIO=Value},v2z:function(Value){gx.O.ZV59TIPOUSUARIO=Value},v2c:function(){gx.fn.setControlValue("vTIPOUSUARIO",gx.O.AV59TIPOUSUARIO,0)},c2v:function(){gx.O.AV59TIPOUSUARIO=this.val()},val:function(){return gx.fn.getControlValue("vTIPOUSUARIO")},nac:gx.falseFn};
   GXValidFnc[48]={fld:"",grid:0};
   GXValidFnc[49]={fld:"GRIDTABLE",grid:0};
   GXValidFnc[50]={fld:"",grid:0};
   GXValidFnc[51]={fld:"",grid:0};
   GXValidFnc[52]={fld:"TITLETEXT", format:0,grid:0};
   GXValidFnc[53]={fld:"",grid:0};
   GXValidFnc[55]={fld:"",grid:0};
   GXValidFnc[57]={fld:"",grid:0};
   GXValidFnc[58]={fld:"",grid:0};
   GXValidFnc[59]={fld:"COLABORADOR_CONTAINER",grid:0};
   GXValidFnc[60]={fld:"", format:0,grid:0};
   GXValidFnc[61]={fld:"",grid:0};
   GXValidFnc[62]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vCOLABORADOR",gxz:"ZV7COLABORADOR",gxold:"OV7COLABORADOR",gxvar:"AV7COLABORADOR",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV7COLABORADOR=Value},v2z:function(Value){gx.O.ZV7COLABORADOR=Value},v2c:function(){gx.fn.setControlValue("vCOLABORADOR",gx.O.AV7COLABORADOR,0)},c2v:function(){gx.O.AV7COLABORADOR=this.val()},val:function(){return gx.fn.getControlValue("vCOLABORADOR")},nac:gx.falseFn};
   GXValidFnc[63]={fld:"",grid:0};
   GXValidFnc[64]={fld:"FECHAPANTALLA_CONTAINER",grid:0};
   GXValidFnc[65]={fld:"", format:0,grid:0};
   GXValidFnc[66]={fld:"",grid:0};
   GXValidFnc[67]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vFECHAPANTALLA",gxz:"ZV23FechaPantalla",gxold:"OV23FechaPantalla",gxvar:"AV23FechaPantalla",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV23FechaPantalla=Value},v2z:function(Value){gx.O.ZV23FechaPantalla=Value},v2c:function(){gx.fn.setControlValue("vFECHAPANTALLA",gx.O.AV23FechaPantalla,0)},c2v:function(){gx.O.AV23FechaPantalla=this.val()},val:function(){return gx.fn.getControlValue("vFECHAPANTALLA")},nac:gx.falseFn};
   GXValidFnc[68]={fld:"",grid:0};
   GXValidFnc[69]={fld:"DOMINGOHORARIOSEMANALPANTALLA_CONTAINER",grid:0};
   GXValidFnc[70]={fld:"", format:0,grid:0};
   GXValidFnc[71]={fld:"",grid:0};
   GXValidFnc[72]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vDOMINGOHORARIOSEMANALPANTALLA",gxz:"ZV18DomingoHorarioSemanalPantalla",gxold:"OV18DomingoHorarioSemanalPantalla",gxvar:"AV18DomingoHorarioSemanalPantalla",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV18DomingoHorarioSemanalPantalla=Value},v2z:function(Value){gx.O.ZV18DomingoHorarioSemanalPantalla=Value},v2c:function(){gx.fn.setControlValue("vDOMINGOHORARIOSEMANALPANTALLA",gx.O.AV18DomingoHorarioSemanalPantalla,0)},c2v:function(){gx.O.AV18DomingoHorarioSemanalPantalla=this.val()},val:function(){return gx.fn.getControlValue("vDOMINGOHORARIOSEMANALPANTALLA")},nac:gx.falseFn};
   GXValidFnc[73]={fld:"",grid:0};
   GXValidFnc[74]={fld:"REMOLCADOR_CONTAINER",grid:0};
   GXValidFnc[75]={fld:"", format:0,grid:0};
   GXValidFnc[76]={fld:"",grid:0};
   GXValidFnc[77]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vREMOLCADOR",gxz:"ZV51Remolcador",gxold:"OV51Remolcador",gxvar:"AV51Remolcador",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV51Remolcador=Value},v2z:function(Value){gx.O.ZV51Remolcador=Value},v2c:function(){gx.fn.setControlValue("vREMOLCADOR",gx.O.AV51Remolcador,0)},c2v:function(){gx.O.AV51Remolcador=this.val()},val:function(){return gx.fn.getControlValue("vREMOLCADOR")},nac:gx.falseFn};
   GXValidFnc[78]={fld:"",grid:0};
   GXValidFnc[79]={fld:"",grid:0};
   GXValidFnc[80]={fld:"TABLE1",grid:0};
   GXValidFnc[83]={fld:"TEXTBLOCK1", format:0,grid:0};
   GXValidFnc[85]={fld:"TEXTBLOCK2", format:0,grid:0};
   GXValidFnc[87]={fld:"TEXTBLOCK3", format:0,grid:0};
   GXValidFnc[89]={fld:"TEXTBLOCK4", format:0,grid:0};
   GXValidFnc[91]={fld:"TEXTBLOCK5", format:0,grid:0};
   GXValidFnc[93]={fld:"TEXTBLOCK6", format:0,grid:0};
   GXValidFnc[95]={fld:"TEXTBLOCK7", format:0,grid:0};
   GXValidFnc[98]={fld:"",grid:0};
   GXValidFnc[99]={lvl:0,type:"svchar",len:5,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vNUMDIA1",gxz:"ZV35NumDia1",gxold:"OV35NumDia1",gxvar:"AV35NumDia1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV35NumDia1=Value},v2z:function(Value){gx.O.ZV35NumDia1=Value},v2c:function(){gx.fn.setControlValue("vNUMDIA1",gx.O.AV35NumDia1,0)},c2v:function(){gx.O.AV35NumDia1=this.val()},val:function(){return gx.fn.getControlValue("vNUMDIA1")},nac:gx.falseFn};
   GXValidFnc[101]={fld:"",grid:0};
   GXValidFnc[102]={lvl:0,type:"svchar",len:5,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vNUMDIA2",gxz:"ZV36NumDia2",gxold:"OV36NumDia2",gxvar:"AV36NumDia2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV36NumDia2=Value},v2z:function(Value){gx.O.ZV36NumDia2=Value},v2c:function(){gx.fn.setControlValue("vNUMDIA2",gx.O.AV36NumDia2,0)},c2v:function(){gx.O.AV36NumDia2=this.val()},val:function(){return gx.fn.getControlValue("vNUMDIA2")},nac:gx.falseFn};
   GXValidFnc[104]={fld:"",grid:0};
   GXValidFnc[105]={lvl:0,type:"svchar",len:5,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vNUMDIA3",gxz:"ZV37NumDia3",gxold:"OV37NumDia3",gxvar:"AV37NumDia3",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV37NumDia3=Value},v2z:function(Value){gx.O.ZV37NumDia3=Value},v2c:function(){gx.fn.setControlValue("vNUMDIA3",gx.O.AV37NumDia3,0)},c2v:function(){gx.O.AV37NumDia3=this.val()},val:function(){return gx.fn.getControlValue("vNUMDIA3")},nac:gx.falseFn};
   GXValidFnc[107]={fld:"",grid:0};
   GXValidFnc[108]={lvl:0,type:"svchar",len:5,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vNUMDIA4",gxz:"ZV38NumDia4",gxold:"OV38NumDia4",gxvar:"AV38NumDia4",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV38NumDia4=Value},v2z:function(Value){gx.O.ZV38NumDia4=Value},v2c:function(){gx.fn.setControlValue("vNUMDIA4",gx.O.AV38NumDia4,0)},c2v:function(){gx.O.AV38NumDia4=this.val()},val:function(){return gx.fn.getControlValue("vNUMDIA4")},nac:gx.falseFn};
   GXValidFnc[110]={fld:"",grid:0};
   GXValidFnc[111]={lvl:0,type:"svchar",len:5,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vNUMDIA5",gxz:"ZV39NumDia5",gxold:"OV39NumDia5",gxvar:"AV39NumDia5",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV39NumDia5=Value},v2z:function(Value){gx.O.ZV39NumDia5=Value},v2c:function(){gx.fn.setControlValue("vNUMDIA5",gx.O.AV39NumDia5,0)},c2v:function(){gx.O.AV39NumDia5=this.val()},val:function(){return gx.fn.getControlValue("vNUMDIA5")},nac:gx.falseFn};
   GXValidFnc[113]={fld:"",grid:0};
   GXValidFnc[114]={lvl:0,type:"svchar",len:5,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vNUMDIA6",gxz:"ZV40NumDia6",gxold:"OV40NumDia6",gxvar:"AV40NumDia6",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV40NumDia6=Value},v2z:function(Value){gx.O.ZV40NumDia6=Value},v2c:function(){gx.fn.setControlValue("vNUMDIA6",gx.O.AV40NumDia6,0)},c2v:function(){gx.O.AV40NumDia6=this.val()},val:function(){return gx.fn.getControlValue("vNUMDIA6")},nac:gx.falseFn};
   GXValidFnc[116]={fld:"",grid:0};
   GXValidFnc[117]={lvl:0,type:"svchar",len:5,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vNUMDIA7",gxz:"ZV41NumDia7",gxold:"OV41NumDia7",gxvar:"AV41NumDia7",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV41NumDia7=Value},v2z:function(Value){gx.O.ZV41NumDia7=Value},v2c:function(){gx.fn.setControlValue("vNUMDIA7",gx.O.AV41NumDia7,0)},c2v:function(){gx.O.AV41NumDia7=this.val()},val:function(){return gx.fn.getControlValue("vNUMDIA7")},nac:gx.falseFn};
   GXValidFnc[120]={fld:"",grid:0};
   GXValidFnc[121]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vTURNO1",gxz:"ZV62Turno1",gxold:"OV62Turno1",gxvar:"AV62Turno1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV62Turno1=Value},v2z:function(Value){gx.O.ZV62Turno1=Value},v2c:function(){gx.fn.setControlValue("vTURNO1",gx.O.AV62Turno1,0)},c2v:function(){gx.O.AV62Turno1=this.val()},val:function(){return gx.fn.getControlValue("vTURNO1")},nac:gx.falseFn};
   GXValidFnc[123]={fld:"",grid:0};
   GXValidFnc[124]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vTURNO2",gxz:"ZV63Turno2",gxold:"OV63Turno2",gxvar:"AV63Turno2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV63Turno2=Value},v2z:function(Value){gx.O.ZV63Turno2=Value},v2c:function(){gx.fn.setControlValue("vTURNO2",gx.O.AV63Turno2,0)},c2v:function(){gx.O.AV63Turno2=this.val()},val:function(){return gx.fn.getControlValue("vTURNO2")},nac:gx.falseFn};
   GXValidFnc[126]={fld:"",grid:0};
   GXValidFnc[127]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vTURNO3",gxz:"ZV64Turno3",gxold:"OV64Turno3",gxvar:"AV64Turno3",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV64Turno3=Value},v2z:function(Value){gx.O.ZV64Turno3=Value},v2c:function(){gx.fn.setControlValue("vTURNO3",gx.O.AV64Turno3,0)},c2v:function(){gx.O.AV64Turno3=this.val()},val:function(){return gx.fn.getControlValue("vTURNO3")},nac:gx.falseFn};
   GXValidFnc[129]={fld:"",grid:0};
   GXValidFnc[130]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vTURNO4",gxz:"ZV65Turno4",gxold:"OV65Turno4",gxvar:"AV65Turno4",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV65Turno4=Value},v2z:function(Value){gx.O.ZV65Turno4=Value},v2c:function(){gx.fn.setControlValue("vTURNO4",gx.O.AV65Turno4,0)},c2v:function(){gx.O.AV65Turno4=this.val()},val:function(){return gx.fn.getControlValue("vTURNO4")},nac:gx.falseFn};
   GXValidFnc[132]={fld:"",grid:0};
   GXValidFnc[133]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vTURNO5",gxz:"ZV66Turno5",gxold:"OV66Turno5",gxvar:"AV66Turno5",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV66Turno5=Value},v2z:function(Value){gx.O.ZV66Turno5=Value},v2c:function(){gx.fn.setControlValue("vTURNO5",gx.O.AV66Turno5,0)},c2v:function(){gx.O.AV66Turno5=this.val()},val:function(){return gx.fn.getControlValue("vTURNO5")},nac:gx.falseFn};
   GXValidFnc[135]={fld:"",grid:0};
   GXValidFnc[136]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vTURNO6",gxz:"ZV67Turno6",gxold:"OV67Turno6",gxvar:"AV67Turno6",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV67Turno6=Value},v2z:function(Value){gx.O.ZV67Turno6=Value},v2c:function(){gx.fn.setControlValue("vTURNO6",gx.O.AV67Turno6,0)},c2v:function(){gx.O.AV67Turno6=this.val()},val:function(){return gx.fn.getControlValue("vTURNO6")},nac:gx.falseFn};
   GXValidFnc[138]={fld:"",grid:0};
   GXValidFnc[139]={lvl:0,type:"svchar",len:2,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vTURNO7",gxz:"ZV68Turno7",gxold:"OV68Turno7",gxvar:"AV68Turno7",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV68Turno7=Value},v2z:function(Value){gx.O.ZV68Turno7=Value},v2c:function(){gx.fn.setControlValue("vTURNO7",gx.O.AV68Turno7,0)},c2v:function(){gx.O.AV68Turno7=this.val()},val:function(){return gx.fn.getControlValue("vTURNO7")},nac:gx.falseFn};
   GXValidFnc[142]={fld:"",grid:0};
   GXValidFnc[143]={lvl:0,type:"svchar",len:3,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vDIA1TURNOOTRO",gxz:"ZV10Dia1TurnoOtro",gxold:"OV10Dia1TurnoOtro",gxvar:"AV10Dia1TurnoOtro",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV10Dia1TurnoOtro=Value},v2z:function(Value){gx.O.ZV10Dia1TurnoOtro=Value},v2c:function(){gx.fn.setControlValue("vDIA1TURNOOTRO",gx.O.AV10Dia1TurnoOtro,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){gx.O.AV10Dia1TurnoOtro=this.val()},val:function(){return gx.fn.getControlValue("vDIA1TURNOOTRO")},nac:gx.falseFn};
   this.declareDomainHdlr( 143 , function() {
   });
   GXValidFnc[145]={fld:"",grid:0};
   GXValidFnc[146]={lvl:0,type:"svchar",len:3,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vDIA2TURNOOTRO",gxz:"ZV11Dia2TurnoOtro",gxold:"OV11Dia2TurnoOtro",gxvar:"AV11Dia2TurnoOtro",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV11Dia2TurnoOtro=Value},v2z:function(Value){gx.O.ZV11Dia2TurnoOtro=Value},v2c:function(){gx.fn.setControlValue("vDIA2TURNOOTRO",gx.O.AV11Dia2TurnoOtro,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){gx.O.AV11Dia2TurnoOtro=this.val()},val:function(){return gx.fn.getControlValue("vDIA2TURNOOTRO")},nac:gx.falseFn};
   this.declareDomainHdlr( 146 , function() {
   });
   GXValidFnc[148]={fld:"",grid:0};
   GXValidFnc[149]={lvl:0,type:"svchar",len:3,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vDIA3TURNOOTRO",gxz:"ZV12Dia3TurnoOtro",gxold:"OV12Dia3TurnoOtro",gxvar:"AV12Dia3TurnoOtro",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV12Dia3TurnoOtro=Value},v2z:function(Value){gx.O.ZV12Dia3TurnoOtro=Value},v2c:function(){gx.fn.setControlValue("vDIA3TURNOOTRO",gx.O.AV12Dia3TurnoOtro,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){gx.O.AV12Dia3TurnoOtro=this.val()},val:function(){return gx.fn.getControlValue("vDIA3TURNOOTRO")},nac:gx.falseFn};
   this.declareDomainHdlr( 149 , function() {
   });
   GXValidFnc[151]={fld:"",grid:0};
   GXValidFnc[152]={lvl:0,type:"svchar",len:3,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vDIA4TURNOOTRO",gxz:"ZV13Dia4TurnoOtro",gxold:"OV13Dia4TurnoOtro",gxvar:"AV13Dia4TurnoOtro",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV13Dia4TurnoOtro=Value},v2z:function(Value){gx.O.ZV13Dia4TurnoOtro=Value},v2c:function(){gx.fn.setControlValue("vDIA4TURNOOTRO",gx.O.AV13Dia4TurnoOtro,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){gx.O.AV13Dia4TurnoOtro=this.val()},val:function(){return gx.fn.getControlValue("vDIA4TURNOOTRO")},nac:gx.falseFn};
   this.declareDomainHdlr( 152 , function() {
   });
   GXValidFnc[154]={fld:"",grid:0};
   GXValidFnc[155]={lvl:0,type:"svchar",len:3,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vDIA5TURNOOTRO",gxz:"ZV14Dia5TurnoOtro",gxold:"OV14Dia5TurnoOtro",gxvar:"AV14Dia5TurnoOtro",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV14Dia5TurnoOtro=Value},v2z:function(Value){gx.O.ZV14Dia5TurnoOtro=Value},v2c:function(){gx.fn.setControlValue("vDIA5TURNOOTRO",gx.O.AV14Dia5TurnoOtro,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){gx.O.AV14Dia5TurnoOtro=this.val()},val:function(){return gx.fn.getControlValue("vDIA5TURNOOTRO")},nac:gx.falseFn};
   this.declareDomainHdlr( 155 , function() {
   });
   GXValidFnc[157]={fld:"",grid:0};
   GXValidFnc[158]={lvl:0,type:"svchar",len:3,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vDIA6TURNOOTRO",gxz:"ZV15Dia6TurnoOtro",gxold:"OV15Dia6TurnoOtro",gxvar:"AV15Dia6TurnoOtro",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV15Dia6TurnoOtro=Value},v2z:function(Value){gx.O.ZV15Dia6TurnoOtro=Value},v2c:function(){gx.fn.setControlValue("vDIA6TURNOOTRO",gx.O.AV15Dia6TurnoOtro,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){gx.O.AV15Dia6TurnoOtro=this.val()},val:function(){return gx.fn.getControlValue("vDIA6TURNOOTRO")},nac:gx.falseFn};
   this.declareDomainHdlr( 158 , function() {
   });
   GXValidFnc[160]={fld:"",grid:0};
   GXValidFnc[161]={lvl:0,type:"svchar",len:3,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vDIA7TURNOOTRO",gxz:"ZV16Dia7TurnoOtro",gxold:"OV16Dia7TurnoOtro",gxvar:"AV16Dia7TurnoOtro",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV16Dia7TurnoOtro=Value},v2z:function(Value){gx.O.ZV16Dia7TurnoOtro=Value},v2c:function(){gx.fn.setControlValue("vDIA7TURNOOTRO",gx.O.AV16Dia7TurnoOtro,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){gx.O.AV16Dia7TurnoOtro=this.val()},val:function(){return gx.fn.getControlValue("vDIA7TURNOOTRO")},nac:gx.falseFn};
   this.declareDomainHdlr( 161 , function() {
   });
   GXValidFnc[162]={fld:"",grid:0};
   GXValidFnc[163]={fld:"",grid:0};
   GXValidFnc[164]={fld:"GROUP1",grid:0};
   GXValidFnc[165]={fld:"GROUP1TABLE",grid:0};
   GXValidFnc[166]={fld:"",grid:0};
   GXValidFnc[167]={fld:"",grid:0};
   GXValidFnc[168]={fld:"MASTER_CONTAINER",grid:0};
   GXValidFnc[169]={fld:"", format:0,grid:0};
   GXValidFnc[170]={fld:"",grid:0};
   GXValidFnc[171]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vMASTER",gxz:"ZV31Master",gxold:"OV31Master",gxvar:"AV31Master",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV31Master=Value},v2z:function(Value){gx.O.ZV31Master=Value},v2c:function(){gx.fn.setControlValue("vMASTER",gx.O.AV31Master,0)},c2v:function(){gx.O.AV31Master=this.val()},val:function(){return gx.fn.getControlValue("vMASTER")},nac:gx.falseFn};
   GXValidFnc[172]={fld:"",grid:0};
   GXValidFnc[173]={fld:"",grid:0};
   GXValidFnc[174]={fld:"ENGINEER_CONTAINER",grid:0};
   GXValidFnc[175]={fld:"", format:0,grid:0};
   GXValidFnc[176]={fld:"",grid:0};
   GXValidFnc[177]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vENGINEER",gxz:"ZV20Engineer",gxold:"OV20Engineer",gxvar:"AV20Engineer",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV20Engineer=Value},v2z:function(Value){gx.O.ZV20Engineer=Value},v2c:function(){gx.fn.setControlValue("vENGINEER",gx.O.AV20Engineer,0)},c2v:function(){gx.O.AV20Engineer=this.val()},val:function(){return gx.fn.getControlValue("vENGINEER")},nac:gx.falseFn};
   GXValidFnc[178]={fld:"",grid:0};
   GXValidFnc[179]={fld:"",grid:0};
   GXValidFnc[180]={fld:"SEAMAN1_CONTAINER",grid:0};
   GXValidFnc[181]={fld:"", format:0,grid:0};
   GXValidFnc[182]={fld:"",grid:0};
   GXValidFnc[183]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vSEAMAN1",gxz:"ZV54Seaman1",gxold:"OV54Seaman1",gxvar:"AV54Seaman1",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV54Seaman1=Value},v2z:function(Value){gx.O.ZV54Seaman1=Value},v2c:function(){gx.fn.setControlValue("vSEAMAN1",gx.O.AV54Seaman1,0)},c2v:function(){gx.O.AV54Seaman1=this.val()},val:function(){return gx.fn.getControlValue("vSEAMAN1")},nac:gx.falseFn};
   GXValidFnc[184]={fld:"",grid:0};
   GXValidFnc[185]={fld:"",grid:0};
   GXValidFnc[186]={fld:"SEAMAN2_CONTAINER",grid:0};
   GXValidFnc[187]={fld:"", format:0,grid:0};
   GXValidFnc[188]={fld:"",grid:0};
   GXValidFnc[189]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vSEAMAN2",gxz:"ZV55Seaman2",gxold:"OV55Seaman2",gxvar:"AV55Seaman2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV55Seaman2=Value},v2z:function(Value){gx.O.ZV55Seaman2=Value},v2c:function(){gx.fn.setControlValue("vSEAMAN2",gx.O.AV55Seaman2,0)},c2v:function(){gx.O.AV55Seaman2=this.val()},val:function(){return gx.fn.getControlValue("vSEAMAN2")},nac:gx.falseFn};
   GXValidFnc[190]={fld:"",grid:0};
   GXValidFnc[191]={fld:"",grid:0};
   GXValidFnc[192]={fld:"BOSNSEAMAN_CONTAINER",grid:0};
   GXValidFnc[193]={fld:"", format:0,grid:0};
   GXValidFnc[194]={fld:"",grid:0};
   GXValidFnc[195]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vBOSNSEAMAN",gxz:"ZV6BosnSeaman",gxold:"OV6BosnSeaman",gxvar:"AV6BosnSeaman",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV6BosnSeaman=Value},v2z:function(Value){gx.O.ZV6BosnSeaman=Value},v2c:function(){gx.fn.setControlValue("vBOSNSEAMAN",gx.O.AV6BosnSeaman,0)},c2v:function(){gx.O.AV6BosnSeaman=this.val()},val:function(){return gx.fn.getControlValue("vBOSNSEAMAN")},nac:gx.falseFn};
   GXValidFnc[196]={fld:"",grid:0};
   GXValidFnc[197]={fld:"",grid:0};
   GXValidFnc[198]={fld:"OILER_CONTAINER",grid:0};
   GXValidFnc[199]={fld:"", format:0,grid:0};
   GXValidFnc[200]={fld:"",grid:0};
   GXValidFnc[201]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vOILER",gxz:"ZV42Oiler",gxold:"OV42Oiler",gxvar:"AV42Oiler",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV42Oiler=Value},v2z:function(Value){gx.O.ZV42Oiler=Value},v2c:function(){gx.fn.setControlValue("vOILER",gx.O.AV42Oiler,0)},c2v:function(){gx.O.AV42Oiler=this.val()},val:function(){return gx.fn.getControlValue("vOILER")},nac:gx.falseFn};
   GXValidFnc[202]={fld:"",grid:0};
   GXValidFnc[203]={fld:"",grid:0};
   GXValidFnc[204]={fld:"MATE_CONTAINER",grid:0};
   GXValidFnc[205]={fld:"", format:0,grid:0};
   GXValidFnc[206]={fld:"",grid:0};
   GXValidFnc[207]={lvl:0,type:"svchar",len:100,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,fld:"vMATE",gxz:"ZV32Mate",gxold:"OV32Mate",gxvar:"AV32Mate",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(Value){gx.O.AV32Mate=Value},v2z:function(Value){gx.O.ZV32Mate=Value},v2c:function(){gx.fn.setControlValue("vMATE",gx.O.AV32Mate,0)},c2v:function(){gx.O.AV32Mate=this.val()},val:function(){return gx.fn.getControlValue("vMATE")},nac:gx.falseFn};
   GXValidFnc[208]={fld:"",grid:0};
   GXValidFnc[209]={fld:"",grid:0};
   GXValidFnc[210]={fld:"JSSCRIPT", format:2,grid:0};
   this.AV58SolicitudFecha = gx.date.nullDate() ;
   this.ZV58SolicitudFecha = gx.date.nullDate() ;
   this.OV58SolicitudFecha = gx.date.nullDate() ;
   this.AV24filtroIP = 0 ;
   this.ZV24filtroIP = 0 ;
   this.OV24filtroIP = 0 ;
   this.AV34NombreCorto = "" ;
   this.ZV34NombreCorto = "" ;
   this.OV34NombreCorto = "" ;
   this.AV59TIPOUSUARIO = "" ;
   this.ZV59TIPOUSUARIO = "" ;
   this.OV59TIPOUSUARIO = "" ;
   this.AV7COLABORADOR = "" ;
   this.ZV7COLABORADOR = "" ;
   this.OV7COLABORADOR = "" ;
   this.AV23FechaPantalla = "" ;
   this.ZV23FechaPantalla = "" ;
   this.OV23FechaPantalla = "" ;
   this.AV18DomingoHorarioSemanalPantalla = "" ;
   this.ZV18DomingoHorarioSemanalPantalla = "" ;
   this.OV18DomingoHorarioSemanalPantalla = "" ;
   this.AV51Remolcador = "" ;
   this.ZV51Remolcador = "" ;
   this.OV51Remolcador = "" ;
   this.AV35NumDia1 = "" ;
   this.ZV35NumDia1 = "" ;
   this.OV35NumDia1 = "" ;
   this.AV36NumDia2 = "" ;
   this.ZV36NumDia2 = "" ;
   this.OV36NumDia2 = "" ;
   this.AV37NumDia3 = "" ;
   this.ZV37NumDia3 = "" ;
   this.OV37NumDia3 = "" ;
   this.AV38NumDia4 = "" ;
   this.ZV38NumDia4 = "" ;
   this.OV38NumDia4 = "" ;
   this.AV39NumDia5 = "" ;
   this.ZV39NumDia5 = "" ;
   this.OV39NumDia5 = "" ;
   this.AV40NumDia6 = "" ;
   this.ZV40NumDia6 = "" ;
   this.OV40NumDia6 = "" ;
   this.AV41NumDia7 = "" ;
   this.ZV41NumDia7 = "" ;
   this.OV41NumDia7 = "" ;
   this.AV62Turno1 = "" ;
   this.ZV62Turno1 = "" ;
   this.OV62Turno1 = "" ;
   this.AV63Turno2 = "" ;
   this.ZV63Turno2 = "" ;
   this.OV63Turno2 = "" ;
   this.AV64Turno3 = "" ;
   this.ZV64Turno3 = "" ;
   this.OV64Turno3 = "" ;
   this.AV65Turno4 = "" ;
   this.ZV65Turno4 = "" ;
   this.OV65Turno4 = "" ;
   this.AV66Turno5 = "" ;
   this.ZV66Turno5 = "" ;
   this.OV66Turno5 = "" ;
   this.AV67Turno6 = "" ;
   this.ZV67Turno6 = "" ;
   this.OV67Turno6 = "" ;
   this.AV68Turno7 = "" ;
   this.ZV68Turno7 = "" ;
   this.OV68Turno7 = "" ;
   this.AV10Dia1TurnoOtro = "" ;
   this.ZV10Dia1TurnoOtro = "" ;
   this.OV10Dia1TurnoOtro = "" ;
   this.AV11Dia2TurnoOtro = "" ;
   this.ZV11Dia2TurnoOtro = "" ;
   this.OV11Dia2TurnoOtro = "" ;
   this.AV12Dia3TurnoOtro = "" ;
   this.ZV12Dia3TurnoOtro = "" ;
   this.OV12Dia3TurnoOtro = "" ;
   this.AV13Dia4TurnoOtro = "" ;
   this.ZV13Dia4TurnoOtro = "" ;
   this.OV13Dia4TurnoOtro = "" ;
   this.AV14Dia5TurnoOtro = "" ;
   this.ZV14Dia5TurnoOtro = "" ;
   this.OV14Dia5TurnoOtro = "" ;
   this.AV15Dia6TurnoOtro = "" ;
   this.ZV15Dia6TurnoOtro = "" ;
   this.OV15Dia6TurnoOtro = "" ;
   this.AV16Dia7TurnoOtro = "" ;
   this.ZV16Dia7TurnoOtro = "" ;
   this.OV16Dia7TurnoOtro = "" ;
   this.AV31Master = "" ;
   this.ZV31Master = "" ;
   this.OV31Master = "" ;
   this.AV20Engineer = "" ;
   this.ZV20Engineer = "" ;
   this.OV20Engineer = "" ;
   this.AV54Seaman1 = "" ;
   this.ZV54Seaman1 = "" ;
   this.OV54Seaman1 = "" ;
   this.AV55Seaman2 = "" ;
   this.ZV55Seaman2 = "" ;
   this.OV55Seaman2 = "" ;
   this.AV6BosnSeaman = "" ;
   this.ZV6BosnSeaman = "" ;
   this.OV6BosnSeaman = "" ;
   this.AV42Oiler = "" ;
   this.ZV42Oiler = "" ;
   this.OV42Oiler = "" ;
   this.AV32Mate = "" ;
   this.ZV32Mate = "" ;
   this.OV32Mate = "" ;
   this.AV58SolicitudFecha = gx.date.nullDate() ;
   this.AV24filtroIP = 0 ;
   this.AV34NombreCorto = "" ;
   this.AV59TIPOUSUARIO = "" ;
   this.AV7COLABORADOR = "" ;
   this.AV23FechaPantalla = "" ;
   this.AV18DomingoHorarioSemanalPantalla = "" ;
   this.AV51Remolcador = "" ;
   this.AV35NumDia1 = "" ;
   this.AV36NumDia2 = "" ;
   this.AV37NumDia3 = "" ;
   this.AV38NumDia4 = "" ;
   this.AV39NumDia5 = "" ;
   this.AV40NumDia6 = "" ;
   this.AV41NumDia7 = "" ;
   this.AV62Turno1 = "" ;
   this.AV63Turno2 = "" ;
   this.AV64Turno3 = "" ;
   this.AV65Turno4 = "" ;
   this.AV66Turno5 = "" ;
   this.AV67Turno6 = "" ;
   this.AV68Turno7 = "" ;
   this.AV10Dia1TurnoOtro = "" ;
   this.AV11Dia2TurnoOtro = "" ;
   this.AV12Dia3TurnoOtro = "" ;
   this.AV13Dia4TurnoOtro = "" ;
   this.AV14Dia5TurnoOtro = "" ;
   this.AV15Dia6TurnoOtro = "" ;
   this.AV16Dia7TurnoOtro = "" ;
   this.AV31Master = "" ;
   this.AV20Engineer = "" ;
   this.AV54Seaman1 = "" ;
   this.AV55Seaman2 = "" ;
   this.AV6BosnSeaman = "" ;
   this.AV42Oiler = "" ;
   this.AV32Mate = "" ;
   this.AV45P1 = "" ;
   this.AV46P2 = "" ;
   this.Events = {"e12072_client": ["ENTER", true] ,"e13072_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[],[]];
   this.setVCMap("AV45P1", "vP1", 0, "svchar");
   this.setVCMap("AV46P2", "vP2", 0, "svchar");
   this.InitStandaloneVars( );
});
gx.createParentObj(segmento1);
