gx.evt.autoSkip=!1;
gx.define("tabbedview",!0,function(b){this.ServerClass="tabbedview";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.setCmpContext(b);this.ReadonlyForm=true;this.skipOnEnter=this.hasEnterEvent=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){this.AV5FirstTab=gx.fn.getIntegerValue("vFIRSTTAB",gx.thousandSeparator);this.AV11LastTab=gx.fn.getIntegerValue("vLASTTAB",gx.thousandSeparator);this.AV18Tabs=gx.fn.getControlValue("vTABS");
this.AV15TabCode=gx.fn.getControlValue("vTABCODE");this.AV8Index=gx.fn.getIntegerValue("vINDEX",gx.thousandSeparator);this.AV13SelectedTab=gx.fn.getIntegerValue("vSELECTEDTAB",gx.thousandSeparator);this.AV19TabsMarkup=gx.fn.getControlValue("vTABSMARKUP");this.AV20TabTemplate=gx.fn.getControlValue("vTABTEMPLATE");this.AV14Tab=gx.fn.getControlValue("vTAB");this.AV23URLChangedEvent=gx.fn.getControlValue("vURLCHANGEDEVENT")};this.s112_client=function(){this.AV20TabTemplate='<li class="%1">';this.AV20TabTemplate=
this.AV20TabTemplate+'<a id="%2Tab" %3%7 class="%4">';this.AV20TabTemplate=this.AV20TabTemplate+'<span class="%5">';this.AV20TabTemplate=this.AV20TabTemplate+'<span class="TabBackground">';this.AV20TabTemplate=this.AV20TabTemplate+'<span class="TabText">%6</span>';this.AV20TabTemplate=this.AV20TabTemplate+"</span>";this.AV20TabTemplate=this.AV20TabTemplate+"</span>";this.AV20TabTemplate=this.AV20TabTemplate+"</a>";this.AV20TabTemplate=this.AV20TabTemplate+"</li>"};this.s142_client=function(){this.AV5FirstTab=
1;this.AV11LastTab=this.AV18Tabs.length;gx.fn.setCtrlProperty("TABPREVIOUS","Visible",0);gx.fn.setCtrlProperty("TABNEXT","Visible",0)};this.e110i2_client=function(){this.executeServerEvent("HISTORYMANAGER.URLCHANGED",false)};this.e150i2_client=function(){this.executeServerEvent("ENTER",true)};this.e160i2_client=function(){this.executeServerEvent("CANCEL",true)};b=this.GXValidFnc=[];this.GXCtrlIds=[2,5,6,7,8,11];this.GXLastCtrlId=11;var a=this.HISTORYMANAGERContainer=gx.uc.getNew(this,15,0,"HistoryManager",
this.CmpContext+"HISTORYMANAGERContainer","Historymanager");a.setProp("Hash","Hash","","char");a.setProp("URL","Url","","char");a.setProp("QueryString","Querystring","","char");a.setProp("Visible","Visible",true,"bool");a.setProp("Enabled","Enabled",false,"boolean");a.setProp("Class","Class","","char");a.setC2ShowFunction(function(a){a.start()});a.addEventHandler("URLChanged",this.e110i2_client);this.setUserControl(a);b[2]={fld:"TABLE1",grid:0};b[5]={fld:"TABCONTAINER",grid:0};b[6]={fld:"TABS",format:1,
grid:0};b[7]={fld:"TABPREVIOUS",grid:0};b[8]={fld:"TABNEXT",grid:0};b[11]={fld:"TABLE2",grid:0};this.AV18Tabs=[];this.AV15TabCode="";this.AV13SelectedTab=this.AV8Index=this.AV11LastTab=this.AV5FirstTab=0;this.AV20TabTemplate=this.AV19TabsMarkup="";this.AV14Tab={};this.AV23URLChangedEvent=false;this.Events={e110i2_client:["HISTORYMANAGER.URLCHANGED",true],e150i2_client:["ENTER",true],e160i2_client:["CANCEL",true],s112_client:["'INIT'",false],s142_client:["'SCROLLTABS'",false]};this.EvtParms.REFRESH=
[[{av:"AV23URLChangedEvent",fld:"vURLCHANGEDEVENT"},{av:"AV5FirstTab",fld:"vFIRSTTAB"},{av:"AV11LastTab",fld:"vLASTTAB"},{av:"AV18Tabs",fld:"vTABS"},{av:"AV15TabCode",fld:"vTABCODE"},{av:"this.HISTORYMANAGERContainer.Hash",ctrl:"HISTORYMANAGER",prop:"Hash"},{av:"AV8Index",fld:"vINDEX"},{av:"AV13SelectedTab",fld:"vSELECTEDTAB"},{av:"AV19TabsMarkup",fld:"vTABSMARKUP"},{av:"AV20TabTemplate",fld:"vTABTEMPLATE"},{av:"AV14Tab",fld:"vTAB"}],[{av:"AV9IsFirstTab",fld:"vISFIRSTTAB"},{av:"AV19TabsMarkup",fld:"vTABSMARKUP"},
{av:"AV8Index",fld:"vINDEX"},{av:"AV14Tab",fld:"vTAB"},{av:"AV18Tabs",fld:"TABS"},{av:"AV6Found",fld:"vFOUND"},{av:"AV13SelectedTab",fld:"vSELECTEDTAB"},{av:"AV5FirstTab",fld:"vFIRSTTAB"},{av:"AV11LastTab",fld:"vLASTTAB"},{av:'gx.fn.getCtrlProperty("TABPREVIOUS","Visible")',ctrl:"TABPREVIOUS",prop:"Visible"},{av:'gx.fn.getCtrlProperty("TABNEXT","Visible")',ctrl:"TABNEXT",prop:"Visible"},{av:"AV16TabLeftCls",fld:"vTABLEFTCLS"},{av:"AV17TabRightCls",fld:"vTABRIGHTCLS"},{av:"AV21WebComponentUrl",fld:"vWEBCOMPONENTURL"},
{ctrl:"COMPONENT"},{av:"AV12OnClickTemplate",fld:"vONCLICKTEMPLATE"}]];this.EvtParms["HISTORYMANAGER.URLCHANGED"]=[[{av:"AV5FirstTab",fld:"vFIRSTTAB"},{av:"AV11LastTab",fld:"vLASTTAB"},{av:"AV18Tabs",fld:"vTABS"},{av:"AV15TabCode",fld:"vTABCODE"},{av:"this.HISTORYMANAGERContainer.Hash",ctrl:"HISTORYMANAGER",prop:"Hash"},{av:"AV8Index",fld:"vINDEX"},{av:"AV13SelectedTab",fld:"vSELECTEDTAB"},{av:"AV19TabsMarkup",fld:"vTABSMARKUP"},{av:"AV20TabTemplate",fld:"vTABTEMPLATE"},{av:"AV14Tab",fld:"vTAB"}],
[{av:"AV23URLChangedEvent",fld:"vURLCHANGEDEVENT"},{av:"AV9IsFirstTab",fld:"vISFIRSTTAB"},{av:"AV19TabsMarkup",fld:"vTABSMARKUP"},{av:"AV8Index",fld:"vINDEX"},{av:"AV14Tab",fld:"vTAB"},{av:"AV18Tabs",fld:"TABS"},{av:"AV6Found",fld:"vFOUND"},{av:"AV13SelectedTab",fld:"vSELECTEDTAB"},{av:"AV5FirstTab",fld:"vFIRSTTAB"},{av:"AV11LastTab",fld:"vLASTTAB"},{av:'gx.fn.getCtrlProperty("TABPREVIOUS","Visible")',ctrl:"TABPREVIOUS",prop:"Visible"},{av:'gx.fn.getCtrlProperty("TABNEXT","Visible")',ctrl:"TABNEXT",
prop:"Visible"},{av:"AV16TabLeftCls",fld:"vTABLEFTCLS"},{av:"AV17TabRightCls",fld:"vTABRIGHTCLS"},{av:"AV21WebComponentUrl",fld:"vWEBCOMPONENTURL"},{ctrl:"COMPONENT"},{av:"AV12OnClickTemplate",fld:"vONCLICKTEMPLATE"}]];this.setVCMap("AV5FirstTab","vFIRSTTAB",0,"int");this.setVCMap("AV11LastTab","vLASTTAB",0,"int");this.setVCMap("AV18Tabs","TABS",0,"CollTabOptions.TabOptionsItem");this.setVCMap("AV15TabCode","vTABCODE",0,"char");this.setVCMap("AV8Index","vINDEX",0,"int");this.setVCMap("AV13SelectedTab",
"vSELECTEDTAB",0,"int");this.setVCMap("AV19TabsMarkup","vTABSMARKUP",0,"char");this.setVCMap("AV20TabTemplate","vTABTEMPLATE",0,"char");this.setVCMap("AV14Tab","vTAB",0,"TabOptions.TabOptionsItem");this.setVCMap("AV23URLChangedEvent","vURLCHANGEDEVENT",0,"boolean");this.InitStandaloneVars();this.setComponent({id:"COMPONENT",GXClass:null,Prefix:"W0014",lvl:1})});
