gx.evt.autoSkip=!1;
gx.define("veh_roro",!1,function(){this.ServerClass="veh_roro";this.PackageName="GeneXus.Programs";this.setObjectType("trn");this.hasEnterEvent=true;this.skipOnEnter=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=true;this.SetStandaloneVars=function(){this.Gx_mode=gx.fn.getControlValue("vMODE")};this.Valid_Veh_roro_id=function(){gx.ajax.validSrvEvt("dyncall","Valid_Veh_roro_id",["gx.O.A38VEH_RORO_ID","gx.num.urlDecimal(gx.O.A39VEH_RORO_TON_INI,gx.thousandSeparator,gx.decimalPoint)","gx.num.urlDecimal(gx.O.A40VEH_RORO_TON_FIN,gx.thousandSeparator,gx.decimalPoint)",
"gx.num.urlDecimal(gx.O.A41VEH_RORO_UTIL_INI,gx.thousandSeparator,gx.decimalPoint)","gx.num.urlDecimal(gx.O.A42VEH_RORO_UTIL_FIN,gx.thousandSeparator,gx.decimalPoint)","gx.num.urlDecimal(gx.O.A43VEH_RORO_TARIFA,gx.thousandSeparator,gx.decimalPoint)"],["A39VEH_RORO_TON_INI","A40VEH_RORO_TON_FIN","A41VEH_RORO_UTIL_INI","A42VEH_RORO_UTIL_FIN","A43VEH_RORO_TARIFA","Gx_mode","Z38VEH_RORO_ID","Z39VEH_RORO_TON_INI","Z40VEH_RORO_TON_FIN","Z41VEH_RORO_UTIL_INI","Z42VEH_RORO_UTIL_FIN","Z43VEH_RORO_TARIFA",
["BTN_DELETE","Enabled"],["BTN_ENTER","Enabled"]]);return true};this.e11068_client=function(){this.executeServerEvent("ENTER",true)};this.e12068_client=function(){this.executeServerEvent("CANCEL",true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,16,17,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57];this.GXLastCtrlId=57;a[2]={fld:"",grid:0};a[3]={fld:"TABLEMAIN",grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};
a[6]={fld:"TITLE",format:0,grid:0};a[7]={fld:"",grid:0};a[8]={fld:"",grid:0};a[9]={fld:"",grid:0};a[10]={fld:"",grid:0};a[16]={fld:"",grid:0};a[17]={fld:"",grid:0};a[19]={fld:"",grid:0};a[20]={fld:"",grid:0};a[21]={fld:"VEH_RORO_ID_CONTAINER",grid:0};a[22]={fld:"",format:0,grid:0};a[23]={fld:"",grid:0};a[24]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Valid_Veh_roro_id,isvalid:null,rgrid:[],fld:"VEH_RORO_ID",gxz:"Z38VEH_RORO_ID",gxold:"O38VEH_RORO_ID",gxvar:"A38VEH_RORO_ID",
ucs:[],op:[54,48,42,36,30],ip:[54,48,42,36,30,24],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A38VEH_RORO_ID=gx.num.intval(a)},v2z:function(a){gx.O.Z38VEH_RORO_ID=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("VEH_RORO_ID",gx.O.A38VEH_RORO_ID,0)},c2v:function(){gx.O.A38VEH_RORO_ID=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("VEH_RORO_ID",gx.thousandSeparator)},nac:gx.falseFn};a[25]={fld:"",grid:0};a[26]={fld:"",grid:0};a[27]={fld:"VEH_RORO_TON_INI_CONTAINER",
grid:0};a[28]={fld:"",format:0,grid:0};a[29]={fld:"",grid:0};a[30]={lvl:0,type:"decimal",len:10,dec:2,sign:false,pic:"ZZZZZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"VEH_RORO_TON_INI",gxz:"Z39VEH_RORO_TON_INI",gxold:"O39VEH_RORO_TON_INI",gxvar:"A39VEH_RORO_TON_INI",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A39VEH_RORO_TON_INI=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.Z39VEH_RORO_TON_INI=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},
v2c:function(){gx.fn.setDecimalValue("VEH_RORO_TON_INI",gx.O.A39VEH_RORO_TON_INI,2,gx.decimalPoint)},c2v:function(){gx.O.A39VEH_RORO_TON_INI=this.val()},val:function(){return gx.fn.getDecimalValue("VEH_RORO_TON_INI",gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};a[31]={fld:"",grid:0};a[32]={fld:"",grid:0};a[33]={fld:"VEH_RORO_TON_FIN_CONTAINER",grid:0};a[34]={fld:"",format:0,grid:0};a[35]={fld:"",grid:0};a[36]={lvl:0,type:"decimal",len:10,dec:2,sign:false,pic:"ZZZZZZ9.99",ro:0,grid:0,gxgrid:null,
fnc:null,isvalid:null,rgrid:[],fld:"VEH_RORO_TON_FIN",gxz:"Z40VEH_RORO_TON_FIN",gxold:"O40VEH_RORO_TON_FIN",gxvar:"A40VEH_RORO_TON_FIN",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A40VEH_RORO_TON_FIN=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.Z40VEH_RORO_TON_FIN=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("VEH_RORO_TON_FIN",gx.O.A40VEH_RORO_TON_FIN,2,gx.decimalPoint)},c2v:function(){gx.O.A40VEH_RORO_TON_FIN=this.val()},
val:function(){return gx.fn.getDecimalValue("VEH_RORO_TON_FIN",gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};a[37]={fld:"",grid:0};a[38]={fld:"",grid:0};a[39]={fld:"VEH_RORO_UTIL_INI_CONTAINER",grid:0};a[40]={fld:"",format:0,grid:0};a[41]={fld:"",grid:0};a[42]={lvl:0,type:"decimal",len:10,dec:2,sign:false,pic:"ZZZZZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"VEH_RORO_UTIL_INI",gxz:"Z41VEH_RORO_UTIL_INI",gxold:"O41VEH_RORO_UTIL_INI",gxvar:"A41VEH_RORO_UTIL_INI",ucs:[],
op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A41VEH_RORO_UTIL_INI=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.Z41VEH_RORO_UTIL_INI=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("VEH_RORO_UTIL_INI",gx.O.A41VEH_RORO_UTIL_INI,2,gx.decimalPoint)},c2v:function(){gx.O.A41VEH_RORO_UTIL_INI=this.val()},val:function(){return gx.fn.getDecimalValue("VEH_RORO_UTIL_INI",gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};a[43]={fld:"",
grid:0};a[44]={fld:"",grid:0};a[45]={fld:"VEH_RORO_UTIL_FIN_CONTAINER",grid:0};a[46]={fld:"",format:0,grid:0};a[47]={fld:"",grid:0};a[48]={lvl:0,type:"decimal",len:10,dec:2,sign:false,pic:"ZZZZZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"VEH_RORO_UTIL_FIN",gxz:"Z42VEH_RORO_UTIL_FIN",gxold:"O42VEH_RORO_UTIL_FIN",gxvar:"A42VEH_RORO_UTIL_FIN",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A42VEH_RORO_UTIL_FIN=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.Z42VEH_RORO_UTIL_FIN=
gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("VEH_RORO_UTIL_FIN",gx.O.A42VEH_RORO_UTIL_FIN,2,gx.decimalPoint)},c2v:function(){gx.O.A42VEH_RORO_UTIL_FIN=this.val()},val:function(){return gx.fn.getDecimalValue("VEH_RORO_UTIL_FIN",gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};a[49]={fld:"",grid:0};a[50]={fld:"",grid:0};a[51]={fld:"VEH_RORO_TARIFA_CONTAINER",grid:0};a[52]={fld:"",format:0,grid:0};a[53]={fld:"",grid:0};a[54]={lvl:0,type:"decimal",
len:10,dec:2,sign:false,pic:"ZZZZZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"VEH_RORO_TARIFA",gxz:"Z43VEH_RORO_TARIFA",gxold:"O43VEH_RORO_TARIFA",gxvar:"A43VEH_RORO_TARIFA",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.A43VEH_RORO_TARIFA=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.Z43VEH_RORO_TARIFA=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("VEH_RORO_TARIFA",gx.O.A43VEH_RORO_TARIFA,2,gx.decimalPoint)},
c2v:function(){gx.O.A43VEH_RORO_TARIFA=this.val()},val:function(){return gx.fn.getDecimalValue("VEH_RORO_TARIFA",gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};a[55]={fld:"",grid:0};a[56]={fld:"",grid:0};a[57]={fld:"",grid:0};this.A43VEH_RORO_TARIFA=this.A42VEH_RORO_UTIL_FIN=this.A41VEH_RORO_UTIL_INI=this.A40VEH_RORO_TON_FIN=this.A39VEH_RORO_TON_INI=this.A38VEH_RORO_ID=this.O43VEH_RORO_TARIFA=this.Z43VEH_RORO_TARIFA=this.A43VEH_RORO_TARIFA=this.O42VEH_RORO_UTIL_FIN=this.Z42VEH_RORO_UTIL_FIN=
this.A42VEH_RORO_UTIL_FIN=this.O41VEH_RORO_UTIL_INI=this.Z41VEH_RORO_UTIL_INI=this.A41VEH_RORO_UTIL_INI=this.O40VEH_RORO_TON_FIN=this.Z40VEH_RORO_TON_FIN=this.A40VEH_RORO_TON_FIN=this.O39VEH_RORO_TON_INI=this.Z39VEH_RORO_TON_INI=this.A39VEH_RORO_TON_INI=this.O38VEH_RORO_ID=this.Z38VEH_RORO_ID=this.A38VEH_RORO_ID=0;this.Events={e11068_client:["ENTER",true],e12068_client:["CANCEL",true]};this.EvtParms.ENTER=[[{postForm:true}],[]];this.EvtParms.REFRESH=[[],[]];this.EnterCtrl=["BTN_ENTER"];this.setVCMap("Gx_mode",
"vMODE",0,"char");this.InitStandaloneVars()});gx.createParentObj(veh_roro);
