gx.evt.autoSkip=!1;
gx.define("wclpg",!1,function(){this.ServerClass="wclpg";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.skipOnEnter=this.hasEnterEvent=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){};this.e111b2_client=function(){this.executeServerEvent("'LIMPIAR'",false)};this.e121b2_client=function(){this.executeServerEvent("'CALCULAR'",false)};this.e151b2_client=function(){this.executeServerEvent("ENTER",true)};this.e161b2_client=
function(){this.executeServerEvent("CANCEL",true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,25,26,28,29,30,31,32,33,34,37,39,40,41,44,46,47,48,51,53,54,55,56,57,58,59,60,61];this.GXLastCtrlId=61;a[2]={fld:"",grid:0};a[3]={fld:"MAINTABLE",grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};a[6]={fld:"GROUPTANQUEROTITULO",grid:0};a[7]={fld:"GROUP1TABLE",grid:0};a[8]={fld:"",grid:0};a[9]={fld:"",grid:0};a[10]={fld:"GRIDTABLE",grid:0};a[11]={fld:"",grid:0};
a[12]={fld:"",grid:0};a[13]={fld:"LPGBANDAM3_CONTAINER",grid:0};a[14]={fld:"",format:0,grid:0};a[15]={fld:"",grid:0};a[16]={lvl:0,type:"int",len:12,dec:0,sign:false,pic:"ZZZ,ZZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vLPGBANDAM3",gxz:"ZV12LPGBandaM3",gxold:"OV12LPGBandaM3",gxvar:"AV12LPGBandaM3",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV12LPGBandaM3=gx.num.intval(a)},v2z:function(a){gx.O.ZV12LPGBandaM3=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vLPGBANDAM3",
gx.O.AV12LPGBandaM3,0)},c2v:function(){gx.O.AV12LPGBandaM3=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vLPGBANDAM3",gx.thousandSeparator)},nac:gx.falseFn};a[17]={fld:"",grid:0};a[18]={fld:"",grid:0};a[19]={fld:"TABLE3",grid:0};a[25]={fld:"",grid:0};a[26]={fld:"",grid:0};a[28]={fld:"",grid:0};a[29]={fld:"",grid:0};a[30]={fld:"GROUPTANQUERORESULTADO",grid:0};a[31]={fld:"GROUP3TABLE",grid:0};a[32]={fld:"",grid:0};a[33]={fld:"",grid:0};a[34]={fld:"TABLE4",grid:0};a[37]={fld:"TEXTBLOCKRESULTADOPANAMAX",
format:0,grid:0};a[39]={fld:"RESULTADOPANAMAX",format:0,grid:0};a[40]={fld:"",grid:0};a[41]={fld:"TABLE2",grid:0};a[44]={fld:"TEXTBLOCKRESULTADONEOPANAMAX",format:0,grid:0};a[46]={fld:"RESULTADONEOPANAMAX",format:0,grid:0};a[47]={fld:"",grid:0};a[48]={fld:"TABLE5",grid:0};a[51]={fld:"TEXTBLOCKRESULTADOLASTRE",format:0,grid:0};a[53]={fld:"RESULTADOLASTRE",format:0,grid:0};a[54]={fld:"",grid:0};a[55]={fld:"",grid:0};a[56]={fld:"TABLE1",grid:0};a[57]={fld:"",grid:0};a[58]={fld:"",grid:0};a[59]={fld:"TEXTBLOCK8",
format:0,grid:0};a[60]={fld:"",grid:0};a[61]={fld:"",grid:0};this.AV12LPGBandaM3=this.OV12LPGBandaM3=this.ZV12LPGBandaM3=this.AV12LPGBandaM3=0;this.AV10SdtResultado={};this.Events={e111b2_client:["'LIMPIAR'",true],e121b2_client:["'CALCULAR'",true],e151b2_client:["ENTER",true],e161b2_client:["CANCEL",true]};this.EvtParms.REFRESH=[[],[]];this.EvtParms["'LIMPIAR'"]=[[],[{av:"AV5TanqueroBandaCPSUAB",fld:"vTANQUEROBANDACPSUAB"},{av:"AV7ValorACalcular",fld:"vVALORACALCULAR"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAX","Caption")',
ctrl:"RESULTADOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAX","Caption")',ctrl:"RESULTADONEOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOLASTRE","Caption")',ctrl:"RESULTADOLASTRE",prop:"Caption"}]];this.EvtParms["'CALCULAR'"]=[[{av:"AV12LPGBandaM3",fld:"vLPGBANDAM3"},{av:"AV10SdtResultado",fld:"vSDTRESULTADO"}],[{av:"AV10SdtResultado",fld:"vSDTRESULTADO"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAX","Caption")',ctrl:"RESULTADOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAX","Caption")',
ctrl:"RESULTADONEOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOLASTRE","Caption")',ctrl:"RESULTADOLASTRE",prop:"Caption"}]];this.InitStandaloneVars();this.setComponent({id:"COMPONENT1",GXClass:"wcnota",Prefix:"W0062",lvl:1})});gx.createParentObj(wclpg);
