gx.evt.autoSkip=!1;
gx.define("wcpasajeros",!1,function(){this.ServerClass="wcpasajeros";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.skipOnEnter=this.hasEnterEvent=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){};this.e131i1_client=function(){this.clearMessages();this.AV9Relacion=this.AV5CPSUAB=this.AV8TRB=this.AV6PAXITC=0;gx.fn.setCtrlProperty("RESULTADOPANAMAXCARGADOCALCULO","Caption","$0.00");gx.fn.setCtrlProperty("RESULTADOPANAMAXLASTRECALCULO","Caption",
"$0.00");gx.fn.setCtrlProperty("RESULTADONEOPANAMAXCARGADOCALCULO","Caption","$0.00");gx.fn.setCtrlProperty("RESULTADONEOPANAMAXLASTRECALCULO","Caption","$0.00");this.refreshOutputs([{av:"AV6PAXITC",fld:"vPAXITC"},{av:"AV8TRB",fld:"vTRB"},{av:"AV5CPSUAB",fld:"vCPSUAB"},{av:"AV9Relacion",fld:"vRELACION"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXCARGADOCALCULO","Caption")',ctrl:"RESULTADOPANAMAXCARGADOCALCULO",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXLASTRECALCULO","Caption")',
ctrl:"RESULTADOPANAMAXLASTRECALCULO",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXCARGADOCALCULO","Caption")',ctrl:"RESULTADONEOPANAMAXCARGADOCALCULO",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXLASTRECALCULO","Caption")',ctrl:"RESULTADONEOPANAMAXLASTRECALCULO",prop:"Caption"}])};this.e111i2_client=function(){this.executeServerEvent("'CALCULAR'",false)};this.e141i2_client=function(){this.executeServerEvent("ENTER",true)};this.e151i2_client=function(){this.executeServerEvent("CANCEL",
true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,40,41,43,44,45,46,47,48,49,52,55,57,60,62,63,64,67,70,72,75,77,78,79];this.GXLastCtrlId=79;a[2]={fld:"",grid:0};a[3]={fld:"MAINTABLE",grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};a[6]={fld:"GROUP1",grid:0};a[7]={fld:"GROUP1TABLE",grid:0};a[8]={fld:"",grid:0};a[9]={fld:"",grid:0};a[10]={fld:"GRIDTABLE",grid:0};a[11]={fld:"",grid:0};a[12]={fld:"",grid:0};a[13]=
{fld:"CPSUAB_CONTAINER",grid:0};a[14]={fld:"",format:0,grid:0};a[15]={fld:"",grid:0};a[16]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"Z,ZZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vCPSUAB",gxz:"ZV5CPSUAB",gxold:"OV5CPSUAB",gxvar:"AV5CPSUAB",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV5CPSUAB=gx.num.intval(a)},v2z:function(a){gx.O.ZV5CPSUAB=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCPSUAB",gx.O.AV5CPSUAB,0)},c2v:function(){gx.O.AV5CPSUAB=
gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCPSUAB",gx.thousandSeparator)},nac:gx.falseFn};a[17]={fld:"",grid:0};a[18]={fld:"PAXITC_CONTAINER",grid:0};a[19]={fld:"",format:0,grid:0};a[20]={fld:"",grid:0};a[21]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"Z,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vPAXITC",gxz:"ZV6PAXITC",gxold:"OV6PAXITC",gxvar:"AV6PAXITC",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV6PAXITC=gx.num.intval(a)},
v2z:function(a){gx.O.ZV6PAXITC=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vPAXITC",gx.O.AV6PAXITC,0)},c2v:function(){gx.O.AV6PAXITC=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vPAXITC",gx.thousandSeparator)},nac:gx.falseFn};a[22]={fld:"",grid:0};a[23]={fld:"RELACION_CONTAINER",grid:0};a[24]={fld:"",format:0,grid:0};a[25]={fld:"",grid:0};a[26]={lvl:0,type:"decimal",len:10,dec:2,sign:false,pic:"ZZZZZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],
fld:"vRELACION",gxz:"ZV9Relacion",gxold:"OV9Relacion",gxvar:"AV9Relacion",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV9Relacion=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.ZV9Relacion=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("vRELACION",gx.O.AV9Relacion,2,gx.decimalPoint)},c2v:function(){gx.O.AV9Relacion=this.val()},val:function(){return gx.fn.getDecimalValue("vRELACION",gx.thousandSeparator,gx.decimalPoint)},
nac:gx.falseFn};a[27]={fld:"",grid:0};a[28]={fld:"TRB_CONTAINER",grid:0};a[29]={fld:"",format:0,grid:0};a[30]={fld:"",grid:0};a[31]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"Z,ZZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vTRB",gxz:"ZV8TRB",gxold:"OV8TRB",gxvar:"AV8TRB",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV8TRB=gx.num.intval(a)},v2z:function(a){gx.O.ZV8TRB=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vTRB",gx.O.AV8TRB,0)},c2v:function(){gx.O.AV8TRB=
gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vTRB",gx.thousandSeparator)},nac:gx.falseFn};a[32]={fld:"",grid:0};a[33]={fld:"",grid:0};a[34]={fld:"TABLE3",grid:0};a[40]={fld:"",grid:0};a[41]={fld:"",grid:0};a[43]={fld:"",grid:0};a[44]={fld:"",grid:0};a[45]={fld:"GROUP2",grid:0};a[46]={fld:"GROUP2TABLE",grid:0};a[47]={fld:"",grid:0};a[48]={fld:"",grid:0};a[49]={fld:"TABLEPANAMAX",grid:0};a[52]={fld:"PANAMAX",format:0,grid:0};a[55]={fld:"RESULTADOPANAMAXCARGADOTEXTO",format:0,
grid:0};a[57]={fld:"RESULTADOPANAMAXCARGADOCALCULO",format:0,grid:0};a[60]={fld:"RESULTADOPANAMAXLASTRETEXTO",format:0,grid:0};a[62]={fld:"RESULTADOPANAMAXLASTRECALCULO",format:0,grid:0};a[63]={fld:"",grid:0};a[64]={fld:"TABLENEOPANAMAX",grid:0};a[67]={fld:"NEOPANAMAX",format:0,grid:0};a[70]={fld:"RESULTADONEOPANAMAXCARGADOTEXTO",format:0,grid:0};a[72]={fld:"RESULTADONEOPANAMAXCARGADOCALCULO",format:0,grid:0};a[75]={fld:"RESULTADONEOPANAMAXLASTRETEXTO",format:0,grid:0};a[77]={fld:"RESULTADONEOPANAMAXLASTRECALCULO",
format:0,grid:0};a[78]={fld:"",grid:0};a[79]={fld:"",grid:0};this.AV8TRB=this.AV9Relacion=this.AV6PAXITC=this.AV5CPSUAB=this.OV8TRB=this.ZV8TRB=this.AV8TRB=this.OV9Relacion=this.ZV9Relacion=this.AV9Relacion=this.OV6PAXITC=this.ZV6PAXITC=this.AV6PAXITC=this.OV5CPSUAB=this.ZV5CPSUAB=this.AV5CPSUAB=0;this.AV7SdtResultado={};this.Events={e111i2_client:["'CALCULAR'",true],e141i2_client:["ENTER",true],e151i2_client:["CANCEL",true],e131i1_client:["'LIMPIAR'",false]};this.EvtParms.REFRESH=[[],[]];this.EvtParms["'LIMPIAR'"]=
[[],[{av:"AV6PAXITC",fld:"vPAXITC"},{av:"AV8TRB",fld:"vTRB"},{av:"AV5CPSUAB",fld:"vCPSUAB"},{av:"AV9Relacion",fld:"vRELACION"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXCARGADOCALCULO","Caption")',ctrl:"RESULTADOPANAMAXCARGADOCALCULO",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXLASTRECALCULO","Caption")',ctrl:"RESULTADOPANAMAXLASTRECALCULO",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXCARGADOCALCULO","Caption")',ctrl:"RESULTADONEOPANAMAXCARGADOCALCULO",prop:"Caption"},
{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXLASTRECALCULO","Caption")',ctrl:"RESULTADONEOPANAMAXLASTRECALCULO",prop:"Caption"}]];this.EvtParms["'CALCULAR'"]=[[{av:"AV6PAXITC",fld:"vPAXITC"},{av:"AV8TRB",fld:"vTRB"},{av:"AV5CPSUAB",fld:"vCPSUAB"},{av:"AV7SdtResultado",fld:"vSDTRESULTADO"}],[{av:"AV9Relacion",fld:"vRELACION"},{av:"AV7SdtResultado",fld:"vSDTRESULTADO"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXCARGADOCALCULO","Caption")',ctrl:"RESULTADOPANAMAXCARGADOCALCULO",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXLASTRECALCULO","Caption")',
ctrl:"RESULTADOPANAMAXLASTRECALCULO",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXCARGADOCALCULO","Caption")',ctrl:"RESULTADONEOPANAMAXCARGADOCALCULO",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXLASTRECALCULO","Caption")',ctrl:"RESULTADONEOPANAMAXLASTRECALCULO",prop:"Caption"}]];this.InitStandaloneVars();this.setComponent({id:"COMPONENT1",GXClass:"wcnota",Prefix:"W0080",lvl:1})});gx.createParentObj(wcpasajeros);
