gx.evt.autoSkip=!1;
gx.define("wcportacontenedores",!1,function(){this.ServerClass="wcportacontenedores";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.hasEnterEvent=true;this.skipOnEnter=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){};this.Validv_Capacidaddecontenedores=function(){try{var a=gx.util.balloon.getNew("vCAPACIDADDECONTENEDORES");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};this.Validv_Cargateu=
function(){gx.ajax.validSrvEvt("dyncall","Validv_Cargateu",["gx.O.AV9CargaTEU","gx.O.AV5CapacidadDeContenedores","gx.num.urlDecimal(gx.O.AV6PorcentajeDeCarga,gx.thousandSeparator,gx.decimalPoint)"],["AV6PorcentajeDeCarga"]);return true};this.e150a1_client=function(){this.clearMessages();this.s112_client();this.refreshOutputs([{av:"AV9CargaTEU",fld:"vCARGATEU"},{av:"AV5CapacidadDeContenedores",fld:"vCAPACIDADDECONTENEDORES"},{av:"AV6PorcentajeDeCarga",fld:"vPORCENTAJEDECARGA"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAX","Caption")',
ctrl:"RESULTADOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAX","Caption")',ctrl:"RESULTADONEOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXC3","Caption")',ctrl:"RESULTADOPANAMAXC3",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXC3","Caption")',ctrl:"RESULTADONEOPANAMAXC3",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXC2","Caption")',ctrl:"RESULTADOPANAMAXC2",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXC2","Caption")',
ctrl:"RESULTADONEOPANAMAXC2",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXC1","Caption")',ctrl:"RESULTADOPANAMAXC1",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXC1","Caption")',ctrl:"RESULTADONEOPANAMAXC1",prop:"Caption"}])};this.s112_client=function(){this.AV6PorcentajeDeCarga=this.AV5CapacidadDeContenedores=this.AV9CargaTEU=0;gx.fn.setCtrlProperty("RESULTADOPANAMAX","Caption",gx.text.format("%1","$0.00","","","","","","","",""));gx.fn.setCtrlProperty("RESULTADONEOPANAMAX",
"Caption",gx.text.format("%1","$0.00","","","","","","","",""));gx.fn.setCtrlProperty("RESULTADOPANAMAXC3","Caption",gx.text.format("%1","$0.00","","","","","","","",""));gx.fn.setCtrlProperty("RESULTADONEOPANAMAXC3","Caption",gx.text.format("%1","$0.00","","","","","","","",""));gx.fn.setCtrlProperty("RESULTADOPANAMAXC2","Caption",gx.text.format("%1","$0.00","","","","","","","",""));gx.fn.setCtrlProperty("RESULTADONEOPANAMAXC2","Caption",gx.text.format("%1","$0.00","","","","","","","",""));gx.fn.setCtrlProperty("RESULTADOPANAMAXC1",
"Caption",gx.text.format("%1","$0.00","","","","","","","",""));gx.fn.setCtrlProperty("RESULTADONEOPANAMAXC1","Caption",gx.text.format("%1","$0.00","","","","","","","",""))};this.e110a2_client=function(){this.executeServerEvent("ENTER",true)};this.e120a2_client=function(){this.executeServerEvent("'CALCULAR'",false)};this.e160a2_client=function(){this.executeServerEvent("CANCEL",true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,
29,35,36,38,39,40,41,42,43,44,45,46,47,50,52,53,54,57,59,60,61,62,63,64,65,69,71,72,73,77,79,80,81,82,83,84,85,89,91,92,93,97,99,100,101,102,103,104,105,109,111,112,113,117,119,120,121];this.GXLastCtrlId=121;a[2]={fld:"",grid:0};a[3]={fld:"MAINTABLE",grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};a[6]={fld:"GROUP1",grid:0};a[7]={fld:"GROUP1TABLE",grid:0};a[8]={fld:"",grid:0};a[9]={fld:"",grid:0};a[10]={fld:"GRIDTABLE",grid:0};a[11]={fld:"",grid:0};a[12]={fld:"",grid:0};a[13]={fld:"CAPACIDADDECONTENEDORES_CONTAINER",
grid:0};a[14]={fld:"",format:0,grid:0};a[15]={fld:"",grid:0};a[16]={lvl:0,type:"int",len:6,dec:0,sign:false,pic:"ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Validv_Capacidaddecontenedores,isvalid:null,rgrid:[],fld:"vCAPACIDADDECONTENEDORES",gxz:"ZV5CapacidadDeContenedores",gxold:"OV5CapacidadDeContenedores",gxvar:"AV5CapacidadDeContenedores",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV5CapacidadDeContenedores=gx.num.intval(a)},v2z:function(a){gx.O.ZV5CapacidadDeContenedores=
gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCAPACIDADDECONTENEDORES",gx.O.AV5CapacidadDeContenedores,0)},c2v:function(){gx.O.AV5CapacidadDeContenedores=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCAPACIDADDECONTENEDORES",gx.thousandSeparator)},nac:gx.falseFn};a[17]={fld:"",grid:0};a[18]={fld:"CARGATEU_CONTAINER",grid:0};a[19]={fld:"",format:0,grid:0};a[20]={fld:"",grid:0};a[21]={lvl:0,type:"int",len:6,dec:0,sign:false,pic:"ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,
fnc:this.Validv_Cargateu,isvalid:null,rgrid:[],fld:"vCARGATEU",gxz:"ZV9CargaTEU",gxold:"OV9CargaTEU",gxvar:"AV9CargaTEU",ucs:[],op:[26],ip:[26,16,21],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV9CargaTEU=gx.num.intval(a)},v2z:function(a){gx.O.ZV9CargaTEU=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCARGATEU",gx.O.AV9CargaTEU,0)},c2v:function(){gx.O.AV9CargaTEU=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCARGATEU",gx.thousandSeparator)},nac:gx.falseFn};
a[22]={fld:"",grid:0};a[23]={fld:"PORCENTAJEDECARGA_CONTAINER",grid:0};a[24]={fld:"",format:0,grid:0};a[25]={fld:"",grid:0};a[26]={lvl:0,type:"decimal",len:6,dec:2,sign:false,pic:"ZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vPORCENTAJEDECARGA",gxz:"ZV6PorcentajeDeCarga",gxold:"OV6PorcentajeDeCarga",gxvar:"AV6PorcentajeDeCarga",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV6PorcentajeDeCarga=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.ZV6PorcentajeDeCarga=
gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("vPORCENTAJEDECARGA",gx.O.AV6PorcentajeDeCarga,2,gx.decimalPoint)},c2v:function(){gx.O.AV6PorcentajeDeCarga=this.val()},val:function(){return gx.fn.getDecimalValue("vPORCENTAJEDECARGA",gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};a[27]={fld:"",grid:0};a[28]={fld:"",grid:0};a[29]={fld:"TABLE3",grid:0};a[35]={fld:"",grid:0};a[36]={fld:"",grid:0};a[38]={fld:"",grid:0};a[39]={fld:"",grid:0};a[40]=
{fld:"GROUPTANQUERORESULTADO",grid:0};a[41]={fld:"GROUPTANQUERORESULTADOTABLE",grid:0};a[42]={fld:"",grid:0};a[43]={fld:"",grid:0};a[44]={fld:"TEXTBLOCK1",format:0,grid:0};a[45]={fld:"",grid:0};a[46]={fld:"",grid:0};a[47]={fld:"TABLE1",grid:0};a[50]={fld:"TEXTBLOCKRESULTADOPANAMAX",format:0,grid:0};a[52]={fld:"RESULTADOPANAMAX",format:0,grid:0};a[53]={fld:"",grid:0};a[54]={fld:"TABLE2",grid:0};a[57]={fld:"TEXTBLOCKRESULTADONEOPANAMAX",format:0,grid:0};a[59]={fld:"RESULTADONEOPANAMAX",format:0,grid:0};
a[60]={fld:"",grid:0};a[61]={fld:"",grid:0};a[62]={fld:"TEXTBLOCK2",format:0,grid:0};a[63]={fld:"",grid:0};a[64]={fld:"",grid:0};a[65]={fld:"TABLE4",grid:0};a[69]={fld:"TEXTBLOCKRESULTADOPANAMAXC3",format:0,grid:0};a[71]={fld:"RESULTADOPANAMAXC3",format:0,grid:0};a[72]={fld:"",grid:0};a[73]={fld:"TABLE5",grid:0};a[77]={fld:"TEXTBLOCKRESULTADONEOPANAMAXC3",format:0,grid:0};a[79]={fld:"RESULTADONEOPANAMAXC3",format:0,grid:0};a[80]={fld:"",grid:0};a[81]={fld:"",grid:0};a[82]={fld:"TEXTBLOCK3",format:0,
grid:0};a[83]={fld:"",grid:0};a[84]={fld:"",grid:0};a[85]={fld:"TABLE6",grid:0};a[89]={fld:"TEXTBLOCKRESULTADOPANAMAXC2",format:0,grid:0};a[91]={fld:"RESULTADOPANAMAXC2",format:0,grid:0};a[92]={fld:"",grid:0};a[93]={fld:"TABLE7",grid:0};a[97]={fld:"TEXTBLOCKRESULTADONEOPANAMAXC2",format:0,grid:0};a[99]={fld:"RESULTADONEOPANAMAXC2",format:0,grid:0};a[100]={fld:"",grid:0};a[101]={fld:"",grid:0};a[102]={fld:"TEXTBLOCK4",format:0,grid:0};a[103]={fld:"",grid:0};a[104]={fld:"",grid:0};a[105]={fld:"TABLE8",
grid:0};a[109]={fld:"TEXTBLOCKRESULTADOPANAMAXC1",format:0,grid:0};a[111]={fld:"RESULTADOPANAMAXC1",format:0,grid:0};a[112]={fld:"",grid:0};a[113]={fld:"TABLE9",grid:0};a[117]={fld:"TEXTBLOCKRESULTADONEOPANAMAXC1",format:0,grid:0};a[119]={fld:"RESULTADONEOPANAMAXC1",format:0,grid:0};a[120]={fld:"",grid:0};a[121]={fld:"",grid:0};this.AV6PorcentajeDeCarga=this.AV9CargaTEU=this.AV5CapacidadDeContenedores=this.OV6PorcentajeDeCarga=this.ZV6PorcentajeDeCarga=this.AV6PorcentajeDeCarga=this.OV9CargaTEU=this.ZV9CargaTEU=
this.AV9CargaTEU=this.OV5CapacidadDeContenedores=this.ZV5CapacidadDeContenedores=this.AV5CapacidadDeContenedores=0;this.AV10SdtResultado={};this.Events={e110a2_client:["ENTER",true],e120a2_client:["'CALCULAR'",true],e160a2_client:["CANCEL",true],e150a1_client:["'LIMPIAR'",false],s112_client:["'LIMPIARCALCULOS'",false]};this.EvtParms.REFRESH=[[],[]];this.EvtParms["'LIMPIAR'"]=[[],[{av:"AV9CargaTEU",fld:"vCARGATEU"},{av:"AV5CapacidadDeContenedores",fld:"vCAPACIDADDECONTENEDORES"},{av:"AV6PorcentajeDeCarga",
fld:"vPORCENTAJEDECARGA"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAX","Caption")',ctrl:"RESULTADOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAX","Caption")',ctrl:"RESULTADONEOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXC3","Caption")',ctrl:"RESULTADOPANAMAXC3",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXC3","Caption")',ctrl:"RESULTADONEOPANAMAXC3",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXC2","Caption")',ctrl:"RESULTADOPANAMAXC2",
prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXC2","Caption")',ctrl:"RESULTADONEOPANAMAXC2",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXC1","Caption")',ctrl:"RESULTADOPANAMAXC1",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXC1","Caption")',ctrl:"RESULTADONEOPANAMAXC1",prop:"Caption"}]];this.EvtParms.ENTER=[[],[]];this.EvtParms["'CALCULAR'"]=[[{av:"AV5CapacidadDeContenedores",fld:"vCAPACIDADDECONTENEDORES"},{av:"AV9CargaTEU",fld:"vCARGATEU"},{av:"AV10SdtResultado",
fld:"vSDTRESULTADO"}],[{av:"AV10SdtResultado",fld:"vSDTRESULTADO"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAX","Caption")',ctrl:"RESULTADOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAX","Caption")',ctrl:"RESULTADONEOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXC3","Caption")',ctrl:"RESULTADOPANAMAXC3",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXC3","Caption")',ctrl:"RESULTADONEOPANAMAXC3",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXC2","Caption")',
ctrl:"RESULTADOPANAMAXC2",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXC2","Caption")',ctrl:"RESULTADONEOPANAMAXC2",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAXC1","Caption")',ctrl:"RESULTADOPANAMAXC1",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAXC1","Caption")',ctrl:"RESULTADONEOPANAMAXC1",prop:"Caption"},{av:"AV9CargaTEU",fld:"vCARGATEU"},{av:"AV5CapacidadDeContenedores",fld:"vCAPACIDADDECONTENEDORES"},{av:"AV6PorcentajeDeCarga",fld:"vPORCENTAJEDECARGA"}]];
this.InitStandaloneVars();this.setComponent({id:"COMPONENT1",GXClass:"wcnota",Prefix:"W0122",lvl:1})});gx.createParentObj(wcportacontenedores);
