gx.evt.autoSkip=!1;
gx.define("wcportavehiculosroro",!1,function(){this.ServerClass="wcportavehiculosroro";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.skipOnEnter=this.hasEnterEvent=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){};this.Validv_Tm=function(){try{var a=gx.util.balloon.getNew("vTM");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};this.Validv_Dwt=function(){gx.ajax.validSrvEvt("dyncall","Validv_Dwt",
["gx.O.AV10TM","gx.O.AV8DWT","gx.num.urlDecimal(gx.O.AV7Utilizacion,gx.thousandSeparator,gx.decimalPoint)"],["AV7Utilizacion"]);return true};this.e13171_client=function(){this.clearMessages();this.AV7Utilizacion=this.AV8DWT=this.AV10TM=this.AV6Tonelaje=0;gx.fn.setCtrlProperty("RESULTADOCALCULO","Caption","$0.00");this.refreshOutputs([{av:"AV6Tonelaje",fld:"vTONELAJE"},{av:"AV10TM",fld:"vTM"},{av:"AV8DWT",fld:"vDWT"},{av:"AV7Utilizacion",fld:"vUTILIZACION"},{av:'gx.fn.getCtrlProperty("RESULTADOCALCULO","Caption")',
ctrl:"RESULTADOCALCULO",prop:"Caption"}])};this.e11172_client=function(){this.executeServerEvent("'CALCULAR'",false)};this.e14172_client=function(){this.executeServerEvent("ENTER",true)};this.e15172_client=function(){this.executeServerEvent("CANCEL",true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,40,41,43,44,45,46,47,48,49,52,54,55,56];this.GXLastCtrlId=56;a[2]={fld:"",grid:0};a[3]={fld:"MAINTABLE",grid:0};
a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};a[6]={fld:"GROUP1",grid:0};a[7]={fld:"GROUP1TABLE",grid:0};a[8]={fld:"",grid:0};a[9]={fld:"",grid:0};a[10]={fld:"GRIDTABLE",grid:0};a[11]={fld:"",grid:0};a[12]={fld:"",grid:0};a[13]={fld:"TONELAJE_CONTAINER",grid:0};a[14]={fld:"",format:0,grid:0};a[15]={fld:"",grid:0};a[16]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"Z,ZZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vTONELAJE",gxz:"ZV6Tonelaje",gxold:"OV6Tonelaje",gxvar:"AV6Tonelaje",
ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV6Tonelaje=gx.num.intval(a)},v2z:function(a){gx.O.ZV6Tonelaje=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vTONELAJE",gx.O.AV6Tonelaje,0)},c2v:function(){gx.O.AV6Tonelaje=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vTONELAJE",gx.thousandSeparator)},nac:gx.falseFn};a[17]={fld:"",grid:0};a[18]={fld:"TM_CONTAINER",grid:0};a[19]={fld:"",format:0,grid:0};a[20]={fld:"",grid:0};a[21]={lvl:0,type:"int",
len:10,dec:0,sign:false,pic:"Z,ZZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Validv_Tm,isvalid:null,rgrid:[],fld:"vTM",gxz:"ZV10TM",gxold:"OV10TM",gxvar:"AV10TM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV10TM=gx.num.intval(a)},v2z:function(a){gx.O.ZV10TM=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vTM",gx.O.AV10TM,0)},c2v:function(){gx.O.AV10TM=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vTM",gx.thousandSeparator)},nac:gx.falseFn};
a[22]={fld:"",grid:0};a[23]={fld:"DWT_CONTAINER",grid:0};a[24]={fld:"",format:0,grid:0};a[25]={fld:"",grid:0};a[26]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"Z,ZZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Validv_Dwt,isvalid:null,rgrid:[],fld:"vDWT",gxz:"ZV8DWT",gxold:"OV8DWT",gxvar:"AV8DWT",ucs:[],op:[31],ip:[31,26,21],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV8DWT=gx.num.intval(a)},v2z:function(a){gx.O.ZV8DWT=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vDWT",gx.O.AV8DWT,
0)},c2v:function(){gx.O.AV8DWT=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vDWT",gx.thousandSeparator)},nac:gx.falseFn};a[27]={fld:"",grid:0};a[28]={fld:"UTILIZACION_CONTAINER",grid:0};a[29]={fld:"",format:0,grid:0};a[30]={fld:"",grid:0};a[31]={lvl:0,type:"decimal",len:10,dec:2,sign:false,pic:"Z,ZZZ,ZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vUTILIZACION",gxz:"ZV7Utilizacion",gxold:"OV7Utilizacion",gxvar:"AV7Utilizacion",ucs:[],op:[],ip:[],nacdep:[],
ctrltype:"edit",v2v:function(a){gx.O.AV7Utilizacion=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.ZV7Utilizacion=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("vUTILIZACION",gx.O.AV7Utilizacion,2,gx.decimalPoint)},c2v:function(){gx.O.AV7Utilizacion=this.val()},val:function(){return gx.fn.getDecimalValue("vUTILIZACION",gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};a[32]={fld:"",grid:0};a[33]={fld:"",grid:0};a[34]={fld:"TABLE3",grid:0};
a[40]={fld:"",grid:0};a[41]={fld:"",grid:0};a[43]={fld:"",grid:0};a[44]={fld:"",grid:0};a[45]={fld:"GROUP2",grid:0};a[46]={fld:"GROUP2TABLE",grid:0};a[47]={fld:"",grid:0};a[48]={fld:"",grid:0};a[49]={fld:"TABLE1",grid:0};a[52]={fld:"RESULTADOTEXTO",format:0,grid:0};a[54]={fld:"RESULTADOCALCULO",format:0,grid:0};a[55]={fld:"",grid:0};a[56]={fld:"",grid:0};this.AV7Utilizacion=this.AV8DWT=this.AV10TM=this.AV6Tonelaje=this.OV7Utilizacion=this.ZV7Utilizacion=this.AV7Utilizacion=this.OV8DWT=this.ZV8DWT=
this.AV8DWT=this.OV10TM=this.ZV10TM=this.AV10TM=this.OV6Tonelaje=this.ZV6Tonelaje=this.AV6Tonelaje=0;this.AV9SdtResultado={};this.Events={e11172_client:["'CALCULAR'",true],e14172_client:["ENTER",true],e15172_client:["CANCEL",true],e13171_client:["'LIMPIAR'",false]};this.EvtParms.REFRESH=[[],[]];this.EvtParms["'LIMPIAR'"]=[[],[{av:"AV6Tonelaje",fld:"vTONELAJE"},{av:"AV10TM",fld:"vTM"},{av:"AV8DWT",fld:"vDWT"},{av:"AV7Utilizacion",fld:"vUTILIZACION"},{av:'gx.fn.getCtrlProperty("RESULTADOCALCULO","Caption")',
ctrl:"RESULTADOCALCULO",prop:"Caption"}]];this.EvtParms["'CALCULAR'"]=[[{av:"AV10TM",fld:"vTM"},{av:"AV8DWT",fld:"vDWT"},{av:"AV6Tonelaje",fld:"vTONELAJE"},{av:"AV7Utilizacion",fld:"vUTILIZACION"},{av:"AV9SdtResultado",fld:"vSDTRESULTADO"}],[{av:"AV7Utilizacion",fld:"vUTILIZACION"},{av:"AV9SdtResultado",fld:"vSDTRESULTADO"},{av:'gx.fn.getCtrlProperty("RESULTADOCALCULO","Caption")',ctrl:"RESULTADOCALCULO",prop:"Caption"}]];this.InitStandaloneVars();this.setComponent({id:"COMPONENT1",GXClass:"wcnota",
Prefix:"W0057",lvl:1})});gx.createParentObj(wcportavehiculosroro);
