gx.evt.autoSkip=!1;
gx.define("wcquimiqueros",!1,function(){this.ServerClass="wcquimiqueros";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.skipOnEnter=this.hasEnterEvent=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){};this.Validv_Dominioquimiquerostipo=function(){try{var a=gx.util.balloon.getNew("vDOMINIOQUIMIQUEROSTIPO");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};this.Validv_Dominioimo=
function(){try{var a=gx.util.balloon.getNew("vDOMINIOIMO");this.AnyError=0;if(!(this.AV12DominioIMO=="Ninguno"||this.AV12DominioIMO=="Clase 1"||this.AV12DominioIMO=="Otros"))try{a.setError(gx.text.format(gx.getMessage("GXSPC_OutOfRange"),gx.getMessage("DominioIMO"),"","","","","","","",""));this.AnyError=1}catch(b){}}catch(c){}try{return a==null?true:a.show()}catch(d){}return true};this.e11161_client=function(){this.clearMessages();if(this.AV13DominioQuimiquerosTipo==1){this.AV12DominioIMO="Ninguno";
gx.fn.setCtrlProperty("vDOMINIOIMO","Enabled",false)}else gx.fn.setCtrlProperty("vDOMINIOIMO","Enabled",true);this.refreshOutputs([{av:"AV12DominioIMO",fld:"vDOMINIOIMO"},{ctrl:"vDOMINIOIMO"}])};this.e12162_client=function(){this.executeServerEvent("'LIMPIAR'",false)};this.e13162_client=function(){this.executeServerEvent("'CALCULAR'",false)};this.e16162_client=function(){this.executeServerEvent("ENTER",true)};this.e17162_client=function(){this.executeServerEvent("CANCEL",true)};var a=this.GXValidFnc=
[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,35,36,38,39,40,41,42,43,44,45,46,47,48,49,50,53,55,56,57,60,62,63,64,67,69,70,71];this.GXLastCtrlId=71;a[2]={fld:"",grid:0};a[3]={fld:"MAINTABLE",grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};a[6]={fld:"GROUPTANQUEROTITULO",grid:0};a[7]={fld:"GROUP1TABLE",grid:0};a[8]={fld:"",grid:0};a[9]={fld:"",grid:0};a[10]={fld:"GRIDTABLE",grid:0};a[11]={fld:"",grid:0};a[12]={fld:"",grid:0};a[13]={fld:"TANQUEROBANDACPSUAB_CONTAINER",
grid:0};a[14]={fld:"",format:0,grid:0};a[15]={fld:"",grid:0};a[16]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"Z,ZZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vTANQUEROBANDACPSUAB",gxz:"ZV5TanqueroBandaCPSUAB",gxold:"OV5TanqueroBandaCPSUAB",gxvar:"AV5TanqueroBandaCPSUAB",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV5TanqueroBandaCPSUAB=gx.num.intval(a)},v2z:function(a){gx.O.ZV5TanqueroBandaCPSUAB=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vTANQUEROBANDACPSUAB",
gx.O.AV5TanqueroBandaCPSUAB,0)},c2v:function(){gx.O.AV5TanqueroBandaCPSUAB=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vTANQUEROBANDACPSUAB",gx.thousandSeparator)},nac:gx.falseFn};a[17]={fld:"",grid:0};a[18]={fld:"DOMINIOQUIMIQUEROSTIPO_CONTAINER",grid:0};a[19]={fld:"",format:0,grid:0};a[20]={fld:"",grid:0};a[21]={lvl:0,type:"int",len:4,dec:0,sign:false,pic:"ZZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Validv_Dominioquimiquerostipo,isvalid:null,rgrid:[],fld:"vDOMINIOQUIMIQUEROSTIPO",
gxz:"ZV13DominioQuimiquerosTipo",gxold:"OV13DominioQuimiquerosTipo",gxvar:"AV13DominioQuimiquerosTipo",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",v2v:function(a){gx.O.AV13DominioQuimiquerosTipo=gx.num.intval(a)},v2z:function(a){gx.O.ZV13DominioQuimiquerosTipo=gx.num.intval(a)},v2c:function(){gx.fn.setComboBoxValue("vDOMINIOQUIMIQUEROSTIPO",gx.O.AV13DominioQuimiquerosTipo);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV13DominioQuimiquerosTipo=gx.num.intval(this.val())},
val:function(){return gx.fn.getIntegerValue("vDOMINIOQUIMIQUEROSTIPO",gx.thousandSeparator)},nac:gx.falseFn};this.declareDomainHdlr(21,function(){});a[22]={fld:"",grid:0};a[23]={fld:"DOMINIOIMO_CONTAINER",grid:0};a[24]={fld:"",format:0,grid:0};a[25]={fld:"",grid:0};a[26]={lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:this.Validv_Dominioimo,isvalid:null,fld:"vDOMINIOIMO",gxz:"ZV12DominioIMO",gxold:"OV12DominioIMO",gxvar:"AV12DominioIMO",ucs:[],op:[26],ip:[26],nacdep:[],ctrltype:"combo",
v2v:function(a){gx.O.AV12DominioIMO=a},v2z:function(a){gx.O.ZV12DominioIMO=a},v2c:function(){gx.fn.setComboBoxValue("vDOMINIOIMO",gx.O.AV12DominioIMO);typeof this.dom_hdl=="function"&&this.dom_hdl.call(gx.O)},c2v:function(){gx.O.AV12DominioIMO=this.val()},val:function(){return gx.fn.getControlValue("vDOMINIOIMO")},nac:gx.falseFn};this.declareDomainHdlr(26,function(){});a[27]={fld:"",grid:0};a[28]={fld:"",grid:0};a[29]={fld:"TABLE3",grid:0};a[35]={fld:"",grid:0};a[36]={fld:"",grid:0};a[38]={fld:"",
grid:0};a[39]={fld:"",grid:0};a[40]={fld:"TABLE5",grid:0};a[41]={fld:"",grid:0};a[42]={fld:"",grid:0};a[43]={fld:"TEXTBLOCK8",format:0,grid:0};a[44]={fld:"",grid:0};a[45]={fld:"",grid:0};a[46]={fld:"GROUPTANQUERORESULTADO",grid:0};a[47]={fld:"GROUP3TABLE",grid:0};a[48]={fld:"",grid:0};a[49]={fld:"",grid:0};a[50]={fld:"TABLE4",grid:0};a[53]={fld:"TEXTBLOCKRESULTADOPANAMAX",format:0,grid:0};a[55]={fld:"RESULTADOPANAMAX",format:0,grid:0};a[56]={fld:"",grid:0};a[57]={fld:"TABLE1",grid:0};a[60]={fld:"TEXTBLOCKRESULTADONEOPANAMAX",
format:0,grid:0};a[62]={fld:"RESULTADONEOPANAMAX",format:0,grid:0};a[63]={fld:"",grid:0};a[64]={fld:"TABLE2",grid:0};a[67]={fld:"TEXTBLOCKRESULTADOLASTRE",format:0,grid:0};a[69]={fld:"RESULTADOLASTRE",format:0,grid:0};a[70]={fld:"",grid:0};a[71]={fld:"",grid:0};this.OV13DominioQuimiquerosTipo=this.ZV13DominioQuimiquerosTipo=this.AV13DominioQuimiquerosTipo=this.OV5TanqueroBandaCPSUAB=this.ZV5TanqueroBandaCPSUAB=this.AV5TanqueroBandaCPSUAB=0;this.OV12DominioIMO=this.ZV12DominioIMO=this.AV12DominioIMO=
"";this.AV13DominioQuimiquerosTipo=this.AV5TanqueroBandaCPSUAB=0;this.AV12DominioIMO="";this.AV11SdtResultado={};this.Events={e12162_client:["'LIMPIAR'",true],e13162_client:["'CALCULAR'",true],e16162_client:["ENTER",true],e17162_client:["CANCEL",true],e11161_client:["VDOMINIOQUIMIQUEROSTIPO.CLICK",false]};this.EvtParms.REFRESH=[[],[]];this.EvtParms["'LIMPIAR'"]=[[],[{av:"AV5TanqueroBandaCPSUAB",fld:"vTANQUEROBANDACPSUAB"},{av:"AV7ValorACalcular",fld:"vVALORACALCULAR"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAX","Caption")',
ctrl:"RESULTADOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAX","Caption")',ctrl:"RESULTADONEOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOLASTRE","Caption")',ctrl:"RESULTADOLASTRE",prop:"Caption"}]];this.EvtParms["'CALCULAR'"]=[[{av:"AV5TanqueroBandaCPSUAB",fld:"vTANQUEROBANDACPSUAB"},{av:"AV12DominioIMO",fld:"vDOMINIOIMO"},{av:"AV11SdtResultado",fld:"vSDTRESULTADO"},{av:"AV13DominioQuimiquerosTipo",fld:"vDOMINIOQUIMIQUEROSTIPO"}],[{av:"AV11SdtResultado",
fld:"vSDTRESULTADO"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAX","Caption")',ctrl:"RESULTADOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAX","Caption")',ctrl:"RESULTADONEOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOLASTRE","Caption")',ctrl:"RESULTADOLASTRE",prop:"Caption"}]];this.EvtParms["VDOMINIOQUIMIQUEROSTIPO.CLICK"]=[[{av:"AV13DominioQuimiquerosTipo",fld:"vDOMINIOQUIMIQUEROSTIPO"}],[{av:"AV12DominioIMO",fld:"vDOMINIOIMO"},{ctrl:"vDOMINIOIMO"}]];this.InitStandaloneVars();
this.setComponent({id:"COMPONENT1",GXClass:"wcnota",Prefix:"W0072",lvl:1})});gx.createParentObj(wcquimiqueros);
