gx.evt.autoSkip=!1;
gx.define("wctanqueros",!1,function(){this.ServerClass="wctanqueros";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.skipOnEnter=this.hasEnterEvent=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){this.AV8ValorACalcular=gx.fn.getDecimalValue("vVALORACALCULAR",gx.thousandSeparator,gx.decimalPoint)};this.e130y1_client=function(){this.clearMessages();this.AV8ValorACalcular=this.AV11TanqueroBandaTM=this.AV9TanqueroBandaCPSUAB=
0;gx.fn.setCtrlProperty("RESULTADOPANAMAX","Caption",gx.text.format("%1","$0.00","","","","","","","",""));gx.fn.setCtrlProperty("RESULTADONEOPANAMAX","Caption",gx.text.format("%1","$0.00","","","","","","","",""));gx.fn.setCtrlProperty("RESULTADOLASTRE","Caption",gx.text.format("%1","$0.00","","","","","","","",""));this.refreshOutputs([{av:"AV9TanqueroBandaCPSUAB",fld:"vTANQUEROBANDACPSUAB"},{av:"AV11TanqueroBandaTM",fld:"vTANQUEROBANDATM"},{av:"AV8ValorACalcular",fld:"vVALORACALCULAR"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAX","Caption")',
ctrl:"RESULTADOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAX","Caption")',ctrl:"RESULTADONEOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOLASTRE","Caption")',ctrl:"RESULTADOLASTRE",prop:"Caption"}])};this.e110y2_client=function(){this.executeServerEvent("'CALCULAR'",false)};this.e140y2_client=function(){this.executeServerEvent("ENTER",true)};this.e150y2_client=function(){this.executeServerEvent("CANCEL",true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,3,
4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,35,36,38,39,40,41,42,43,44,47,49,50,51,54,56,57,58,61,63,64,65];this.GXLastCtrlId=65;a[2]={fld:"",grid:0};a[3]={fld:"MAINTABLE",grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};a[6]={fld:"GROUPTANQUEROTITULO",grid:0};a[7]={fld:"GROUP1TABLE",grid:0};a[8]={fld:"",grid:0};a[9]={fld:"",grid:0};a[10]={fld:"GRIDTABLE",grid:0};a[11]={fld:"",grid:0};a[12]={fld:"",grid:0};a[13]={fld:"TANQUEROBANDACPSUAB_CONTAINER",grid:0};a[14]={fld:"",
format:0,grid:0};a[15]={fld:"",grid:0};a[16]={lvl:0,type:"int",len:10,dec:0,sign:false,pic:"Z,ZZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vTANQUEROBANDACPSUAB",gxz:"ZV9TanqueroBandaCPSUAB",gxold:"OV9TanqueroBandaCPSUAB",gxvar:"AV9TanqueroBandaCPSUAB",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV9TanqueroBandaCPSUAB=gx.num.intval(a)},v2z:function(a){gx.O.ZV9TanqueroBandaCPSUAB=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vTANQUEROBANDACPSUAB",
gx.O.AV9TanqueroBandaCPSUAB,0)},c2v:function(){gx.O.AV9TanqueroBandaCPSUAB=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vTANQUEROBANDACPSUAB",gx.thousandSeparator)},nac:gx.falseFn};a[17]={fld:"",grid:0};a[18]={fld:"TANQUEROBANDATM_CONTAINER",grid:0};a[19]={fld:"",format:0,grid:0};a[20]={fld:"",grid:0};a[21]={lvl:0,type:"int",len:12,dec:0,sign:false,pic:"ZZZ,ZZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vTANQUEROBANDATM",gxz:"ZV11TanqueroBandaTM",
gxold:"OV11TanqueroBandaTM",gxvar:"AV11TanqueroBandaTM",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV11TanqueroBandaTM=gx.num.intval(a)},v2z:function(a){gx.O.ZV11TanqueroBandaTM=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vTANQUEROBANDATM",gx.O.AV11TanqueroBandaTM,0)},c2v:function(){gx.O.AV11TanqueroBandaTM=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vTANQUEROBANDATM",gx.thousandSeparator)},nac:gx.falseFn};a[22]={fld:"",grid:0};a[23]=
{fld:"DWT_CONTAINER",grid:0};a[24]={fld:"",format:0,grid:0};a[25]={fld:"",grid:0};a[26]={lvl:0,type:"int",len:12,dec:0,sign:false,pic:"ZZZ,ZZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vDWT",gxz:"ZV15DWT",gxold:"OV15DWT",gxvar:"AV15DWT",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV15DWT=gx.num.intval(a)},v2z:function(a){gx.O.ZV15DWT=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vDWT",gx.O.AV15DWT,0)},c2v:function(){gx.O.AV15DWT=gx.num.intval(this.val())},
val:function(){return gx.fn.getIntegerValue("vDWT",gx.thousandSeparator)},nac:gx.falseFn};a[27]={fld:"",grid:0};a[28]={fld:"",grid:0};a[29]={fld:"TABLE3",grid:0};a[35]={fld:"",grid:0};a[36]={fld:"",grid:0};a[38]={fld:"",grid:0};a[39]={fld:"",grid:0};a[40]={fld:"GROUPTANQUERORESULTADO",grid:0};a[41]={fld:"GROUP3TABLE",grid:0};a[42]={fld:"",grid:0};a[43]={fld:"",grid:0};a[44]={fld:"TABLE4",grid:0};a[47]={fld:"TEXTBLOCKRESULTADOPANAMAX",format:0,grid:0};a[49]={fld:"RESULTADOPANAMAX",format:0,grid:0};
a[50]={fld:"",grid:0};a[51]={fld:"TABLE1",grid:0};a[54]={fld:"TEXTBLOCKRESULTADONEOPANAMAX",format:0,grid:0};a[56]={fld:"RESULTADONEOPANAMAX",format:0,grid:0};a[57]={fld:"",grid:0};a[58]={fld:"TABLE2",grid:0};a[61]={fld:"TEXTBLOCKRESULTADOLASTRE",format:0,grid:0};a[63]={fld:"RESULTADOLASTRE",format:0,grid:0};a[64]={fld:"",grid:0};a[65]={fld:"",grid:0};this.AV15DWT=this.AV11TanqueroBandaTM=this.AV9TanqueroBandaCPSUAB=this.OV15DWT=this.ZV15DWT=this.AV15DWT=this.OV11TanqueroBandaTM=this.ZV11TanqueroBandaTM=
this.AV11TanqueroBandaTM=this.OV9TanqueroBandaCPSUAB=this.ZV9TanqueroBandaCPSUAB=this.AV9TanqueroBandaCPSUAB=0;this.AV14SdtResultado={};this.AV8ValorACalcular=0;this.Events={e110y2_client:["'CALCULAR'",true],e140y2_client:["ENTER",true],e150y2_client:["CANCEL",true],e130y1_client:["'LIMPIAR'",false]};this.EvtParms.REFRESH=[[],[]];this.EvtParms["'LIMPIAR'"]=[[],[{av:"AV9TanqueroBandaCPSUAB",fld:"vTANQUEROBANDACPSUAB"},{av:"AV11TanqueroBandaTM",fld:"vTANQUEROBANDATM"},{av:"AV8ValorACalcular",fld:"vVALORACALCULAR"},
{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAX","Caption")',ctrl:"RESULTADOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAX","Caption")',ctrl:"RESULTADONEOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOLASTRE","Caption")',ctrl:"RESULTADOLASTRE",prop:"Caption"}]];this.EvtParms["'CALCULAR'"]=[[{av:"AV9TanqueroBandaCPSUAB",fld:"vTANQUEROBANDACPSUAB"},{av:"AV15DWT",fld:"vDWT"},{av:"AV11TanqueroBandaTM",fld:"vTANQUEROBANDATM"},{av:"AV14SdtResultado",fld:"vSDTRESULTADO"}],
[{av:"AV14SdtResultado",fld:"vSDTRESULTADO"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAX","Caption")',ctrl:"RESULTADOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAX","Caption")',ctrl:"RESULTADONEOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADOLASTRE","Caption")',ctrl:"RESULTADOLASTRE",prop:"Caption"}]];this.setVCMap("AV8ValorACalcular","vVALORACALCULAR",0,"decimal");this.InitStandaloneVars();this.setComponent({id:"COMPONENT1",GXClass:"wcnota",Prefix:"W0066",
lvl:1})});gx.createParentObj(wctanqueros);
