gx.evt.autoSkip=!1;
gx.define("webportacontenedores",!1,function(){this.ServerClass="webportacontenedores";this.PackageName="GeneXus.Programs";this.setObjectType("web");this.skipOnEnter=this.hasEnterEvent=false;this.ajaxSecurityToken=this.supportAjaxEvents=this.fullAjax=this.autoRefresh=true;this.SetStandaloneVars=function(){};this.Validv_Capacidaddecontenedores=function(){try{var a=gx.util.balloon.getNew("vCAPACIDADDECONTENEDORES");this.AnyError=0}catch(b){}try{return a==null?true:a.show()}catch(c){}return true};this.Validv_Cargateu=
function(){gx.ajax.validSrvEvt("dyncall","Validv_Cargateu",["gx.O.AV6CargaTEU","gx.O.AV5CapacidadDeContenedores","gx.num.urlDecimal(gx.O.AV7PorcentajeDeCarga,gx.thousandSeparator,gx.decimalPoint)"],["AV7PorcentajeDeCarga"]);return true};this.e141y1_client=function(){this.clearMessages();this.s112_client();this.refreshOutputs([{av:"AV6CargaTEU",fld:"vCARGATEU"},{av:"AV5CapacidadDeContenedores",fld:"vCAPACIDADDECONTENEDORES"},{av:"AV7PorcentajeDeCarga",fld:"vPORCENTAJEDECARGA"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAX","Caption")',
ctrl:"RESULTADOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAX","Caption")',ctrl:"RESULTADONEOPANAMAX",prop:"Caption"}])};this.s112_client=function(){this.AV7PorcentajeDeCarga=this.AV5CapacidadDeContenedores=this.AV6CargaTEU=0;gx.fn.setCtrlProperty("RESULTADOPANAMAX","Caption",gx.text.format("%1","$0.00","","","","","","","",""));gx.fn.setCtrlProperty("RESULTADONEOPANAMAX","Caption",gx.text.format("%1","$0.00","","","","","","","",""))};this.e111y2_client=function(){this.executeServerEvent("'CALCULAR'",
false)};this.e151y2_client=function(){this.executeServerEvent("ENTER",true)};this.e161y2_client=function(){this.executeServerEvent("CANCEL",true)};var a=this.GXValidFnc=[];this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,35,36,38,39,40,41,42,43,44,47,49,50,51,54,56,57,58,60,61,62];this.GXLastCtrlId=62;a[2]={fld:"",grid:0};a[3]={fld:"MAINTABLE",grid:0};a[4]={fld:"",grid:0};a[5]={fld:"",grid:0};a[6]={fld:"GROUP1",grid:0};a[7]={fld:"GROUP1TABLE",grid:0};a[8]=
{fld:"",grid:0};a[9]={fld:"",grid:0};a[10]={fld:"GRIDTABLE",grid:0};a[11]={fld:"",grid:0};a[12]={fld:"",grid:0};a[13]={fld:"CAPACIDADDECONTENEDORES_CONTAINER",grid:0};a[14]={fld:"",format:0,grid:0};a[15]={fld:"",grid:0};a[16]={lvl:0,type:"int",len:6,dec:0,sign:false,pic:"ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Validv_Capacidaddecontenedores,isvalid:null,rgrid:[],fld:"vCAPACIDADDECONTENEDORES",gxz:"ZV5CapacidadDeContenedores",gxold:"OV5CapacidadDeContenedores",gxvar:"AV5CapacidadDeContenedores",
ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV5CapacidadDeContenedores=gx.num.intval(a)},v2z:function(a){gx.O.ZV5CapacidadDeContenedores=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCAPACIDADDECONTENEDORES",gx.O.AV5CapacidadDeContenedores,0)},c2v:function(){gx.O.AV5CapacidadDeContenedores=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCAPACIDADDECONTENEDORES",gx.thousandSeparator)},nac:gx.falseFn};a[17]={fld:"",grid:0};a[18]={fld:"CARGATEU_CONTAINER",
grid:0};a[19]={fld:"",format:0,grid:0};a[20]={fld:"",grid:0};a[21]={lvl:0,type:"int",len:6,dec:0,sign:false,pic:"ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:this.Validv_Cargateu,isvalid:null,rgrid:[],fld:"vCARGATEU",gxz:"ZV6CargaTEU",gxold:"OV6CargaTEU",gxvar:"AV6CargaTEU",ucs:[],op:[26],ip:[26,16,21],nacdep:[],ctrltype:"edit",v2v:function(a){gx.O.AV6CargaTEU=gx.num.intval(a)},v2z:function(a){gx.O.ZV6CargaTEU=gx.num.intval(a)},v2c:function(){gx.fn.setControlValue("vCARGATEU",gx.O.AV6CargaTEU,0)},c2v:function(){gx.O.AV6CargaTEU=
gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vCARGATEU",gx.thousandSeparator)},nac:gx.falseFn};a[22]={fld:"",grid:0};a[23]={fld:"PORCENTAJEDECARGA_CONTAINER",grid:0};a[24]={fld:"",format:0,grid:0};a[25]={fld:"",grid:0};a[26]={lvl:0,type:"decimal",len:6,dec:2,sign:false,pic:"ZZ9.99",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,rgrid:[],fld:"vPORCENTAJEDECARGA",gxz:"ZV7PorcentajeDeCarga",gxold:"OV7PorcentajeDeCarga",gxvar:"AV7PorcentajeDeCarga",ucs:[],op:[],ip:[],nacdep:[],
ctrltype:"edit",v2v:function(a){gx.O.AV7PorcentajeDeCarga=gx.fn.toDecimalValue(a,",",".")},v2z:function(a){gx.O.ZV7PorcentajeDeCarga=gx.fn.toDecimalValue(a,gx.thousandSeparator,gx.decimalPoint)},v2c:function(){gx.fn.setDecimalValue("vPORCENTAJEDECARGA",gx.O.AV7PorcentajeDeCarga,2,gx.decimalPoint)},c2v:function(){gx.O.AV7PorcentajeDeCarga=this.val()},val:function(){return gx.fn.getDecimalValue("vPORCENTAJEDECARGA",gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};a[27]={fld:"",grid:0};a[28]={fld:"",
grid:0};a[29]={fld:"TABLE3",grid:0};a[35]={fld:"",grid:0};a[36]={fld:"",grid:0};a[38]={fld:"",grid:0};a[39]={fld:"",grid:0};a[40]={fld:"GROUPTANQUERORESULTADO",grid:0};a[41]={fld:"GROUPTANQUERORESULTADOTABLE",grid:0};a[42]={fld:"",grid:0};a[43]={fld:"",grid:0};a[44]={fld:"TABLE1",grid:0};a[47]={fld:"TEXTBLOCKRESULTADOPANAMAX",format:0,grid:0};a[49]={fld:"RESULTADOPANAMAX",format:0,grid:0};a[50]={fld:"",grid:0};a[51]={fld:"TABLE2",grid:0};a[54]={fld:"TEXTBLOCKRESULTADONEOPANAMAX",format:0,grid:0};
a[56]={fld:"RESULTADONEOPANAMAX",format:0,grid:0};a[57]={fld:"",grid:0};a[58]={fld:"",grid:0};a[60]={fld:"",grid:0};a[61]={fld:"",grid:0};a[62]={fld:"TEXTBLOCK1",format:2,grid:0};this.AV7PorcentajeDeCarga=this.AV6CargaTEU=this.AV5CapacidadDeContenedores=this.OV7PorcentajeDeCarga=this.ZV7PorcentajeDeCarga=this.AV7PorcentajeDeCarga=this.OV6CargaTEU=this.ZV6CargaTEU=this.AV6CargaTEU=this.OV5CapacidadDeContenedores=this.ZV5CapacidadDeContenedores=this.AV5CapacidadDeContenedores=0;this.AV8SdtResultado=
{};this.Events={e111y2_client:["'CALCULAR'",true],e151y2_client:["ENTER",true],e161y2_client:["CANCEL",true],e141y1_client:["'LIMPIAR'",false],s112_client:["'LIMPIARCALCULOS'",false]};this.EvtParms.REFRESH=[[],[]];this.EvtParms["'LIMPIAR'"]=[[],[{av:"AV6CargaTEU",fld:"vCARGATEU"},{av:"AV5CapacidadDeContenedores",fld:"vCAPACIDADDECONTENEDORES"},{av:"AV7PorcentajeDeCarga",fld:"vPORCENTAJEDECARGA"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAX","Caption")',ctrl:"RESULTADOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAX","Caption")',
ctrl:"RESULTADONEOPANAMAX",prop:"Caption"}]];this.EvtParms["'CALCULAR'"]=[[{av:"AV5CapacidadDeContenedores",fld:"vCAPACIDADDECONTENEDORES"},{av:"AV6CargaTEU",fld:"vCARGATEU"},{av:"AV8SdtResultado",fld:"vSDTRESULTADO"}],[{av:"AV8SdtResultado",fld:"vSDTRESULTADO"},{av:'gx.fn.getCtrlProperty("RESULTADOPANAMAX","Caption")',ctrl:"RESULTADOPANAMAX",prop:"Caption"},{av:'gx.fn.getCtrlProperty("RESULTADONEOPANAMAX","Caption")',ctrl:"RESULTADONEOPANAMAX",prop:"Caption"},{av:"AV6CargaTEU",fld:"vCARGATEU"},{av:"AV5CapacidadDeContenedores",
fld:"vCAPACIDADDECONTENEDORES"},{av:"AV7PorcentajeDeCarga",fld:"vPORCENTAJEDECARGA"}]];this.InitStandaloneVars();this.setComponent({id:"COMPONENT1",GXClass:"wcnota",Prefix:"W0059",lvl:1})});gx.createParentObj(webportacontenedores);
